"""Large-Nf axial RG and constant-background vacuum diagnostics for 032V19R2.

PURPOSE
-------
Determine whether the structurally red fixed-order axial wavefunction result
from 032V19R1 represents:

1. genuine strong-coupling failure,

or

2. an order-one collective wavefunction correction generated by many
   individually weak hidden-fermion species that can be reorganized through
   the exact fermion determinant and canonical matching.

This module also constructs a symmetry-restored constant-spacelike-axial
vacuum-energy scout.

SOURCE INTERACTION
------------------
The low-energy source interaction is

    L_int
        =
        (1/f_psi)
        partial_mu(phi)
        bar(Psi) gamma^mu gamma^5 Psi.

For a gauge-singlet Dirac fermion, integration by parts and the axial Ward
identity motivate the equivalent pseudoscalar coupling convention

    g_p = 2 m_psi / f_psi.

This is the same convention already used by ANTIGRAVITY_RESEARCH.

LARGE-NF ORGANIZATION
---------------------
Define

    epsilon_1
        =
        g_p^2 / (16 pi^2)

and

    L
        =
        N_f epsilon_1
        =
        N_f m_psi^2 / (4 pi^2 f_psi^2).

If N_f is large while L remains fixed, then

    epsilon_1 ~ 1/N_f.

The fermion determinant is order N_f.

Higher induced scalar vertices scale with additional powers of 1/N_f.

Therefore an order-one two-point correction does not automatically imply
that every loop order is uncontrolled.

VACUUM SCOUT
------------
The exact positive-energy axial bands are

    E_s^2
        =
        p_perp^2
        +
        (
            sqrt(p_z^2 + m^2)
            +
            s b
        )^2,

with

    s = -1, +1.

The static Dirac-sea difference is evaluated with a rotational three-momentum
cutoff.

A massless reference is subtracted:

    Delta V_sym
        =
        Delta V(m,b)
        -
        Delta V(0,b).

This enforces the expected gauge-singlet massless decoupling and removes the
power divergence that a naive hard cutoff would otherwise introduce.

The remaining quadratic divergence structure is logarithmic and corresponds
to scalar wavefunction renormalization.

The exact quadratic contribution is subtracted again when examining the
nonlinear b^4-and-higher remainder.

IMPORTANT
---------
The resulting nonlinear remainder is a REGULATOR / MATCHING SCOUT.

It is not a unique physical vacuum energy because local higher-derivative
counterterms are allowed.

Boundary/Casimir contributions are also absent.

CLAIM LIMITS
------------
This module does NOT establish:

- a complete covariant renormalization scheme;
- a full beta-function system for C1, f_psi, m_psi and companion operators;
- an ultraviolet completion;
- boundary/Casimir vacuum energy;
- nonlinear chi/Psi/phi stability;
- empirical viability;
- complete operating energy;
- a practical antigravity device.
"""

from __future__ import annotations

import math

import numpy as np

from antigravity_research.agminer.kinetic_conformal import (
    EV_J,
    HBARC_EV_M,
)


PI = math.pi


def ev4_energy_density_j_m3(
    density_ev4: float,
) -> float:
    """Convert natural-unit eV^4 density to J/m^3."""

    return (
        float(
            density_ev4
        )
        * EV_J
        / HBARC_EV_M**3
    )


def pseudoscalar_equivalent_coupling(
    *,
    mass_ev: float,
    f_psi_ev: float,
) -> float:
    """Return the project convention g_p = 2 m_psi / f_psi."""

    mass = float(
        mass_ev
    )

    f_value = float(
        f_psi_ev
    )

    if (
        mass <= 0.0
        or f_value <= 0.0
    ):
        raise ValueError(
            "mass and f_psi must be positive"
        )

    return (
        2.0
        * mass
        / f_value
    )


def large_nf_power_counting(
    *,
    flavors: int,
    mass_ev: float,
    f_psi_ev: float,
) -> dict[str, float | bool]:
    """Return transparent large-Nf expansion parameters.

    The collective loop parameter is

        L
            =
            N_f g_p^2
            /
            (16 pi^2).

    At fixed L and large N_f:

        g_p^2/(16 pi^2)
            =
            L/N_f

    and a representative induced four-point scalar loop scales as

        L^2/N_f.
    """

    nf = int(
        flavors
    )

    if nf < 1:
        raise ValueError(
            "flavors must be positive"
        )

    g_p = (
        pseudoscalar_equivalent_coupling(
            mass_ev=
                mass_ev,

            f_psi_ev=
                f_psi_ev,
        )
    )

    single_flavor_loop = (
        g_p**2
        /
        (
            16.0
            * PI**2
        )
    )

    collective_loop = (
        nf
        * single_flavor_loop
    )

    one_over_nf = (
        1.0
        / nf
    )

    induced_four_point = (
        collective_loop**2
        / nf
    )

    controlled_scout = (
        single_flavor_loop
        <
        1.0e-2
        and
        one_over_nf
        <
        1.0e-2
        and
        induced_four_point
        <
        1.0e-3
    )

    return {
        "g_p_equivalent":
            g_p,

        "single_flavor_loop":
            single_flavor_loop,

        "collective_loop":
            collective_loop,

        "one_over_nf":
            one_over_nf,

        "induced_four_point_scaling":
            induced_four_point,

        "large_nf_power_counting_scout":
            controlled_scout,
    }


def field_rescaling_scout(
    *,
    f_psi_ev: float,
    c1_ev_m4: float,
    collective_loop: float,
    delta_z: float,
) -> dict[str, float | bool]:
    """Canonicalize one positive wavefunction factor.

    This is an algebraic field-rescaling scout, not a complete RGE.

    For

        Z = 1 + Delta Z

    and

        phi_c = sqrt(Z) phi,

    one has

        f_c = f sqrt(Z)

        C1_c = C1/Z

    and therefore

        C1_c f_c^2 = C1 f^2.

    The loop proxy expressed only through the rescaled f becomes L/Z if the
    fermion mass is held fixed.

    Full running of m, f, C1 and companion Wilson coefficients remains open.
    """

    f_value = float(
        f_psi_ev
    )

    c1 = float(
        c1_ev_m4
    )

    loop = float(
        collective_loop
    )

    dz = float(
        delta_z
    )

    if (
        f_value <= 0.0
        or c1 <= 0.0
        or loop <= 0.0
    ):
        raise ValueError(
            "positive matching parameters required"
        )

    z_factor = (
        1.0
        + dz
    )

    if z_factor <= 0.0:
        raise ValueError(
            "wavefunction factor is nonpositive"
        )

    sqrt_z = math.sqrt(
        z_factor
    )

    f_rescaled = (
        f_value
        * sqrt_z
    )

    c1_rescaled = (
        c1
        / z_factor
    )

    original_invariant = (
        c1
        * f_value**2
    )

    rescaled_invariant = (
        c1_rescaled
        * f_rescaled**2
    )

    return {
        "z_factor":
            z_factor,

        "f_rescaled_ev":
            f_rescaled,

        "c1_rescaled_ev_m4":
            c1_rescaled,

        "collective_loop_rescaled":
            (
                loop
                / z_factor
            ),

        "invariant_original":
            original_invariant,

        "invariant_rescaled":
            rescaled_invariant,

        "invariant_relative_error":
            (
                abs(
                    rescaled_invariant
                    - original_invariant
                )
                / original_invariant
            ),

        "positive_kinetic_factor":
            True,

        "full_rge_completed":
            False,
    }


def _gauss_interval(
    order: int,
    upper: float,
) -> tuple[np.ndarray, np.ndarray]:
    """Return Gauss-Legendre nodes and weights on [0, upper]."""

    if order < 24:
        raise ValueError(
            "quadrature order must be at least 24"
        )

    if upper <= 0.0:
        raise ValueError(
            "upper integration limit must be positive"
        )

    nodes, weights = (
        np.polynomial.legendre.leggauss(
            int(
                order
            )
        )
    )

    x = (
        0.5
        * upper
        * (
            nodes
            + 1.0
        )
    )

    w = (
        0.5
        * upper
        * weights
    )

    return x, w


def symmetry_restored_axial_vacuum_density_ev4(
    *,
    mass_ev: float,
    axial_b_ev: float,
    flavors: int,
    cutoff_ev: float,
    p_order: int = 160,
    u_order: int = 120,
) -> float:
    """Return a symmetry-restored constant-b vacuum determinant scout.

    Compute

        -N_f integral d^3p/(2pi)^3
        [
            E_-(m,b)+E_+(m,b)-2E_0(m)
            -
            (
                E_-(0,b)+E_+(0,b)-2|p|
            )
        ].

    The massless subtraction enforces the expected decoupling of an
    anomaly-free gauge-singlet derivative axial coupling in the m -> 0 limit.

    This is not yet a complete covariant renormalization prescription.
    """

    mass = float(
        mass_ev
    )

    b_value = float(
        axial_b_ev
    )

    nf = int(
        flavors
    )

    cutoff = float(
        cutoff_ev
    )

    if (
        mass < 0.0
        or b_value < 0.0
        or nf < 1
        or cutoff <= 0.0
    ):
        raise ValueError(
            "invalid vacuum determinant input"
        )

    p, p_weights = (
        _gauss_interval(
            int(
                p_order
            ),
            cutoff,
        )
    )

    u, u_weights = (
        np.polynomial.legendre.leggauss(
            int(
                u_order
            )
        )
    )

    p_grid = p[
        :,
        None,
    ]

    u_grid = u[
        None,
        :,
    ]

    p_perp_sq = (
        p_grid**2
        * (
            1.0
            - u_grid**2
        )
    )

    e0_massive = np.sqrt(
        p_grid**2
        + mass**2
    )

    axial_root_massive = np.sqrt(
        (
            p_grid
            * u_grid
        )**2
        + mass**2
    )

    e_minus_massive = np.sqrt(
        p_perp_sq
        +
        (
            axial_root_massive
            - b_value
        )**2
    )

    e_plus_massive = np.sqrt(
        p_perp_sq
        +
        (
            axial_root_massive
            + b_value
        )**2
    )

    massive_difference = (
        e_minus_massive
        + e_plus_massive
        - 2.0
        * e0_massive
    )

    axial_root_massless = np.abs(
        p_grid
        * u_grid
    )

    e_minus_massless = np.sqrt(
        p_perp_sq
        +
        (
            axial_root_massless
            - b_value
        )**2
    )

    e_plus_massless = np.sqrt(
        p_perp_sq
        +
        (
            axial_root_massless
            + b_value
        )**2
    )

    massless_difference = (
        e_minus_massless
        + e_plus_massless
        - 2.0
        * p_grid
    )

    integrand = (
        p_grid**2
        * (
            massive_difference
            - massless_difference
        )
    )

    integral = float(
        np.sum(
            p_weights[
                :,
                None,
            ]
            * u_weights[
                None,
                :,
            ]
            * integrand
        )
    )

    return (
        -nf
        * integral
        /
        (
            4.0
            * PI**2
        )
    )


def quadratic_wavefunction_density_ev4(
    *,
    mass_ev: float,
    axial_b_ev: float,
    flavors: int,
    cutoff_ev: float,
    order: int = 256,
) -> float:
    """Return the exact b^2 piece of the symmetry-restored cutoff scout.

    After angular integration,

        V_2
            =
            -N_f b^2/(3 pi^2)
            integral_0^Lambda
            [
                p^4/(p^2+m^2)^(3/2)
                -
                p
            ] dp.

    At large cutoff,

        d V_2 / d ln Lambda
            ->
            N_f m^2 b^2/(2 pi^2).

    This is the universal logarithmic wavefunction coefficient reproduced by
    the V17/V18 leading-log diagnostic.
    """

    mass = float(
        mass_ev
    )

    b_value = float(
        axial_b_ev
    )

    nf = int(
        flavors
    )

    cutoff = float(
        cutoff_ev
    )

    if (
        mass < 0.0
        or b_value < 0.0
        or nf < 1
        or cutoff <= 0.0
    ):
        raise ValueError(
            "invalid quadratic vacuum input"
        )

    p, weights = (
        _gauss_interval(
            int(
                order
            ),
            cutoff,
        )
    )

    integrand = (
        p**4
        /
        (
            p**2
            + mass**2
        )**1.5
        -
        p
    )

    integral = float(
        np.sum(
            weights
            * integrand
        )
    )

    return (
        -nf
        * b_value**2
        /
        (
            3.0
            * PI**2
        )
        * integral
    )


def nonlinear_vacuum_remainder_ev4(
    *,
    mass_ev: float,
    axial_b_ev: float,
    flavors: int,
    cutoff_ev: float,
    p_order: int = 160,
    u_order: int = 120,
) -> float:
    """Return the b^4-and-higher remainder after b^2 subtraction.

    This remainder is useful as a magnitude and convergence scout.

    It is NOT automatically a physical energy because finite local
    higher-derivative counterterms remain matching dependent.
    """

    full = (
        symmetry_restored_axial_vacuum_density_ev4(
            mass_ev=
                mass_ev,

            axial_b_ev=
                axial_b_ev,

            flavors=
                flavors,

            cutoff_ev=
                cutoff_ev,

            p_order=
                p_order,

            u_order=
                u_order,
        )
    )

    quadratic = (
        quadratic_wavefunction_density_ev4(
            mass_ev=
                mass_ev,

            axial_b_ev=
                axial_b_ev,

            flavors=
                flavors,

            cutoff_ev=
                cutoff_ev,

            order=
                max(
                    192,
                    p_order,
                ),
        )
    )

    return (
        full
        - quadratic
    )


def asymptotic_quadratic_log_slope_ev4(
    *,
    mass_ev: float,
    axial_b_ev: float,
    flavors: int,
) -> float:
    """Return N_f m^2 b^2/(2 pi^2)."""

    mass = float(
        mass_ev
    )

    b_value = float(
        axial_b_ev
    )

    nf = int(
        flavors
    )

    return (
        nf
        * mass**2
        * b_value**2
        /
        (
            2.0
            * PI**2
        )
    )


def finite_cutoff_quadratic_log_slope_ev4(
    *,
    mass_ev: float,
    axial_b_ev: float,
    flavors: int,
    cutoff_ev: float,
) -> float:
    """Return dV_2/dln(Lambda) at finite cutoff."""

    mass = float(
        mass_ev
    )

    b_value = float(
        axial_b_ev
    )

    nf = int(
        flavors
    )

    cutoff = float(
        cutoff_ev
    )

    energy = math.sqrt(
        cutoff**2
        + mass**2
    )

    return (
        -nf
        * b_value**2
        /
        (
            3.0
            * PI**2
        )
        * cutoff
        * (
            cutoff**4
            / energy**3
            - cutoff
        )
    )


def natural_b4_loop_scale_ev4(
    *,
    axial_b_ev: float,
    flavors: int,
) -> float:
    """Return N_f b^4/(16 pi^2) as a local nonlinear loop scale."""

    b_value = float(
        axial_b_ev
    )

    nf = int(
        flavors
    )

    if (
        b_value < 0.0
        or nf < 1
    ):
        raise ValueError(
            "invalid b^4 scale input"
        )

    return (
        nf
        * b_value**4
        /
        (
            16.0
            * PI**2
        )
    )


def bulk_derivative_expansion_scout(
    *,
    mass_ev: float,
    source_radius_m: float,
) -> dict[str, float | bool]:
    """Compare source radius with hidden-fermion Compton length."""

    mass = float(
        mass_ev
    )

    radius = float(
        source_radius_m
    )

    if (
        mass <= 0.0
        or radius <= 0.0
    ):
        raise ValueError(
            "positive mass and radius required"
        )

    compton = (
        HBARC_EV_M
        / mass
    )

    ratio = (
        radius
        / compton
    )

    return {
        "fermion_compton_length_m":
            compton,

        "source_radius_over_compton":
            ratio,

        "bulk_slow_variation_scout":
            (
                ratio
                >
                1.0e5
            ),

        "boundary_layer_automatically_controlled":
            False,
    }


def jiang_positive_c1_spin2_template() -> dict[str, float | bool | str]:
    """Return the published positive-C1 spin-2 matching ratios used by V18.

    This is a provenance/falsification record only.

    The template cannot be directly adopted as a pure j=0 universal
    kinetic-conformal completion because it simultaneously generates j=2
    companion coefficients.
    """

    return {
        "c2_over_c1":
            12.0,

        "c4_over_c1":
            -12.0,

        "pure_j0_completion":
            False,

        "directly_adopted":
            False,

        "reason":
            "NONZERO_J2_COMPANION_OPERATORS",
    }
