"""032H17A12D — Pauli/magnetization source reopening for the A12B/A12C carrier.

PURPOSE
-------
A12C established two facts simultaneously:

1. the exact A12B massless carrier plus the gauge-invariant F_X^2 universal
   metric possesses a finite reduced-EFT 1 kg / 1 m / whole-payload >=1g
   witness with a very small field term;

2. the stable ordinary renormalizable payload-silent vector current is
   electromagnetic-like, and the corresponding photon-aligned F^2 metric
   fails the MRI empirical sanity gate by orders of magnitude.

The correct next question is therefore source-selective:

    Can an identically conserved Pauli/magnetization current source the
    A12B carrier strongly enough under real massless-vector constraints?

This is especially important because A11A already proved that the desired
compact azimuthal source morphology is EXACTLY the curl of a compact
magnetization profile.  A11A nevertheless closed the simple electron Pauli
lane because it compared against the much more expensive A10F2 source-energy
requirement.

That old energy closeout is not automatically transferable to the radically
lower-capacity A12C F_X^2 metric.

EXTERNAL ELECTRON-DIPOLE BOUND
------------------------------
The massless-dark-photon review arXiv:2005.01515 writes the electroweak
gauge-invariant magnetic-dipole interaction as

    L =
      e_D/(2 Lambda^2)
      bar(psi_L) sigma^{mu nu} D_M H psi_R F^X_{mu nu}
      + h.c.

and gives the stellar-cooling bound

    Lambda^2 / (sqrt(alpha_D) d_M^e)
        >= 4.5e6 TeV^2.

After electroweak symmetry breaking, with v_h=174 GeV,

    1/M_eff
        =
    e_D d_M^e v_h / (2 Lambda^2).

Using e_D=sqrt(4*pi*alpha_D), the alpha_D dependence cancels and gives

    M_eff
        >=
    [4.5e6 TeV^2] / [sqrt(pi) v_h].

This branch deliberately saturates that bound to maximize source strength.

PROJECT PAULI NORMALIZATION
---------------------------
A11A used

    L_int
        =
    (1/M_eff) F_X^{mu nu} bar(e) sigma_{mu nu} e

and the optimistic characteristic-momentum coupling

    g_eff
        =
    2 q / M_eff.

For a maximally polarized static electron source, give each source electron
the largest possible O(1) tensor bilinear in the same normalization.

For the canonical Maxwell source integral I_J generated by A12C,

    N_e >= I_J / (g_eff hbar*c).

This is intentionally optimistic:

- 100% useful spin polarization is assumed;
- no host ions are charged to the energy ledger;
- no ordinary magnetic-field energy is charged;
- no preparation/polarization energy is charged;
- no support, confinement, cooling, control, or reset is charged;
- no radiative kinetic mixing is yet charged;
- no source backreaction is charged.

It is therefore a LOWER BOUND suitable to reject or identify headroom,
never to certify a device.

A12C SCALING
------------
For fixed 1g / 1m physical response of the F_X^2 metric,

    required canonical source ~ M_g^2
    field energy              ~ M_g^4,

where M_g is the universal-metric portal scale.

This lets us reuse the converged A12C BVP exactly rather than rerunning it.

EFT / SCALE-SEPARATION DIAGNOSTIC
---------------------------------
The source morphology has characteristic momentum

    q = hbar*c / R_source.

For the local metric interaction suppressed by M_g, a useful EFT requires
a hierarchy q/M_g << 1.

This run does not impose an arbitrary hard "10x" theorem.  Instead it reports
the exact maximum M_g/q permitted by the strict partial 10-MJ boundary.

If that maximum is O(1), the local portal has no parametric scale separation.
An explicit low-scale or nonperturbative UV completion could still exist and
is NOT closed by this diagnostic.

IMPORTANT SOURCE-SELECTIVITY POINT
----------------------------------
This Pauli current is not the renormalizable electromagnetic-like J_EM
source closed in A12C.

It is derivative and spin dependent.

Therefore the A12C MRI photon-alignment kill does NOT automatically transfer.

The appropriate next gate, if a source-energy corridor exists, is instead:

- explicit UV completion / operator provenance;
- radiatively generated kinetic mixing;
- spin-source fifth-force / laboratory constraints;
- source support and polarization energy;
- full quantum/RG control.

CLAIM LIMITS
------------
A green or yellow result here is not a physical antigravity model.

This branch does not establish:

- a controlled UV completion;
- radiatively stable zero photon mixing;
- exact direct-force silence for arbitrary payload spin states;
- full source support/confinement;
- complete operating energy below 10 MJ;
- loaded nonlinear backreaction;
- a practical device.

A red result closes only the minimal electron Pauli realization under the
declared assumptions, not all derivative/composite currents or HOOK17.
"""

from __future__ import annotations

import json
import math
from functools import lru_cache
from pathlib import Path
from typing import Any

from .hook17_exact_current_protection_atlas import (
    pauli_source_shape_identity,
)


HBAR_C_EV_M = 1.973269804e-7
EV_J = 1.602176634e-19

ELECTRON_MASS_EV = 510_998.95
HIGGS_VEV_EV = 174.0e9

STRICT_COMPLETE_OPERATING_TARGET_J = 1.0e7

# Fabbrichesi, Gabrielli, Lanfranchi, "The Dark Photon",
# arXiv:2005.01515, Eq. (2.9).
STELLAR_ELECTRON_DIPLOE_BOUND_TEV2 = 4.5e6

# Diagnostic margins only.  The exact ratio itself is always reported.
TWO_X_SCALE_MARGIN = 2.0
TEN_X_SCALE_MARGIN = 10.0


def _repo_root() -> Path:
    """Return repository root from src/antigravity_research/agminer."""

    return (
        Path(__file__)
        .resolve()
        .parents[3]
    )


@lru_cache(maxsize=1)
def a12c_artifact() -> dict[str, Any]:
    """Load authoritative local A12C summary without rerunning its BVP."""

    path = (
        _repo_root()
        / "results"
        / "data"
        / "032h17a12c_hook17_concurrent_u1_fieldstrength_metric_summary.json"
    )

    if not path.exists():
        raise FileNotFoundError(
            str(path)
        )

    return json.loads(
        path.read_text(
            encoding="utf-8"
        )
    )


@lru_cache(maxsize=1)
def a11a_artifact() -> dict[str, Any]:
    """Load A11A source-protection artifact for exact historical provenance."""

    path = (
        _repo_root()
        / "results"
        / "data"
        / "032h17a11a_hook17_exact_current_protection_atlas_summary.json"
    )

    if not path.exists():
        raise FileNotFoundError(
            str(path)
        )

    return json.loads(
        path.read_text(
            encoding="utf-8"
        )
    )


@lru_cache(maxsize=1)
def provenance_gate() -> dict[str, Any]:
    """Require the exact scientific handoff from A11A and A12C."""

    a12c = a12c_artifact()
    a11a = a11a_artifact()

    a12c_production = (
        a12c[
            "massless_f2_finite_payload_bvp"
        ][
            "production"
        ]
    )

    a11a_pauli = (
        a11a[
            "pauli_derivative_exact_current"
        ]
    )

    passed = bool(
        a12c[
            "branch"
        ]
        ==
        "032H17A12C"

        and

        a12c[
            "gauge_invariant_massless_f2_reduced_eft_1g_1m_witness"
        ]
        is True

        and

        a12c[
            "ordinary_em_like_minimal_f2_a12b_realization_closed"
        ]
        is True

        and

        a12c[
            "a12b_exact_massless_carrier_closed"
        ]
        is False

        and

        a12c[
            "hook17_closed"
        ]
        is False

        and

        a11a_pauli[
            "source_shape"
        ][
            "source_shape_identity_pass"
        ]
        is True

        and

        a11a_pauli[
            "simple_dimension5_pauli_current_valid_through_electron_threshold_closed"
        ]
        is True

        and

        a11a_pauli[
            "explicit_uv_completion_below_electron_threshold_closed"
        ]
        is False

        and

        math.isclose(
            float(
                a12c_production[
                    "geometric_external_standoff_m"
                ]
            ),
            1.0,
            rel_tol=0.0,
            abs_tol=1.0e-12,
        )
    )

    return {
        "pass":
            passed,

        "a12c_branch":
            a12c[
                "branch"
            ],

        "a12c_reduced_f2_1g_1m":
            a12c[
                "gauge_invariant_massless_f2_reduced_eft_1g_1m_witness"
            ],

        "a12b_carrier_preserved":
            not a12c[
                "a12b_exact_massless_carrier_closed"
            ],

        "a11a_simple_pauli_was_closed_under_old_energy_requirement":
            a11a_pauli[
                "simple_dimension5_pauli_current_valid_through_electron_threshold_closed"
            ],

        "a11a_explicit_lower_scale_uv_completion_was_not_closed":
            not a11a_pauli[
                "explicit_uv_completion_below_electron_threshold_closed"
            ],
    }


@lru_cache(maxsize=1)
def pauli_geometry_gate() -> dict[str, Any]:
    """Verify exact source morphology and independent 2-m momentum scale."""

    a12c = a12c_artifact()
    a11a = a11a_artifact()

    shape = (
        pauli_source_shape_identity()
    )

    production = (
        a12c[
            "massless_f2_finite_payload_bvp"
        ][
            "production"
        ]
    )

    source_radius_m = float(
        production[
            "source_radius_m"
        ]
    )

    q_from_radius_ev = (
        HBAR_C_EV_M
        /
        source_radius_m
    )

    q_a11a_ev = float(
        a11a[
            "pauli_derivative_exact_current"
        ][
            "characteristic_source_q_ev"
        ]
    )

    q_identity = math.isclose(
        q_from_radius_ev,
        q_a11a_ev,
        rel_tol=1.0e-12,
        abs_tol=0.0,
    )

    return {
        "source_shape_identity_pass":
            shape[
                "source_shape_identity_pass"
            ],

        "derivative_current_identically_conserved":
            shape[
                "derivative_current_identically_conserved"
            ],

        "magnetization_profile":
            shape[
                "magnetization_profile"
            ],

        "target_source_shape":
            shape[
                "target_source_shape"
            ],

        "source_radius_m":
            source_radius_m,

        "q_from_source_radius_ev":
            q_from_radius_ev,

        "q_from_a11a_ev":
            q_a11a_ev,

        "q_identity_pass":
            q_identity,
    }


@lru_cache(maxsize=1)
def stellar_electron_pauli_bound_gate() -> dict[str, Any]:
    """Translate the massless-vector stellar electron-dipole bound."""

    bound_ev2 = (
        STELLAR_ELECTRON_DIPLOE_BOUND_TEV2
        *
        (
            1.0e12
        ) ** 2
    )

    minimum_effective_scale_ev = (
        bound_ev2
        /
        (
            math.sqrt(
                math.pi
            )
            *
            HIGGS_VEV_EV
        )
    )

    q_ev = float(
        pauli_geometry_gate()[
            "q_from_source_radius_ev"
        ]
    )

    maximum_effective_constituent_coupling = (
        2.0
        *
        q_ev
        /
        minimum_effective_scale_ev
    )

    return {
        "external_reference":
            "FABBRICHESI_GABRIELLI_LANFRANCHI_DARK_PHOTON_ARXIV_2005_01515",

        "external_bound_equation":
            "EQ_2_9",

        "external_bound":
            "Lambda^2/(sqrt(alpha_D)*d_M_e)>=4.5e6_TeV^2",

        "stellar_bound_tev2":
            STELLAR_ELECTRON_DIPLOE_BOUND_TEV2,

        "higgs_vev_ev":
            HIGGS_VEV_EV,

        "low_energy_project_operator":
            "(1/M_eff)*F_X_mn*bar(e)*sigma^mn*e",

        "minimum_effective_pauli_scale_ev":
            minimum_effective_scale_ev,

        "characteristic_device_q_ev":
            q_ev,

        "maximum_effective_constituent_coupling":
            maximum_effective_constituent_coupling,

        "stellar_bound_saturated_for_optimistic_source":
            True,

        "astrophysical_bound_has_order_of_magnitude_systematics":
            True,
    }


def _reference_source_quantities() -> dict[str, float]:
    """Return A12C canonical source and field requirement at reference scale."""

    a12c = a12c_artifact()

    production = (
        a12c[
            "massless_f2_finite_payload_bvp"
        ][
            "production"
        ]
    )

    return {
        "reference_portal_scale_ev":
            float(
                production[
                    "reference_portal_scale_ev"
                ]
            ),

        "reference_field_energy_j":
            float(
                production[
                    "field_energy_j"
                ]
            ),

        "reference_integrated_source_ev_m":
            float(
                production[
                    "integrated_canonical_source_ev_m"
                ]
            ),
    }


@lru_cache(maxsize=1)
def pauli_source_reference_floor() -> dict[str, Any]:
    """Compute optimistic electron-spin rest floor at A12C 1-keV reference."""

    reference = (
        _reference_source_quantities()
    )

    stellar = (
        stellar_electron_pauli_bound_gate()
    )

    g_eff = float(
        stellar[
            "maximum_effective_constituent_coupling"
        ]
    )

    integrated_source = float(
        reference[
            "reference_integrated_source_ev_m"
        ]
    )

    electron_count = (
        integrated_source
        /
        (
            g_eff
            *
            HBAR_C_EV_M
        )
    )

    electron_rest_energy_j = (
        electron_count
        *
        ELECTRON_MASS_EV
        *
        EV_J
    )

    return {
        "reference_portal_scale_ev":
            reference[
                "reference_portal_scale_ev"
            ],

        "reference_field_energy_j":
            reference[
                "reference_field_energy_j"
            ],

        "reference_integrated_canonical_source_ev_m":
            integrated_source,

        "maximum_effective_pauli_coupling":
            g_eff,

        "optimistic_fully_polarized_electron_count":
            electron_count,

        "optimistic_electron_rest_floor_j":
            electron_rest_energy_j,

        "fully_useful_spin_tensor_per_electron_assumed":
            True,

        "host_ion_rest_energy_included":
            False,

        "polarization_energy_included":
            False,

        "ordinary_magnetic_energy_included":
            False,

        "support_control_reset_included":
            False,

        "complete_energy_established":
            False,
    }


def source_energy_at_portal_scale(
    portal_scale_ev: float,
) -> dict[str, float]:
    """Scale A12C source and field costs to another F^2 metric scale."""

    if portal_scale_ev <= 0.0:
        raise ValueError(
            "portal_scale_ev must be positive"
        )

    reference = (
        pauli_source_reference_floor()
    )

    reference_scale = float(
        reference[
            "reference_portal_scale_ev"
        ]
    )

    ratio = (
        float(
            portal_scale_ev
        )
        /
        reference_scale
    )

    field_energy_j = (
        float(
            reference[
                "reference_field_energy_j"
            ]
        )
        *
        ratio**4
    )

    electron_rest_floor_j = (
        float(
            reference[
                "optimistic_electron_rest_floor_j"
            ]
        )
        *
        ratio**2
    )

    electron_count = (
        float(
            reference[
                "optimistic_fully_polarized_electron_count"
            ]
        )
        *
        ratio**2
    )

    return {
        "portal_scale_ev":
            float(
                portal_scale_ev
            ),

        "field_energy_j":
            field_energy_j,

        "optimistic_electron_rest_floor_j":
            electron_rest_floor_j,

        "partial_total_j":
            (
                field_energy_j
                +
                electron_rest_floor_j
            ),

        "optimistic_fully_polarized_electron_count":
            electron_count,
    }


@lru_cache(maxsize=1)
def strict_partial_energy_boundary() -> dict[str, Any]:
    """Solve exact positive strict-10MJ boundary in portal scale."""

    reference = (
        pauli_source_reference_floor()
    )

    reference_scale = float(
        reference[
            "reference_portal_scale_ev"
        ]
    )

    field_reference = float(
        reference[
            "reference_field_energy_j"
        ]
    )

    source_reference = float(
        reference[
            "optimistic_electron_rest_floor_j"
        ]
    )

    # Let y=(M_g/M_ref)^2.
    #
    # Then:
    #
    #   E(y)=E_field_ref*y^2 + E_source_ref*y.
    #
    # Use the cancellation-safe positive root.
    discriminant = math.sqrt(
        source_reference**2
        +
        4.0
        *
        field_reference
        *
        STRICT_COMPLETE_OPERATING_TARGET_J
    )

    y_boundary = (
        2.0
        *
        STRICT_COMPLETE_OPERATING_TARGET_J
        /
        (
            source_reference
            +
            discriminant
        )
    )

    portal_boundary_ev = (
        reference_scale
        *
        math.sqrt(
            y_boundary
        )
    )

    q_ev = float(
        pauli_geometry_gate()[
            "q_from_source_radius_ev"
        ]
    )

    at_q = (
        source_energy_at_portal_scale(
            q_ev
        )
    )

    at_two_q = (
        source_energy_at_portal_scale(
            TWO_X_SCALE_MARGIN
            *
            q_ev
        )
    )

    at_ten_q = (
        source_energy_at_portal_scale(
            TEN_X_SCALE_MARGIN
            *
            q_ev
        )
    )

    at_boundary = (
        source_energy_at_portal_scale(
            portal_boundary_ev
        )
    )

    maximum_scale_over_q = (
        portal_boundary_ev
        /
        q_ev
    )

    smallest_q_over_scale_in_allowed_corridor = (
        q_ev
        /
        portal_boundary_ev
    )

    return {
        "strict_target_j":
            STRICT_COMPLETE_OPERATING_TARGET_J,

        "exactly_10mj_passes":
            False,

        "strict_sub10mj_requires_portal_scale_ev_less_than":
            portal_boundary_ev,

        "portal_boundary_over_characteristic_q":
            maximum_scale_over_q,

        "minimum_q_over_portal_scale_inside_sub10mj_corridor":
            smallest_q_over_scale_in_allowed_corridor,

        "partial_overlap_exists_at_portal_scale_equal_q":
            at_q[
                "partial_total_j"
            ]
            <
            STRICT_COMPLETE_OPERATING_TARGET_J,

        "partial_at_q":
            at_q,

        "partial_at_2q":
            at_two_q,

        "partial_at_10q":
            at_ten_q,

        "partial_at_exact_boundary":
            at_boundary,

        "two_q_scale_margin_sub10mj":
            at_two_q[
                "partial_total_j"
            ]
            <
            STRICT_COMPLETE_OPERATING_TARGET_J,

        "ten_q_scale_margin_sub10mj":
            at_ten_q[
                "partial_total_j"
            ]
            <
            STRICT_COMPLETE_OPERATING_TARGET_J,

        "parametric_q_over_M_small":
            smallest_q_over_scale_in_allowed_corridor
            <
            0.1,

        "narrow_eft_edge_overlap_only":
            bool(
                maximum_scale_over_q
                >
                1.0

                and

                maximum_scale_over_q
                <
                2.0
            ),
    }


@lru_cache(maxsize=1)
def source_selectivity_and_empirical_scope_gate() -> dict[str, Any]:
    """Record what A12C empirical closeout does and does not transfer."""

    return {
        "source_operator":
            "F_X_mn*bar(e)*sigma^mn*e/M_eff",

        "source_is_renormalizable_vector_charge":
            False,

        "source_is_derivative_current":
            True,

        "source_is_identically_conserved":
            True,

        "source_is_spin_dependent":
            True,

        "a12c_em_like_photon_alignment_applies":
            False,

        "a12c_mri_photon_field_kill_directly_reused":
            False,

        "leading_direct_force_on_unpolarized_payload_expected_spin_averaged":
            True,

        "exact_payload_direct_force_silence_established":
            False,

        "massless_vector_stellar_electron_dipole_bound_applied":
            True,

        "radiative_kinetic_mixing_certified_zero":
            False,

        "spin_source_laboratory_empirical_consistency_established":
            False,

        "full_standard_model_uv_completion_established":
            False,
    }


@lru_cache(maxsize=1)
def h17a12d_summary() -> dict[str, Any]:
    """Return conservative A12D source-reopening decision."""

    provenance = (
        provenance_gate()
    )

    geometry = (
        pauli_geometry_gate()
    )

    stellar = (
        stellar_electron_pauli_bound_gate()
    )

    reference = (
        pauli_source_reference_floor()
    )

    energy = (
        strict_partial_energy_boundary()
    )

    scope = (
        source_selectivity_and_empirical_scope_gate()
    )

    reopened_partial = bool(
        provenance[
            "pass"
        ]

        and

        geometry[
            "source_shape_identity_pass"
        ]

        and

        geometry[
            "derivative_current_identically_conserved"
        ]

        and

        geometry[
            "q_identity_pass"
        ]

        and

        energy[
            "partial_overlap_exists_at_portal_scale_equal_q"
        ]
    )

    controlled_local_eft_promoted = bool(
        reopened_partial

        and

        not energy[
            "narrow_eft_edge_overlap_only"
        ]

        and

        energy[
            "two_q_scale_margin_sub10mj"
        ]
    )

    if (
        reopened_partial
        and
        not controlled_local_eft_promoted
    ):
        decision = (
            "YELLOW_SCOPED_A12D_ELECTRON_PAULI_MAGNETIZATION_SOURCE_"
            "REOPENS_A12B_F2_SUB10MJ_PARTIAL_ONLY_IN_A_NARROW_"
            "PORTAL_SCALE_EDGE_CORRIDOR__NO_PARAMETRIC_Q_OVER_M_"
            "SEPARATION__PROMOTE_UV_RADIATIVE_MIXING_AND_SPIN_"
            "EMPIRICAL_GATE"
        )
    elif controlled_local_eft_promoted:
        decision = (
            "GREEN_SCOPED_A12D_PAULI_SOURCE_HAS_SUB10MJ_AND_"
            "CONTROLLED_SCALE_HEADROOM__PROMOTE_UV_EMPIRICAL_GATE"
        )
    else:
        decision = (
            "RED_SCOPED_A12D_MINIMAL_ELECTRON_PAULI_SOURCE_"
            "HAS_NO_SUB10MJ_PARTIAL_OVERLAP"
        )

    return {
        "branch":
            "032H17A12D",

        "decision":
            decision,

        "provenance":
            provenance,

        "pauli_geometry":
            geometry,

        "stellar_electron_dipole_bound":
            stellar,

        "reference_source_floor":
            reference,

        "strict_partial_energy_boundary":
            energy,

        "source_selectivity_and_empirical_scope":
            scope,

        "minimal_electron_pauli_source_partial_corridor_reopened":
            reopened_partial,

        "controlled_local_f2_eft_completion_promoted":
            controlled_local_eft_promoted,

        "explicit_low_scale_uv_completion_closed":
            False,

        "a12b_exact_massless_carrier_closed":
            False,

        "a12c_gauge_invariant_f2_metric_mechanism_closed":
            False,

        "ordinary_em_like_route_remains_closed":
            True,

        "all_derivative_composite_currents_closed":
            False,

        "metric_bvp_rerun_authorized":
            False,

        "complete_energy_optimization_authorized":
            False,

        "hook17_closed":
            False,

        "physical_antigravity_model_found":
            False,

        "certified_sub10mj_model_found":
            False,

        "next":
            (
                "032H17A12E_PAULI_UV_RADIATIVE_KINETIC_MIXING_"
                "SPIN_SOURCE_EMPIRICAL_AND_SUPPORT_GATE"
                if reopened_partial
                else
                "032H17A13_NEW_PROTECTED_SOURCE_FAMILY"
            ),

        "stop_rule":
            (
                "DO_NOT_RERUN_THE_A12C_BVP_OR_OPTIMIZE_ITS_ALREADY_"
                "SUB100J_FIELD_TERM;_IF_A12D_REOPENS_ONLY_AN_EFT_EDGE_"
                "CORRIDOR_TEST_UV_COMPLETION_RADIATIVE_MIXING_SPIN_"
                "EMPIRICAL_CONSTRAINTS_AND_SOURCE_SUPPORT_BEFORE_ANY_"
                "FURTHER_PAYLOAD_OR_COMPLETE_ENERGY_WORK"
            ),
    }
