"""032H17A12D0 — low-capacity F^2 mechanism-preserving completion atlas.

PURPOSE
-------
A12C established a new project-level mechanism result:

    exact A12B massless protected U(1) carrier
        +
    gauge-invariant quadratic field-strength physical metric
        +
    finite compact source BVP
        +
    finite 1 kg neutral toroidal payload
        +
    true 1 m external geometric stand-off
        +
    >=1 g at every sampled payload point
        +
    2.656859142... J canonical field energy

at the declared 1-keV metric-portal reference normalization.

A12C simultaneously closed only one microscopic realization:

    stable ordinary e/p/n directly-silent renormalizable current
        ->
    EM-like current
        ->
    photon-aligned F^2 portal
        ->
    empirical MRI-field sanity failure.

The correct scientific response is NOT to discard the low-capacity mechanism
and NOT to optimize its already-sub-100-J field term.

This branch freezes the new low-capacity reference, exactly classifies the
local algebraic quadratic metric descendants of one Abelian field strength,
and constructs a theorem-first source/completion atlas for subsequent
physicalization.

It is intentionally a final-session state-consolidation run.

EXACT QUADRATIC METRIC BASIS
----------------------------
In four dimensions, for one antisymmetric Abelian field strength F_mn, local
symmetric rank-two tensors algebraic and quadratic in F are generated by

    g_mn F_ab F^ab

and

    F_m a F_n^a

in the parity-even sector.

The apparent parity-odd rank-two tensor obeys the exact identity

    F_m a *F_n^a
        =
    (1/4) g_mn F_ab *F^ab

under the conventions implemented here.

The dual-dual tensor is also reducible:

    *F_m a *F_n^a
        =
    F_m a F_n^a
        -
    (1/2) g_mn F_ab F^ab.

Therefore the complete declared local algebraic quadratic basis contains

    parity even:
        g F^2
        F F

    parity odd:
        g F *F

with no additional independent quadratic rank-two tensor.

PURE MAGNETOSTATIC CONSEQUENCE
------------------------------
For F_0i=0,

    [F_m a F_n^a]_00 = 0

and

    F_ab *F^ab = 0.

Hence, within this complete declared local algebraic quadratic basis, the
conformal g_mn F^2 structure is the UNIQUE term producing a leading static
g_00 response for an initially stationary payload in a purely magnetostatic
background.

This does NOT close:

- derivative metric descendants;
- curvature portals;
- multiple field strengths;
- additional compensator fields;
- nonlocal operators;
- higher powers F^4, F^6, ...;
- electric or mixed E/B backgrounds.

It does show that A12C already exhausted the useful purely magnetostatic
quadratic algebraic g00 basis up to normalization.

SOURCE-COMPLETION ATLAS
-----------------------
The low-capacity field mechanism is held fixed while source families are
ranked.

Permanent failure memory is applied before ranking:

- ordinary EM-like vector source:
    A12C scoped closed;

- direct ordinary-Dirac Wheeler -> K2:
    A11C scoped closed;

- unmodified engineered axial Dirac -> IW Maxwell:
    A12A scoped closed.

Open mechanism-preserving classes include:

- electron Pauli / magnetization derivative current;
- composite atomic/nuclear magnetization;
- full same-action source-selective Noether current;
- interacting / bound-state Dirac current engineering;
- known-particle flavor-selective currents;
- neutrino currents;
- pseudotensor derivative currents;
- curvature/composite source descendants.

Unobserved hidden/exotic matter is retained only as failure-memory and is not
authorized by current project policy.

IMPORTANT
---------
The source atlas is NOT a theorem that all microscopic matter currents have
been globally enumerated.

The metric-basis statement IS exhaustive only within its explicitly declared
scope:

    one Abelian F
    four dimensions
    local
    algebraic
    symmetric rank two
    quadratic in F
    no derivatives / curvature / extra fields.

PRIORITY SCORES
---------------
Atlas priority scores are deterministic research-management heuristics.

They are NOT:

- success probabilities;
- Bayesian probabilities;
- physical observables;
- model evidence.

Scores reward exact Ward conservation, source selectivity, exact source-shape
compatibility, and ability to reuse the converged A12C magnetostatic kernel.

CLAIM LIMITS
------------
This run does not establish:

- a physical microscopic source;
- complete operating energy;
- quantum/RG/UV consistency;
- empirical consistency of an open source family;
- loaded nonlinear backreaction;
- a practical antigravity device;
- new fundamental physics.

The 2.656859-J number remains a field-capacity reference at the declared
metric normalization, not complete device energy.
"""

from __future__ import annotations

import json
import math
from functools import lru_cache
from pathlib import Path
from typing import Any

import sympy as sp


A10F2_FALLBACK_FIELD_ENERGY_J = 562_964.8297553215

A11A_SUMMARY = (
    "032h17a11a_hook17_exact_current_protection_atlas_summary.json"
)

A11C_SUMMARY = (
    "032h17a11c_hook17_k2_onshell_dirac_bilinear_summary.json"
)

A12A_SUMMARY = (
    "032h17a12a_hook17_iw_engineered_axial_source_summary.json"
)

A12B_SUMMARY = (
    "032h17a12b_hook17_concurrent_iw_exact_source_summary.json"
)

A12C_SUMMARY = (
    "032h17a12c_hook17_concurrent_u1_fieldstrength_metric_summary.json"
)


def _repo_root() -> Path:
    """Return repository root from src/antigravity_research/agminer."""

    return (
        Path(__file__)
        .resolve()
        .parents[3]
    )


def _load_artifact(
    filename: str,
) -> dict[str, Any]:
    """Load one required generated scientific artifact."""

    path = (
        _repo_root()
        /
        "results"
        /
        "data"
        /
        filename
    )

    if not path.exists():
        raise FileNotFoundError(
            str(path)
        )

    return json.loads(
        path.read_text(
            encoding="utf-8"
        )
    )


@lru_cache(maxsize=1)
def required_artifacts() -> dict[str, dict[str, Any]]:
    """Return the complete A11A/A11C/A12A-C provenance chain."""

    return {
        "a11a":
            _load_artifact(
                A11A_SUMMARY
            ),

        "a11c":
            _load_artifact(
                A11C_SUMMARY
            ),

        "a12a":
            _load_artifact(
                A12A_SUMMARY
            ),

        "a12b":
            _load_artifact(
                A12B_SUMMARY
            ),

        "a12c":
            _load_artifact(
                A12C_SUMMARY
            ),
    }


@lru_cache(maxsize=1)
def provenance_gate() -> dict[str, Any]:
    """Require the exact scientific state that motivates A12D0."""

    artifacts = (
        required_artifacts()
    )

    a11a = artifacts[
        "a11a"
    ]

    a11c = artifacts[
        "a11c"
    ]

    a12a = artifacts[
        "a12a"
    ]

    a12b = artifacts[
        "a12b"
    ]

    a12c = artifacts[
        "a12c"
    ]

    passed = bool(
        a11a[
            "branch"
        ]
        ==
        "032H17A11A"

        and

        a11a[
            "all_derivative_composite_currents_closed"
        ]
        is False

        and

        a11a[
            "all_higgsed_noether_completions_closed"
        ]
        is False

        and

        a11c[
            "branch"
        ]
        ==
        "032H17A11C"

        and

        a11c[
            "direct_k2_ordinary_dirac_onshell_wheeler_route_closed"
        ]
        is True

        and

        a12a[
            "branch"
        ]
        ==
        "032H17A12A"

        and

        a12a[
            "maxwell_source_ward"
        ][
            "direct_engineered_dirac_iw_maxwell_branch_closed"
        ]
        is True

        and

        a12b[
            "branch"
        ]
        ==
        "032H17A12B"

        and

        a12b[
            "classical_protected_same_action_massless_source_corridor_exists"
        ]
        is True

        and

        a12b[
            "near_singular_gain_used"
        ]
        is False

        and

        a12c[
            "branch"
        ]
        ==
        "032H17A12C"

        and

        a12c[
            "gauge_invariant_massless_f2_reduced_eft_1g_1m_witness"
        ]
        is True

        and

        a12c[
            "ordinary_em_like_minimal_f2_a12b_realization_closed"
        ]
        is True

        and

        a12c[
            "a12b_exact_massless_carrier_closed"
        ]
        is False

        and

        a12c[
            "hook17_closed"
        ]
        is False
    )

    return {
        "pass":
            passed,

        "a11a_derivative_composite_space_open":
            not a11a[
                "all_derivative_composite_currents_closed"
            ],

        "a11a_full_noether_space_open":
            not a11a[
                "all_higgsed_noether_completions_closed"
            ],

        "a11c_direct_k2_ordinary_dirac_closed":
            a11c[
                "direct_k2_ordinary_dirac_onshell_wheeler_route_closed"
            ],

        "a12a_unmodified_axial_iw_maxwell_closed":
            a12a[
                "maxwell_source_ward"
            ][
                "direct_engineered_dirac_iw_maxwell_branch_closed"
            ],

        "a12b_protected_massless_carrier_open":
            not a12c[
                "a12b_exact_massless_carrier_closed"
            ],

        "a12c_ordinary_em_like_route_closed":
            a12c[
                "ordinary_em_like_minimal_f2_a12b_realization_closed"
            ],

        "hook17_open":
            not a12c[
                "hook17_closed"
            ],
    }


@lru_cache(maxsize=1)
def frozen_low_capacity_reference() -> dict[str, Any]:
    """Freeze A12C as a mechanism reference, not as complete energy."""

    artifacts = (
        required_artifacts()
    )

    a11a = artifacts[
        "a11a"
    ]

    a12c = artifacts[
        "a12c"
    ]

    bvp = a12c[
        "massless_f2_finite_payload_bvp"
    ]

    production = bvp[
        "production"
    ]

    a10f2_field_energy = float(
        a11a[
            "optimistic_energy_coupling_floor"
        ].get(
            "strict_field_energy_j",
            A10F2_FALLBACK_FIELD_ENERGY_J,
        )
    )

    field_energy = float(
        production[
            "field_energy_j"
        ]
    )

    improvement = (
        a10f2_field_energy
        /
        field_energy
    )

    reference_green = bool(
        provenance_gate()[
            "pass"
        ]

        and

        bvp[
            "preflight_convergence_pass"
        ]

        and

        production[
            "strict_whole_payload_1g_pass"
        ]

        and

        production[
            "invariant_tidal_response_nonzero"
        ]

        and

        math.isclose(
            float(
                production[
                    "geometric_external_standoff_m"
                ]
            ),
            1.0,
            rel_tol=0.0,
            abs_tol=1.0e-12,
        )

        and

        field_energy
        <
        100.0
    )

    return {
        "reference_id":
            "A12C_MASSLESS_F2_1G_1M",

        "reference_kernel_frozen":
            reference_green,

        "reference_portal_scale_ev":
            float(
                production[
                    "reference_portal_scale_ev"
                ]
            ),

        "field_energy_j":
            field_energy,

        "source_work_j":
            float(
                production[
                    "source_work_j"
                ]
            ),

        "source_work_relative_error":
            float(
                production[
                    "source_work_relative_error"
                ]
            ),

        "integrated_canonical_source_ev_m":
            float(
                production[
                    "integrated_canonical_source_ev_m"
                ]
            ),

        "payload_mass_kg":
            float(
                production[
                    "payload_mass_kg"
                ]
            ),

        "geometric_external_standoff_m":
            float(
                production[
                    "geometric_external_standoff_m"
                ]
            ),

        "payload_local_acceleration_min_m_s2":
            float(
                production[
                    "payload_local_acceleration_min_m_s2"
                ]
            ),

        "payload_local_acceleration_max_m_s2":
            float(
                production[
                    "payload_local_acceleration_max_m_s2"
                ]
            ),

        "payload_com_acceleration_m_s2":
            float(
                production[
                    "payload_com_acceleration_m_s2"
                ]
            ),

        "strict_whole_payload_1g_pass":
            production[
                "strict_whole_payload_1g_pass"
            ],

        "invariant_tidal_response_nonzero":
            production[
                "invariant_tidal_response_nonzero"
            ],

        "bvp_preflight_convergence_pass":
            bvp[
                "preflight_convergence_pass"
            ],

        "grid_energy_relative_difference":
            float(
                bvp[
                    "grid_energy_relative_difference"
                ]
            ),

        "domain_energy_relative_difference":
            float(
                bvp[
                    "domain_energy_relative_difference"
                ]
            ),

        "a10f2_field_energy_reference_j":
            a10f2_field_energy,

        "field_energy_improvement_factor_vs_a10f2":
            improvement,

        "field_term_below_100j":
            field_energy
            <
            100.0,

        "field_efficiency_optimization_authorized":
            False,

        "complete_energy_established":
            False,

        "certified_sub10mj_model":
            False,

        "physical_antigravity_model":
            False,

        "claim":
            (
                "LOWEST_CURRENT_PROJECT_NORMALIZED_FINITE_PAYLOAD_"
                "FIELD_CAPACITY_REFERENCE_AT_DECLARED_PORTAL_NORMALIZATION"
            ),
    }


def _epsilon4(
    indices: tuple[
        int,
        int,
        int,
        int,
    ],
) -> int:
    """Return epsilon^{0123}=+1 convention."""

    if len(
        set(
            indices
        )
    ) != 4:
        return 0

    inversions = sum(
        indices[
            i
        ]
        >
        indices[
            j
        ]
        for i in range(
            4
        )
        for j in range(
            i + 1,
            4,
        )
    )

    return (
        -1
        if inversions % 2
        else 1
    )


@lru_cache(maxsize=1)
def quadratic_fieldstrength_metric_basis_theorem() -> dict[str, Any]:
    """Prove the declared local quadratic one-F metric basis exactly."""

    eta = sp.diag(
        -1,
        1,
        1,
        1,
    )

    (
        f01,
        f02,
        f03,
        f12,
        f13,
        f23,
    ) = sp.symbols(
        "f01 f02 f03 f12 f13 f23",
        real=True,
    )

    field = sp.zeros(
        4,
        4,
    )

    components = {
        (0, 1): f01,
        (0, 2): f02,
        (0, 3): f03,
        (1, 2): f12,
        (1, 3): f13,
        (2, 3): f23,
    }

    for (
        (
            mu,
            nu,
        ),
        value,
    ) in components.items():
        field[
            mu,
            nu,
        ] = value

        field[
            nu,
            mu,
        ] = -value

    field_up = (
        eta
        *
        field
        *
        eta
    )

    dual_up = sp.zeros(
        4,
        4,
    )

    for mu in range(
        4
    ):
        for nu in range(
            4
        ):
            dual_up[
                mu,
                nu,
            ] = (
                sp.Rational(
                    1,
                    2,
                )
                *
                sum(
                    _epsilon4(
                        (
                            mu,
                            nu,
                            rho,
                            sigma,
                        )
                    )
                    *
                    field[
                        rho,
                        sigma,
                    ]
                    for rho in range(
                        4
                    )
                    for sigma in range(
                        4
                    )
                )
            )

    dual_low = (
        eta
        *
        dual_up
        *
        eta
    )

    field_mixed = (
        field
        *
        eta
    )

    dual_mixed = (
        dual_low
        *
        eta
    )

    ff_rank2 = sp.simplify(
        field
        *
        field_mixed.T
    )

    dualdual_rank2 = sp.simplify(
        dual_low
        *
        dual_mixed.T
    )

    odd_rank2 = sp.simplify(
        field
        *
        dual_mixed.T
    )

    scalar_f2 = sp.factor(
        sum(
            field[
                mu,
                nu,
            ]
            *
            field_up[
                mu,
                nu,
            ]
            for mu in range(
                4
            )
            for nu in range(
                4
            )
        )
    )

    scalar_fdual = sp.factor(
        sum(
            field[
                mu,
                nu,
            ]
            *
            dual_up[
                mu,
                nu,
            ]
            for mu in range(
                4
            )
            for nu in range(
                4
            )
        )
    )

    odd_identity = all(
        sp.simplify(
            odd_rank2[
                mu,
                nu,
            ]
            -
            eta[
                mu,
                nu,
            ]
            *
            scalar_fdual
            /
            4
        )
        ==
        0
        for mu in range(
            4
        )
        for nu in range(
            4
        )
    )

    dualdual_identity = all(
        sp.simplify(
            dualdual_rank2[
                mu,
                nu,
            ]
            -
            ff_rank2[
                mu,
                nu,
            ]
            +
            eta[
                mu,
                nu,
            ]
            *
            scalar_f2
            /
            2
        )
        ==
        0
        for mu in range(
            4
        )
        for nu in range(
            4
        )
    )

    pure_magnetic = {
        f01: 0,
        f02: 0,
        f03: 0,
    }

    pure_electric = {
        f12: 0,
        f13: 0,
        f23: 0,
    }

    magnetostatic_disformal_g00 = sp.simplify(
        ff_rank2[
            0,
            0,
        ].subs(
            pure_magnetic
        )
    )

    magnetostatic_pseudoscalar = sp.simplify(
        scalar_fdual.subs(
            pure_magnetic
        )
    )

    electrostatic_pseudoscalar = sp.simplify(
        scalar_fdual.subs(
            pure_electric
        )
    )

    magnetostatic_unique = bool(
        odd_identity
        and
        dualdual_identity
        and
        magnetostatic_disformal_g00
        ==
        0
        and
        magnetostatic_pseudoscalar
        ==
        0
    )

    return {
        "declared_scope":
            (
                "4D_ONE_ABELIAN_FIELD_STRENGTH_LOCAL_ALGEBRAIC_"
                "SYMMETRIC_RANK2_QUADRATIC_IN_F_NO_DERIVATIVES_"
                "NO_CURVATURE_NO_EXTRA_FIELDS"
            ),

        "basis_exhaustive_within_declared_scope":
            bool(
                odd_identity
                and
                dualdual_identity
            ),

        "parity_even_independent_dimension":
            2,

        "parity_even_basis":
            [
                "g_mn*F_ab*F^ab",
                "F_m_a*F_n^a",
            ],

        "parity_odd_independent_dimension":
            1,

        "parity_odd_basis":
            [
                "g_mn*F_ab*dualF^ab",
            ],

        "odd_rank2_identity":
            (
                "F_m_a*dualF_n^a="
                "(1/4)*g_mn*F_ab*dualF^ab"
            ),

        "odd_rank2_identity_pass":
            odd_identity,

        "dualdual_identity":
            (
                "dualF_m_a*dualF_n^a="
                "F_m_a*F_n^a-(1/2)*g_mn*F_ab*F^ab"
            ),

        "dualdual_identity_pass":
            dualdual_identity,

        "magnetostatic_disformal_g00":
            str(
                magnetostatic_disformal_g00
            ),

        "magnetostatic_pseudoscalar":
            str(
                magnetostatic_pseudoscalar
            ),

        "electrostatic_pseudoscalar":
            str(
                electrostatic_pseudoscalar
            ),

        "pure_magnetostatic_useful_static_g00_basis_dimension":
            1,

        "pure_magnetostatic_unique_quadratic_algebraic_g00_portal":
            "g_mn*F_ab*F^ab",

        "pure_magnetostatic_unique_g00_result_pass":
            magnetostatic_unique,

        "derivative_metric_descendants_closed":
            False,

        "curvature_portals_closed":
            False,

        "higher_power_F_portals_closed":
            False,

        "multiple_field_strength_portals_closed":
            False,

        "electric_or_mixed_backgrounds_closed":
            False,
    }


@lru_cache(maxsize=1)
def field_sector_portal_atlas() -> list[
    dict[str, Any]
]:
    """Enumerate the low-order field-sector / quadratic-metric combinations."""

    return [
        {
            "portal_id":
                "MAGNETOSTATIC_CONFORMAL_F2",

            "field_sector":
                "MAGNETOSTATIC",

            "metric_structure":
                "g_mn*F2",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                True,

            "status":
                "ESTABLISHED_A12C_REFERENCE",
        },
        {
            "portal_id":
                "MAGNETOSTATIC_DISFORMAL_FF",

            "field_sector":
                "MAGNETOSTATIC",

            "metric_structure":
                "F_m_a*F_n^a",

            "static_g00_active":
                False,

            "structurally_closed":
                True,

            "reference_kernel_reuse":
                False,

            "status":
                "CLOSED_ZERO_G00_FOR_PURE_B_STATIC_REST_PAYLOAD",
        },
        {
            "portal_id":
                "MAGNETOSTATIC_PARITY_ODD",

            "field_sector":
                "MAGNETOSTATIC",

            "metric_structure":
                "g_mn*F_dualF",

            "static_g00_active":
                False,

            "structurally_closed":
                True,

            "reference_kernel_reuse":
                False,

            "status":
                "CLOSED_F_DUALF_ZERO_FOR_PURE_B",
        },
        {
            "portal_id":
                "ELECTROSTATIC_CONFORMAL_F2",

            "field_sector":
                "ELECTROSTATIC",

            "metric_structure":
                "g_mn*F2",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                False,

            "status":
                "OPEN_NEW_BVP_REQUIRED",
        },
        {
            "portal_id":
                "ELECTROSTATIC_DISFORMAL_FF",

            "field_sector":
                "ELECTROSTATIC",

            "metric_structure":
                "F_m_a*F_n^a",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                False,

            "status":
                "OPEN_NEW_BVP_REQUIRED",
        },
        {
            "portal_id":
                "ELECTROSTATIC_PARITY_ODD",

            "field_sector":
                "ELECTROSTATIC",

            "metric_structure":
                "g_mn*F_dualF",

            "static_g00_active":
                False,

            "structurally_closed":
                True,

            "reference_kernel_reuse":
                False,

            "status":
                "CLOSED_F_DUALF_ZERO_FOR_PURE_E",
        },
        {
            "portal_id":
                "MIXED_EB_CONFORMAL_F2",

            "field_sector":
                "MIXED_EB",

            "metric_structure":
                "g_mn*F2",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                False,

            "status":
                "OPEN_NEW_BVP_REQUIRED",
        },
        {
            "portal_id":
                "MIXED_EB_DISFORMAL_FF",

            "field_sector":
                "MIXED_EB",

            "metric_structure":
                "F_m_a*F_n^a",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                False,

            "status":
                "OPEN_NEW_BVP_REQUIRED",
        },
        {
            "portal_id":
                "MIXED_EB_PARITY_ODD",

            "field_sector":
                "MIXED_EB",

            "metric_structure":
                "g_mn*F_dualF",

            "static_g00_active":
                True,

            "structurally_closed":
                False,

            "reference_kernel_reuse":
                False,

            "status":
                "OPEN_REQUIRES_NONZERO_E_DOT_B",
        },
    ]


@lru_cache(maxsize=1)
def source_completion_atlas() -> list[
    dict[str, Any]
]:
    """Return project-derived source families with permanent closures applied."""

    artifacts = (
        required_artifacts()
    )

    a11a = artifacts[
        "a11a"
    ]

    a11c = artifacts[
        "a11c"
    ]

    a12a = artifacts[
        "a12a"
    ]

    a12c = artifacts[
        "a12c"
    ]

    pauli = a11a[
        "pauli_derivative_exact_current"
    ]

    rows = [
        {
            "source_id":
                "ORDINARY_EM_LIKE_VECTOR",

            "operator_class":
                "RENORMALIZABLE_VECTOR_CURRENT",

            "current_status":
                "CLOSED_A12C_EMPIRICAL_PHOTON_ALIGNMENT",

            "exact_conservation":
                "YES",

            "source_selectivity":
                "NO_FOR_ORDINARY_CHARGED_MATTER",

            "same_action_status":
                "CLASSICAL_A12B_CORRIDOR_EXISTS",

            "source_shape_reference_compatibility":
                "ENGINEERABLE",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "CLOSED_IN_MINIMAL_F2_REALIZATION",

            "priority_base":
                0,

            "next_gate":
                "DO_NOT_REOPEN_MINIMAL_ROUTE",
        },
        {
            "source_id":
                "DIRECT_K2_WHEELER_ORDINARY_DIRAC",

            "operator_class":
                "WHEELER_TORSION_SOURCE",

            "current_status":
                (
                    "CLOSED_A11C_ALL_FINITE_NONZERO_"
                    "ONSHELL_TRANSFER_IN_DECLARED_CLASS"
                ),

            "exact_conservation":
                "FAILS_FULL_K2_SOURCE_SUBSPACE",

            "source_selectivity":
                "N_A",

            "same_action_status":
                "ROUTE_CLOSED",

            "source_shape_reference_compatibility":
                "N_A",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "NOT_REACHED",

            "priority_base":
                0,

            "next_gate":
                "DO_NOT_REOPEN_WITH_MORE_MOMENTUM_TUNING",

            "closure_provenance":
                bool(
                    a11c[
                        "direct_k2_ordinary_dirac_onshell_wheeler_route_closed"
                    ]
                ),
        },
        {
            "source_id":
                "UNMODIFIED_IW_AXIAL_DIRAC",

            "operator_class":
                "AXIAL_DIRAC_CURRENT",

            "current_status":
                "CLOSED_A12A_MAXWELL_WARD",

            "exact_conservation":
                "NO_FOR_MASSIVE_DIRAC",

            "source_selectivity":
                "SPIN_DEPENDENT",

            "same_action_status":
                "UNMODIFIED_ROUTE_CLOSED",

            "source_shape_reference_compatibility":
                "REOPENED_SOURCE_BUT_WARD_FAILED",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "NOT_REACHED",

            "priority_base":
                0,

            "next_gate":
                "DO_NOT_REOPEN_UNMODIFIED_AXIAL_MAXWELL",

            "closure_provenance":
                bool(
                    a12a[
                        "maxwell_source_ward"
                    ][
                        "direct_engineered_dirac_iw_maxwell_branch_closed"
                    ]
                ),
        },
        {
            "source_id":
                "ELECTRON_PAULI_MAGNETIZATION",

            "operator_class":
                "IDENTICALLY_CONSERVED_DERIVATIVE_TENSOR_CURRENT",

            "current_status":
                "OPEN_REEVALUATE_AGAINST_A12C_LOW_CAPACITY_KERNEL",

            "exact_conservation":
                "YES_IDENTICAL",

            "source_selectivity":
                "SPIN_DERIVATIVE_NOT_RENORMALIZABLE_CHARGE",

            "same_action_status":
                "LOCAL_OPERATOR_KNOWN_UV_COMPLETION_OPEN",

            "source_shape_reference_compatibility":
                "EXACT",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                (
                    "MASSLESS_DIPOLE_STELLAR_SPIN_AND_"
                    "RADIATIVE_MIXING_GATE_REQUIRED"
                ),

            "priority_base":
                100,

            "next_gate":
                "032H17A12D1_PAULI_SOURCE_ENERGY_UV_EMPIRICAL_GATE",

            "a11a_exact_shape_pass":
                bool(
                    pauli[
                        "source_shape"
                    ][
                        "source_shape_identity_pass"
                    ]
                ),

            "a11a_identically_conserved":
                bool(
                    pauli[
                        "source_shape"
                    ][
                        "derivative_current_identically_conserved"
                    ]
                ),

            "old_a11a_energy_closeout_transfers_automatically":
                False,
        },
        {
            "source_id":
                "COMPOSITE_ATOMIC_NUCLEAR_MAGNETIZATION",

            "operator_class":
                "COMPOSITE_MAGNETIZATION_CURL_CURRENT",

            "current_status":
                "OPEN",

            "exact_conservation":
                "YES_AT_EFFECTIVE_MAGNETIZATION_CURRENT_LEVEL",

            "source_selectivity":
                "SPIN_OR_COMPOSITE_DEPENDENT",

            "same_action_status":
                "MICROSCOPIC_MATCH_OPEN",

            "source_shape_reference_compatibility":
                "PLAUSIBLE_NOT_CERTIFIED",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "MAGNETIC_MOMENT_SPIN_FORCE_GATE_REQUIRED",

            "priority_base":
                85,

            "next_gate":
                "CANONICAL_CURRENT_PER_JOULE_BOUND",
        },
        {
            "source_id":
                "FULL_NOETHER_SOURCE_SELECTIVE_VECTOR",

            "operator_class":
                "FULL_NOETHER_COMPLETION",

            "current_status":
                "OPEN",

            "exact_conservation":
                "REQUIRES_EXPLICIT_SAME_ACTION_NOETHER_IDENTITY",

            "source_selectivity":
                "TARGET_PROPERTY",

            "same_action_status":
                "REQUIRED_NOT_YET_CONSTRUCTED_FOR_SOURCE_SELECTIVITY",

            "source_shape_reference_compatibility":
                "CAN_TARGET_REFERENCE_PROFILE",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "OPEN",

            "priority_base":
                90,

            "next_gate":
                "EXPLICIT_ACTION_PLUS_ANOMALY_AND_PAYLOAD_SILENCE",
        },
        {
            "source_id":
                "INTERACTING_BOUND_STATE_DIRAC",

            "operator_class":
                "BOUND_STATE_OR_TEXTURED_DIRAC_CURRENT",

            "current_status":
                "OPEN_OUTSIDE_A11C_FREE_ONSHELL_SCOPE",

            "exact_conservation":
                "ACTION_DEPENDENT",

            "source_selectivity":
                "POTENTIALLY_SPIN_TEXTURE_SELECTIVE",

            "same_action_status":
                "OPEN",

            "source_shape_reference_compatibility":
                "OPEN",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "OPEN",

            "priority_base":
                70,

            "next_gate":
                "BOUND_STATE_WARD_AND_CHARGE_PER_JOULE",
        },
        {
            "source_id":
                "KNOWN_PARTICLE_FLAVOR_SELECTIVE_VECTOR",

            "operator_class":
                "FLAVOR_VECTOR_CURRENT",

            "current_status":
                "OPEN_REQUIRES_EXPLICIT_ANOMALY_SOURCE_LIFETIME_RECONSTRUCTION",

            "exact_conservation":
                "CANDIDATE_DEPENDENT",

            "source_selectivity":
                "POTENTIALLY_HIGH_FOR_ORDINARY_PAYLOAD",

            "same_action_status":
                "CANDIDATE_DEPENDENT",

            "source_shape_reference_compatibility":
                "CURRENT_PROFILE_ENGINEERABLE_IN_PRINCIPLE",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "FLAVOR_FORCE_KINETIC_MIXING_AND_LIFETIME_GATE_REQUIRED",

            "priority_base":
                60,

            "next_gate":
                "ANOMALY_LIFETIME_POWER_AND_MIXING_PREFLIGHT",
        },
        {
            "source_id":
                "NEUTRINO_VECTOR_CURRENT",

            "operator_class":
                "KNOWN_PARTICLE_NEUTRINO_CURRENT",

            "current_status":
                "OPEN_BUT_SOURCE_CONFINEMENT_EXPECTED_DIFFICULT",

            "exact_conservation":
                "MODEL_DEPENDENT",

            "source_selectivity":
                "HIGH_FOR_ORDINARY_PAYLOAD",

            "same_action_status":
                "OPEN",

            "source_shape_reference_compatibility":
                "DIFFICULT",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "NEUTRINO_FORCE_AND_SOURCE_POWER_GATE_REQUIRED",

            "priority_base":
                45,

            "next_gate":
                "CONFINEMENT_AND_SOURCE_POWER_LOWER_BOUND",
        },
        {
            "source_id":
                "PSEUDOTENSOR_DERIVATIVE_CURRENT",

            "operator_class":
                "IDENTICALLY_CONSERVED_DERIVATIVE_PSEUDOTENSOR",

            "current_status":
                "OPEN",

            "exact_conservation":
                "YES_IDENTICAL_AT_DERIVATIVE_CURRENT_LEVEL",

            "source_selectivity":
                "SPIN_PARITY_DEPENDENT",

            "same_action_status":
                "OPERATOR_COMPLETION_REQUIRED",

            "source_shape_reference_compatibility":
                "DIFFERENT_FIELD_SECTOR",

            "supported_sectors":
                [
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "EDM_CP_AND_STELLAR_GATE_REQUIRED",

            "priority_base":
                55,

            "next_gate":
                "OPERATOR_STRENGTH_AND_EMPIRICAL_PREFLIGHT",
        },
        {
            "source_id":
                "CURVATURE_OR_COMPOSITE_SOURCE_CURRENT",

            "operator_class":
                "GAUGE_INVARIANT_COMPOSITE_OR_CURVATURE_CURRENT",

            "current_status":
                "OPEN",

            "exact_conservation":
                "MUST_BE_DERIVED",

            "source_selectivity":
                "OPEN",

            "same_action_status":
                "OPEN",

            "source_shape_reference_compatibility":
                "OPEN",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                True,

            "empirical_status":
                "OPEN_DERIVATIVE_TAX_EXPECTED",

            "priority_base":
                50,

            "next_gate":
                "WARD_FIRST_THEN_CAPACITY",
        },
        {
            "source_id":
                "UNOBSERVED_HIDDEN_EXOTIC_MATTER",

            "operator_class":
                "NEW_HIDDEN_MATTER_CURRENT",

            "current_status":
                "NOT_AUTHORIZED_BY_CURRENT_PROJECT_POLICY",

            "exact_conservation":
                "MODEL_DEPENDENT",

            "source_selectivity":
                "POTENTIALLY_HIGH",

            "same_action_status":
                "WOULD_REQUIRE_NEW_UNOBSERVED_MATTER",

            "source_shape_reference_compatibility":
                "OPEN",

            "supported_sectors":
                [
                    "MAGNETOSTATIC",
                    "ELECTROSTATIC",
                    "MIXED_EB",
                ],

            "project_policy_authorized":
                False,

            "empirical_status":
                "NOT_EVALUATED",

            "priority_base":
                0,

            "next_gate":
                "DO_NOT_USE_UNDER_CURRENT_POLICY",
        },
    ]

    # Permanent closure consistency.
    assert a12c[
        "ordinary_em_like_minimal_f2_a12b_realization_closed"
    ] is True

    return rows


def _source_is_closed(
    row: dict[str, Any],
) -> bool:
    """Return whether a source row is permanently unavailable in this atlas."""

    return (
        row[
            "current_status"
        ].startswith(
            "CLOSED_"
        )
        or
        row[
            "current_status"
        ].startswith(
            "NOT_AUTHORIZED_"
        )
    )


def _shape_bonus(
    source: dict[str, Any],
) -> int:
    """Return deterministic priority bonus for A12C profile compatibility."""

    status = source[
        "source_shape_reference_compatibility"
    ]

    if status == "EXACT":
        return 15

    if status in {
        "PLAUSIBLE_NOT_CERTIFIED",
        "CAN_TARGET_REFERENCE_PROFILE",
        "CURRENT_PROFILE_ENGINEERABLE_IN_PRINCIPLE",
    }:
        return 5

    return 0


def _conservation_bonus(
    source: dict[str, Any],
) -> int:
    """Return deterministic bonus for exact source conservation."""

    status = source[
        "exact_conservation"
    ]

    if status.startswith(
        "YES"
    ):
        return 10

    return 0


@lru_cache(maxsize=1)
def completion_combination_atlas() -> list[
    dict[str, Any]
]:
    """Cross source families with allowed field-sector metric portals."""

    sources = (
        source_completion_atlas()
    )

    portals = (
        field_sector_portal_atlas()
    )

    rows = []

    for source in sources:
        supported = set(
            source[
                "supported_sectors"
            ]
        )

        for portal in portals:
            if (
                portal[
                    "field_sector"
                ]
                not in supported
            ):
                continue

            source_closed = (
                _source_is_closed(
                    source
                )
            )

            portal_closed = bool(
                portal[
                    "structurally_closed"
                ]
            )

            if source_closed:
                status = (
                    "SOURCE_CLOSED_OR_POLICY_EXCLUDED"
                )

            elif portal_closed:
                status = (
                    "METRIC_STRUCTURE_STRUCTURALLY_CLOSED_IN_SECTOR"
                )

            else:
                status = (
                    "OPEN_PRE_BVP"
                )

            exact_kernel_reuse = bool(
                portal[
                    "reference_kernel_reuse"
                ]
                and
                source[
                    "source_shape_reference_compatibility"
                ]
                ==
                "EXACT"
            )

            conditional_kernel_reuse = bool(
                portal[
                    "reference_kernel_reuse"
                ]
                and
                source[
                    "source_shape_reference_compatibility"
                ]
                in {
                    "PLAUSIBLE_NOT_CERTIFIED",
                    "CAN_TARGET_REFERENCE_PROFILE",
                    "CURRENT_PROFILE_ENGINEERABLE_IN_PRINCIPLE",
                }
            )

            score = int(
                source[
                    "priority_base"
                ]
            )

            score += (
                25
                if exact_kernel_reuse
                else 0
            )

            score += (
                10
                if conditional_kernel_reuse
                else 0
            )

            score += (
                _shape_bonus(
                    source
                )
            )

            score += (
                _conservation_bonus(
                    source
                )
            )

            if (
                not portal[
                    "reference_kernel_reuse"
                ]
                and
                not portal_closed
            ):
                score -= 10

            if status != "OPEN_PRE_BVP":
                score = 0

            rows.append(
                {
                    "source_id":
                        source[
                            "source_id"
                        ],

                    "portal_id":
                        portal[
                            "portal_id"
                        ],

                    "field_sector":
                        portal[
                            "field_sector"
                        ],

                    "metric_structure":
                        portal[
                            "metric_structure"
                        ],

                    "status":
                        status,

                    "exact_a12c_kernel_reuse":
                        exact_kernel_reuse,

                    "conditional_a12c_kernel_reuse":
                        conditional_kernel_reuse,

                    "priority_score_not_probability":
                        score,

                    "source_next_gate":
                        source[
                            "next_gate"
                        ],

                    "complete_energy_certified":
                        False,
                }
            )

    rows.sort(
        key=lambda row: (
            -int(
                row[
                    "priority_score_not_probability"
                ]
            ),
            row[
                "source_id"
            ],
            row[
                "portal_id"
            ],
        )
    )

    return rows


@lru_cache(maxsize=1)
def open_completion_rerank() -> list[
    dict[str, Any]
]:
    """Return only structurally open, policy-authorized completion rows."""

    return [
        row
        for row in completion_combination_atlas()
        if row[
            "status"
        ]
        ==
        "OPEN_PRE_BVP"
    ]


@lru_cache(maxsize=1)
def h17a12d0_summary() -> dict[str, Any]:
    """Return final-session low-capacity mechanism consolidation."""

    provenance = (
        provenance_gate()
    )

    reference = (
        frozen_low_capacity_reference()
    )

    metric = (
        quadratic_fieldstrength_metric_basis_theorem()
    )

    portals = (
        field_sector_portal_atlas()
    )

    sources = (
        source_completion_atlas()
    )

    combinations = (
        completion_combination_atlas()
    )

    rerank = (
        open_completion_rerank()
    )

    open_sources = [
        row
        for row in sources
        if not _source_is_closed(
            row
        )
    ]

    structurally_open_portals = [
        row
        for row in portals
        if not row[
            "structurally_closed"
        ]
    ]

    top = rerank[
        0
    ]

    consolidated_green = bool(
        provenance[
            "pass"
        ]

        and

        reference[
            "reference_kernel_frozen"
        ]

        and

        metric[
            "basis_exhaustive_within_declared_scope"
        ]

        and

        metric[
            "pure_magnetostatic_unique_g00_result_pass"
        ]

        and

        top[
            "source_id"
        ]
        ==
        "ELECTRON_PAULI_MAGNETIZATION"

        and

        top[
            "portal_id"
        ]
        ==
        "MAGNETOSTATIC_CONFORMAL_F2"
    )

    decision = (
        (
            "GREEN_SCOPED_A12D0_LOW_CAPACITY_F2_MECHANISM_FROZEN__"
            "LOCAL_QUADRATIC_ONE_F_METRIC_BASIS_EXHAUSTED_IN_DECLARED_"
            "SCOPE__PURE_MAGNETOSTATIC_STATIC_G00_PORTAL_UNIQUE__"
            "SOURCE_COMPLETION_ATLAS_PROMOTES_PAULI_MAGNETIZATION_FIRST"
        )
        if consolidated_green
        else
        "YELLOW_A12D0_CONSOLIDATION_REQUIRES_REVIEW"
    )

    return {
        "branch":
            "032H17A12D0",

        "decision":
            decision,

        "provenance":
            provenance,

        "frozen_low_capacity_reference":
            reference,

        "quadratic_metric_basis":
            metric,

        "field_sector_portal_count":
            len(
                portals
            ),

        "structurally_open_portal_count":
            len(
                structurally_open_portals
            ),

        "source_family_count":
            len(
                sources
            ),

        "open_or_researchable_source_family_count":
            len(
                open_sources
            ),

        "completion_combination_count":
            len(
                combinations
            ),

        "open_completion_combination_count":
            len(
                rerank
            ),

        "top_completion":
            top,

        "top_10_open_completions":
            rerank[
                :10
            ],

        "low_capacity_mechanism_reference_preserved":
            consolidated_green,

        "a12b_exact_massless_carrier_preserved":
            True,

        "a12c_f2_metric_mechanism_preserved":
            True,

        "a12c_ordinary_em_like_route_remains_closed":
            True,

        "metric_basis_globally_exhausted":
            False,

        "source_space_globally_exhausted":
            False,

        "new_physics_discovery_claim":
            False,

        "project_level_mechanism_result":
            True,

        "complete_energy_established":
            False,

        "physical_antigravity_model_found":
            False,

        "certified_sub10mj_model_found":
            False,

        "practical_device_found":
            False,

        "field_efficiency_optimization_authorized":
            False,

        "new_bvp_authorized_immediately":
            False,

        "documentation_update_authorized":
            consolidated_green,

        "next":
            (
                "032H17A12D1_PAULI_MAGNETIZATION_SOURCE_ENERGY_"
                "UV_RADIATIVE_MIXING_AND_EMPIRICAL_GATE"
                if consolidated_green
                else
                "REVIEW_A12D0_CONSOLIDATION"
            ),

        "stop_rule":
            (
                "PRESERVE_THE_2P656859J_A12C_REFERENCE_AND_DO_NOT_"
                "OPTIMIZE_FIELD_CAPACITY;_EXHAUST_SOURCE_PHYSICALIZATION_"
                "AND_NON_MAGNETOSTATIC_LOW_ORDER_PORTALS_BY_CHEAP_WARD_"
                "SOURCE_ENERGY_UV_AND_EMPIRICAL_GATES_BEFORE_ANY_NEW_"
                "EXPENSIVE_BVP"
            ),
    }
