"""032H17A9R3 — covariant projector / same-action stress / Case-I protection.

PURPOSE
-------
Follow the A9R2 partial green.

A9R2 established that the fixed local projector

    P[X] = X - G(tr X)/5

does all of the following in flat space:

    is local;
    is idempotent;
    is self-adjoint;
    annihilates the torsion-free projective gauge image;
    makes all 16 Wheeler Hermitian source probes projectively compatible;
    leaves the clean A9 source exactly unchanged;
    preserves the exact healthy P&S 1+ pole numerator = 1.44.

A9R3 tests three harder issues.

1. COVARIANT GEOMETRIC LIFT

For a general nondegenerate metric g,

    tr_g[X]_c
        =
    g^{ab} X_cab

and the torsion-free projective gauge image is

    G_g(v)_cab
        =
    g_ab v_c
        +
    g_ac v_b.

In d dimensions,

    tr_g[G_g(v)]
        =
    (d+1) v.

Therefore

    P_g[X]
        =
    X
        -
    G_g(tr_g X)/(d+1)

is a natural local covariant projector.

A9R3 checks:

    trace annihilation;
    gauge-image annihilation;
    idempotence;
    first-third symmetry;
    self-adjointness;
    GL(4) basis equivariance

on a deterministic non-flat Lorentzian metric.

This certifies the GEOMETRIC projector.

It does not by itself certify the full world-spinor representation carried
by H_W.

2. SAME-ACTION LINEARIZED METRIC SOURCE

The A9R2 matter scaffold is

    S_int
        =
    integral sqrt(-g)
        H_W^{cab}
        P_g[N]_cab

with

    N = A - Gamma_LC[g].

At the flat/offstate background:

    N = 0.

For the clean A9 source:

    P[H_W] = H_W.

Consequently, at first order in the metric fluctuation h, variations of

    sqrt(-g),
    the metric dependence of P,
    and metric dependence of H_W

multiply background N and vanish in this interaction term.

The surviving linear metric variation is therefore the Levi-Civita piece

    - tau^{cab} delta Gamma_LC[cab].

A9R3 derives this metric source independently from the action and compares
it against the UNIQUE 40x40 local sigma solution found by A9R1.

The A9R1 result was

    S_032 = S_302 = 4

with every other coefficient zero to numerical precision.

If the action variation reproduces exactly that result, the earlier sigma
was not merely an algebraically possible repair: it is the metric source
generated by the same declared linearized distortion interaction.

This is an important same-action improvement.

3. PERCACCI-SEZGIN CASE-I PROTECTION

The projective symmetry of the torsion-free P&S action exists before the
Case-I health conditions.

After the additional spin-3 / extra-2+ restrictions, the relevant reduced
action contains independent coordinates including

    B,
    C,
    h7,
    h11.

The healthy massive 1+ Case-I branch requires

    C + 16 B / 25 = 0

and

    h11 + 10 h7 / 3 = 0.

These are two independent conditions.

They suppress unwanted propagation through cancellation of kinetic
momentum dependence:

    b(2-)
        =
    1/4 [
        2 B
        +
        (30 h7 + 9 h11) q^2
    ].

On Case I:

    30 h7 + 9 h11 = 0

but

    b(2-) = B/2 != 0.

Likewise the 1- determinant contains

    Delta
        =
    6 B C
        +
    (16 B + 25 C)
    (2 h7 + h11) q^2.

On Case I:

    16 B + 25 C = 0

while

    6 B C = -96 B^2 / 25 != 0

for the healthy B>0 branch.

Thus the unwanted blocks become nondynamical without becoming new gauge
null directions in these reduced sectors.

A9R3 does NOT claim that no unknown ultraviolet symmetry could ever protect
Case I.

It records the narrower fact:

    PROJECTIVE SYMMETRY ALONE DOES NOT ENFORCE THE CASE-I CONDITIONS,

and:

    NO ADDITIONAL NONACCIDENTAL SYMMETRY OR ACTUAL RG INVARIANCE OF
    THE CASE-I SURFACE HAS BEEN ESTABLISHED.

Under the project's technical-naturalness policy, this blocks promotion of
the current P&S Case-I realization.

CLAIM LIMIT
-----------
A positive geometric/Noether result does NOT establish:

- a globally defined GL(4) world-spinor representation;
- the complete nonlinear Wheeler matter action;
- the full nonlinear metric stress;
- radiative stability of Case I;
- the V26B1 quadratic physical metric from the same action;
- universal neutral-matter antigravity;
- finite-payload stand-off;
- complete operating energy;
- a device.

ENERGY POLICY
-------------
No energy optimization is performed.

17.0676442196 J remains only the HOOK17 canonical field-capacity reference.

Complete operating energy remains unknown.

CLAIM_CLASSIFICATION
--------------------
COVARIANT_GEOMETRIC_AND_LINEARIZED_SAME_ACTION_NOETHER_PARTIAL_GREEN
WITH_CURRENT_CASE_I_TECHNICAL_NATURALNESS_BLOCK
"""

from __future__ import annotations

from typing import Any

import numpy as np

from .hook17_percacci_sezgin_1plus_projector import (
    torsion_free_ps_source,
)

from .hook17_projective_dirac_completion import (
    exact_ps_1plus_numerator_for_source,
    h17a9r2_summary,
    projective_traceless_projection,
)

from .hook17_ps_wheeler_same_action_noether import (
    clean_local_sigma_completion_gate,
)


ETA = np.diag(
    [
        -1.0,
        1.0,
        1.0,
        1.0,
    ]
)

DIMENSION = 4

TOL = 1.0e-11

HOOK17_REFERENCE_CAPACITY_RP1E12_J = 17.0676442196
STRICT_COMPLETE_OPERATING_TARGET_J = 1.0e7


def a9r2_provenance_gate() -> dict[str, Any]:
    """Require the exact successful A9R2 state."""

    result = h17a9r2_summary()

    passed = bool(
        result[
            "partial_green"
        ]
        and
        result[
            "linearized_local_projective_matter_action_scaffold_exists"
        ]
        and
        result[
            "all_16_projected_wheeler_probes_projective_compatible"
        ]
        and
        result[
            "clean_a9_1plus_pole_numerator_preserved"
        ]
        and
        not result[
            "same_action_hook17_complete"
        ]
        and
        not result[
            "hook17_closed"
        ]
    )

    return {
        "a9r2_decision":
            result[
                "decision"
            ],

        "a9r2_provenance_pass":
            passed,

        "linearized_projective_scaffold":
            result[
                "linearized_local_projective_matter_action_scaffold_exists"
            ],

        "all_16_sources_projective":
            result[
                "all_16_projected_wheeler_probes_projective_compatible"
            ],

        "clean_pole_preserved":
            result[
                "clean_a9_1plus_pole_numerator_preserved"
            ],

        "clean_pole_numerator":
            result[
                "clean_a9_projected_1plus_pole_numerator"
            ],

        "hook17_open":
            not result[
                "hook17_closed"
            ],
    }


def _validate_metric(
    metric: np.ndarray,
) -> np.ndarray:
    """Return one finite symmetric nondegenerate 4x4 metric."""

    g = np.asarray(
        metric,
        dtype=float,
    )

    if g.shape != (
        4,
        4,
    ):
        raise ValueError(
            "metric must have shape (4,4)"
        )

    if not np.all(
        np.isfinite(
            g
        )
    ):
        raise ValueError(
            "metric must be finite"
        )

    if not np.allclose(
        g,
        g.T,
        atol=
            1.0e-12,
        rtol=
            0.0,
    ):
        raise ValueError(
            "metric must be symmetric"
        )

    if abs(
        np.linalg.det(
            g
        )
    ) <= 1.0e-12:
        raise ValueError(
            "metric must be nondegenerate"
        )

    return g


def _validate_rank3(
    tensor: np.ndarray,
) -> np.ndarray:
    """Return one finite rank-three tensor."""

    value = np.asarray(
        tensor,
        dtype=float,
    )

    if value.shape != (
        4,
        4,
        4,
    ):
        raise ValueError(
            "rank-three tensor must have shape (4,4,4)"
        )

    if not np.all(
        np.isfinite(
            value
        )
    ):
        raise ValueError(
            "rank-three tensor must be finite"
        )

    return value


def covariant_projective_trace(
    tensor: np.ndarray,
    metric: np.ndarray,
) -> np.ndarray:
    """Return tr_g[X]_c = g^{ab} X_cab."""

    value = _validate_rank3(
        tensor
    )

    g = _validate_metric(
        metric
    )

    inverse = np.linalg.inv(
        g
    )

    return np.einsum(
        "ab,cab->c",
        inverse,
        value,
    )


def covariant_projective_gauge_image(
    vector: np.ndarray,
    metric: np.ndarray,
) -> np.ndarray:
    """Return G_g(v)_cab = g_ab v_c + g_ac v_b."""

    v = np.asarray(
        vector,
        dtype=float,
    )

    if v.shape != (
        4,
    ):
        raise ValueError(
            "vector must have shape (4,)"
        )

    g = _validate_metric(
        metric
    )

    return (
        np.einsum(
            "ab,c->cab",
            g,
            v,
        )
        +
        np.einsum(
            "ac,b->cab",
            g,
            v,
        )
    )


def covariant_projective_projection(
    tensor: np.ndarray,
    metric: np.ndarray,
) -> np.ndarray:
    """Return the nonlinear geometric projector P_g."""

    value = _validate_rank3(
        tensor
    )

    g = _validate_metric(
        metric
    )

    trace = covariant_projective_trace(
        value,
        g,
    )

    return (
        value
        -
        covariant_projective_gauge_image(
            trace,
            g,
        )
        /
        float(
            DIMENSION
            +
            1
        )
    )


def _raise_rank3(
    tensor: np.ndarray,
    metric: np.ndarray,
) -> np.ndarray:
    """Raise all indices using one general metric."""

    value = _validate_rank3(
        tensor
    )

    g = _validate_metric(
        metric
    )

    inverse = np.linalg.inv(
        g
    )

    return np.einsum(
        "ci,aj,bk,ijk->cab",
        inverse,
        inverse,
        inverse,
        value,
    )


def _rank3_inner(
    left: np.ndarray,
    right: np.ndarray,
    metric: np.ndarray,
) -> float:
    """Return the metric-induced rank-three inner product."""

    return float(
        np.einsum(
            "cab,cab->",
            _validate_rank3(
                left
            ),
            _raise_rank3(
                right,
                metric,
            ),
        )
    )


def _nonflat_lorentzian_metric() -> np.ndarray:
    """Return a deterministic non-diagonal Lorentzian metric."""

    transform = np.array(
        [
            [
                1.10,
                0.10,
                0.00,
                0.00,
            ],
            [
                0.00,
                1.00,
                0.20,
                0.00,
            ],
            [
                0.05,
                0.00,
                0.90,
                0.10,
            ],
            [
                0.00,
                0.10,
                0.00,
                1.20,
            ],
        ],
        dtype=float,
    )

    return (
        transform
        @
        ETA
        @
        transform.T
    )


def covariant_projector_geometry_gate() -> dict[str, Any]:
    """Test P_g away from the flat diagonal metric."""

    metric = _nonflat_lorentzian_metric()

    eigenvalues = np.linalg.eigvalsh(
        metric
    )

    signature = (
        int(
            np.sum(
                eigenvalues
                <
                0.0
            )
        ),
        int(
            np.sum(
                eigenvalues
                >
                0.0
            )
        ),
    )

    raw_x = (
        np.arange(
            64,
            dtype=float,
        ).reshape(
            (
                4,
                4,
                4,
            )
        )
        /
        17.0
    )

    raw_y = np.cos(
        np.arange(
            64,
            dtype=float,
        )
    ).reshape(
        (
            4,
            4,
            4,
        )
    )

    x = (
        0.5
        *
        (
            raw_x
            +
            np.swapaxes(
                raw_x,
                0,
                2,
            )
        )
    )

    y = (
        0.5
        *
        (
            raw_y
            +
            np.swapaxes(
                raw_y,
                0,
                2,
            )
        )
    )

    px = covariant_projective_projection(
        x,
        metric,
    )

    ppx = covariant_projective_projection(
        px,
        metric,
    )

    py = covariant_projective_projection(
        y,
        metric,
    )

    vector = np.array(
        [
            0.70,
            -0.20,
            0.40,
            0.90,
        ]
    )

    gauge = covariant_projective_gauge_image(
        vector,
        metric,
    )

    projected_gauge = covariant_projective_projection(
        gauge,
        metric,
    )

    gauge_trace = covariant_projective_trace(
        gauge,
        metric,
    )

    expected_gauge_trace = (
        float(
            DIMENSION
            +
            1
        )
        *
        vector
    )

    trace_error = float(
        np.linalg.norm(
            covariant_projective_trace(
                px,
                metric,
            )
        )
    )

    idempotence_error = float(
        np.linalg.norm(
            ppx
            -
            px
        )
    )

    gauge_error = float(
        np.linalg.norm(
            projected_gauge
        )
    )

    gauge_trace_error = float(
        np.linalg.norm(
            gauge_trace
            -
            expected_gauge_trace
        )
    )

    symmetry_error = float(
        np.max(
            np.abs(
                px
                -
                np.swapaxes(
                    px,
                    0,
                    2,
                )
            )
        )
    )

    self_adjoint_error = abs(
        _rank3_inner(
            x,
            py,
            metric,
        )
        -
        _rank3_inner(
            px,
            y,
            metric,
        )
    )

    return {
        "metric_signature_negative_positive":
            list(
                signature
            ),

        "lorentzian_metric":
            bool(
                signature
                ==
                (
                    1,
                    3,
                )
            ),

        "projector_is_local_algebraic":
            True,

        "projector_covariant_formula":
            (
                "P_g[X]=X-G_g(tr_g[X])/(d+1)"
            ),

        "gauge_trace_reconstruction_error":
            gauge_trace_error,

        "projector_output_trace_norm":
            trace_error,

        "projector_idempotence_error":
            idempotence_error,

        "projector_gauge_annihilation_error":
            gauge_error,

        "projector_tf_symmetry_error":
            symmetry_error,

        "projector_self_adjoint_error":
            self_adjoint_error,

        "covariant_trace_zero":
            bool(
                trace_error
                <=
                TOL
            ),

        "covariant_idempotent":
            bool(
                idempotence_error
                <=
                TOL
            ),

        "covariant_gauge_image_annihilated":
            bool(
                gauge_error
                <=
                TOL
            ),

        "covariant_tf_symmetry_preserved":
            bool(
                symmetry_error
                <=
                TOL
            ),

        "covariant_self_adjoint":
            bool(
                self_adjoint_error
                <=
                TOL
            ),
    }


def _transform_covariant_rank3(
    matrix: np.ndarray,
    tensor: np.ndarray,
) -> np.ndarray:
    """Apply the same covariant basis map to all three indices."""

    return np.einsum(
        "ci,aj,bk,ijk->cab",
        matrix,
        matrix,
        matrix,
        tensor,
    )


def covariant_projector_gl_equivariance_gate() -> dict[str, Any]:
    """Test P_g under a deterministic invertible GL(4) basis change."""

    metric = _nonflat_lorentzian_metric()

    raw = np.sin(
        np.arange(
            64,
            dtype=float,
        )
        /
        5.0
    ).reshape(
        (
            4,
            4,
            4,
        )
    )

    tensor = (
        0.5
        *
        (
            raw
            +
            np.swapaxes(
                raw,
                0,
                2,
            )
        )
    )

    change = np.array(
        [
            [
                1.00,
                0.10,
                0.00,
                0.00,
            ],
            [
                0.00,
                1.00,
                0.05,
                0.00,
            ],
            [
                0.02,
                0.00,
                1.00,
                0.10,
            ],
            [
                0.00,
                0.03,
                0.00,
                1.00,
            ],
        ]
    )

    metric_prime = (
        change
        @
        metric
        @
        change.T
    )

    tensor_prime = _transform_covariant_rank3(
        change,
        tensor,
    )

    projected = covariant_projective_projection(
        tensor,
        metric,
    )

    transformed_projected = _transform_covariant_rank3(
        change,
        projected,
    )

    projected_after_transform = covariant_projective_projection(
        tensor_prime,
        metric_prime,
    )

    error = float(
        np.linalg.norm(
            transformed_projected
            -
            projected_after_transform
        )
    )

    return {
        "basis_change_determinant":
            float(
                np.linalg.det(
                    change
                )
            ),

        "basis_change_invertible":
            bool(
                abs(
                    np.linalg.det(
                        change
                    )
                )
                >
                1.0e-8
            ),

        "gl4_equivariance_error":
            error,

        "gl4_equivariance_pass":
            bool(
                error
                <=
                TOL
            ),
    }


def flat_covariant_projector_regression_gate() -> dict[str, Any]:
    """Verify the covariant projector reduces exactly to A9R2 in flat space."""

    raw = np.cos(
        np.arange(
            64,
            dtype=float,
        )
        /
        7.0
    ).reshape(
        (
            4,
            4,
            4,
        )
    )

    tensor = (
        0.5
        *
        (
            raw
            +
            np.swapaxes(
                raw,
                0,
                2,
            )
        )
    )

    old = projective_traceless_projection(
        tensor
    )

    new = covariant_projective_projection(
        tensor,
        ETA,
    )

    error = float(
        np.linalg.norm(
            old
            -
            new
        )
    )

    return {
        "flat_reduction_error":
            error,

        "flat_covariant_projector_matches_a9r2":
            bool(
                error
                <=
                TOL
            ),
    }


def clean_covariant_source_gate() -> dict[str, Any]:
    """Verify the clean source and exact A9 pole survive the covariant lift."""

    clean = np.asarray(
        torsion_free_ps_source(),
        dtype=float,
    )

    projected = covariant_projective_projection(
        clean,
        ETA,
    )

    difference = float(
        np.linalg.norm(
            projected
            -
            clean
        )
    )

    pole = exact_ps_1plus_numerator_for_source(
        projected
    )

    return {
        "clean_source_norm":
            float(
                np.linalg.norm(
                    clean
                )
            ),

        "covariant_projected_minus_clean_norm":
            difference,

        "clean_source_unchanged":
            bool(
                difference
                <=
                TOL
            ),

        "exact_1plus_pole_numerator":
            pole[
                "pole_numerator"
            ],

        "exact_1plus_pole_numerator_nonzero":
            pole[
                "pole_numerator_nonzero"
            ],

        "a9_numerator_preserved":
            bool(
                abs(
                    pole[
                        "pole_numerator"
                    ]
                    -
                    1.44
                )
                <=
                TOL
            ),
    }


def linearized_lc_metric_source_coefficients(
    tau_cov: np.ndarray,
) -> np.ndarray:
    """Derive P&S-normalized sigma coefficient S_abd from -tau.Gamma_LC.

    The source is supplied with all indices lowered.

    We first raise tau for its contraction with Gamma_cab.

    For each independent symmetric metric fluctuation h_mn and momentum
    component q_d we evaluate

        - tau^{cab} Gamma_cab(h).

    P&S source contraction sums both off-diagonal metric components, so the
    independent off-diagonal variation coefficient is divided by two when
    reconstructing symmetric sigma_ab.

    The returned tensor obeys

        sigma_ab(q)
            =
        i S_abd q^d.
    """

    tau = _validate_rank3(
        tau_cov
    )

    tau_up = np.einsum(
        "ci,aj,bk,ijk->cab",
        ETA,
        ETA,
        ETA,
        tau,
    )

    result = np.zeros(
        (
            4,
            4,
            4,
        ),
        dtype=float,
    )

    for m in range(
        4
    ):
        for n in range(
            m,
            4
        ):
            for d in range(
                4
            ):
                h = np.zeros(
                    (
                        4,
                        4,
                    ),
                    dtype=float,
                )

                h[
                    m,
                    n,
                ] = 1.0

                h[
                    n,
                    m,
                ] = 1.0

                q = np.zeros(
                    4,
                    dtype=float,
                )

                q[
                    d
                ] = 1.0

                gamma = np.zeros(
                    (
                        4,
                        4,
                        4,
                    ),
                    dtype=float,
                )

                for c in range(
                    4
                ):
                    for a in range(
                        4
                    ):
                        for b in range(
                            4
                        ):
                            gamma[
                                c,
                                a,
                                b,
                            ] = (
                                0.5
                                *
                                (
                                    q[
                                        c
                                    ]
                                    *
                                    h[
                                        a,
                                        b
                                    ]
                                    +
                                    q[
                                        b
                                    ]
                                    *
                                    h[
                                        a,
                                        c
                                    ]
                                    -
                                    q[
                                        a
                                    ]
                                    *
                                    h[
                                        c,
                                        b
                                    ]
                                )
                            )

                independent_coefficient = float(
                    -np.einsum(
                        "cab,cab->",
                        tau_up,
                        gamma,
                    )
                )

                normalization = (
                    2.0
                    if m
                    !=
                    n
                    else
                    1.0
                )

                coefficient = (
                    independent_coefficient
                    /
                    normalization
                )

                result[
                    m,
                    n,
                    d,
                ] = coefficient

                result[
                    n,
                    m,
                    d,
                ] = coefficient

    return result


def same_action_clean_metric_stress_gate() -> dict[str, Any]:
    """Compare the action-derived metric source to the unique A9R1 sigma."""

    clean = np.asarray(
        torsion_free_ps_source(),
        dtype=float,
    )

    derived = linearized_lc_metric_source_coefficients(
        clean
    )

    a9r1 = clean_local_sigma_completion_gate()

    target = np.asarray(
        a9r1[
            "solution_tensor"
        ],
        dtype=float,
    )

    difference = (
        derived
        -
        target
    )

    difference_norm = float(
        np.linalg.norm(
            difference
        )
    )

    maximum_difference = float(
        np.max(
            np.abs(
                difference
            )
        )
    )

    mask = np.ones(
        derived.shape,
        dtype=bool,
    )

    mask[
        0,
        3,
        2,
    ] = False

    mask[
        3,
        0,
        2,
    ] = False

    maximum_other = float(
        np.max(
            np.abs(
                derived[
                    mask
                ]
            )
        )
    )

    return {
        "declared_interaction":
            (
                "S_INT=INTEGRAL SQRT(-g) "
                "H_W^{cab} P_g[A-GAMMA_LC[g]]_cab"
            ),

        "background_distortion_zero":
            True,

        "clean_projective_source_unchanged":
            clean_covariant_source_gate()[
                "clean_source_unchanged"
            ],

        "linear_metric_variation_survives_from_minus_tau_delta_gamma_lc":
            True,

        "action_derived_s032":
            float(
                derived[
                    0,
                    3,
                    2,
                ]
            ),

        "action_derived_s302":
            float(
                derived[
                    3,
                    0,
                    2,
                ]
            ),

        "maximum_other_action_derived_coefficient":
            maximum_other,

        "a9r1_unique_s032":
            float(
                target[
                    0,
                    3,
                    2,
                ]
            ),

        "a9r1_unique_s302":
            float(
                target[
                    3,
                    0,
                    2,
                ]
            ),

        "action_vs_a9r1_sigma_difference_norm":
            difference_norm,

        "action_vs_a9r1_sigma_maximum_difference":
            maximum_difference,

        "same_action_linearized_clean_metric_stress_matches_a9r1":
            bool(
                maximum_difference
                <=
                1.0e-10
            ),

        "full_curved_world_spinor_metric_stress_derived":
            False,

        "full_nonlinear_metric_variation_derived":
            False,
    }


def clean_same_action_diffeomorphism_ward_gate() -> dict[str, Any]:
    """Verify the action-derived clean sigma on independent momenta."""

    tau = np.asarray(
        torsion_free_ps_source(),
        dtype=float,
    )

    s_tensor = linearized_lc_metric_source_coefficients(
        tau
    )

    mass = float(
        np.sqrt(
            0.18
        )
    )

    witnesses = {
        "MASSIVE_1PLUS_REST":
            np.array(
                [
                    mass,
                    0.0,
                    0.0,
                    0.0,
                ]
            ),

        "GENERIC_MIXED":
            np.array(
                [
                    1.0,
                    0.0,
                    1.0,
                    0.0,
                ]
            ),

        "FULL_DIRECTION":
            np.array(
                [
                    0.7,
                    -0.2,
                    0.4,
                    0.9,
                ]
            ),

        "SPATIAL_DIAGONAL":
            np.array(
                [
                    0.0,
                    1.0,
                    1.0,
                    1.0,
                ]
            ),
    }

    rows: list[dict[str, Any]] = []

    for name, q in witnesses.items():
        connection = np.einsum(
            "a,b,bca->c",
            q,
            q,
            tau,
        )

        sigma = (
            1j
            *
            np.einsum(
                "acd,d->ac",
                s_tensor,
                q,
            )
        )

        metric = (
            2j
            *
            np.einsum(
                "a,ac->c",
                q,
                sigma,
            )
        )

        residual = (
            connection
            +
            metric
        )

        residual_norm = float(
            np.linalg.norm(
                residual
            )
        )

        rows.append(
            {
                "name":
                    name,

                "q":
                    q.tolist(),

                "connection_term":
                    np.real_if_close(
                        connection
                    ).tolist(),

                "metric_term":
                    np.real_if_close(
                        metric
                    ).tolist(),

                "full_residual":
                    np.real_if_close(
                        residual
                    ).tolist(),

                "residual_norm":
                    residual_norm,

                "pass":
                    bool(
                        residual_norm
                        <=
                        1.0e-10
                    ),
            }
        )

    return {
        "witness_count":
            len(
                rows
            ),

        "all_clean_same_action_linearized_diffeo_witnesses_pass":
            all(
                row[
                    "pass"
                ]
                for row in rows
            ),

        "maximum_clean_same_action_diffeo_residual":
            max(
                row[
                    "residual_norm"
                ]
                for row in rows
            ),

        "full_nonlinear_matter_noether_identity_established":
            False,

        "rows":
            rows,
    }


def case_i_protection_audit() -> dict[str, Any]:
    """Audit whether known projective symmetry protects Case-I health relations."""

    b = 1.0
    c = (
        -16.0
        /
        25.0
    )

    h7 = -1.0

    h11 = (
        10.0
        /
        3.0
    )

    case_constraint_1 = (
        c
        +
        16.0
        *
        b
        /
        25.0
    )

    case_constraint_2 = (
        h11
        +
        10.0
        *
        h7
        /
        3.0
    )

    jacobian = np.array(
        [
            [
                16.0 / 25.0,
                1.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                10.0 / 3.0,
                1.0,
            ],
        ]
    )

    rank = int(
        np.linalg.matrix_rank(
            jacobian
        )
    )

    generic_beta_witness = np.array(
        [
            0.31,
            -0.27,
            0.19,
            0.41,
        ]
    )

    generic_normal_flow = (
        jacobian
        @
        generic_beta_witness
    )

    generic_normal_norm = float(
        np.linalg.norm(
            generic_normal_flow
        )
    )

    two_minus_kinetic = (
        30.0
        *
        h7
        +
        9.0
        *
        h11
    )

    two_minus_constant = (
        b
        /
        2.0
    )

    one_minus_q2_factor = (
        (
            16.0
            *
            b
            +
            25.0
            *
            c
        )
        *
        (
            2.0
            *
            h7
            +
            h11
        )
    )

    one_minus_constant = (
        6.0
        *
        b
        *
        c
    )

    case_relations_exact = bool(
        abs(
            case_constraint_1
        )
        <=
        TOL
        and
        abs(
            case_constraint_2
        )
        <=
        TOL
    )

    unwanted_blocks_remain_nondegenerate = bool(
        abs(
            two_minus_constant
        )
        >
        TOL
        and
        abs(
            one_minus_constant
        )
        >
        TOL
    )

    momentum_dependence_removed = bool(
        abs(
            two_minus_kinetic
        )
        <=
        TOL
        and
        abs(
            one_minus_q2_factor
        )
        <=
        TOL
    )

    return {
        "case_i_coordinates":
            [
                "B",
                "C",
                "h7",
                "h11",
            ],

        "case_i_constraint_c_plus_16b_over_25":
            case_constraint_1,

        "case_i_constraint_h11_plus_10h7_over_3":
            case_constraint_2,

        "case_i_relations_exact":
            case_relations_exact,

        "case_i_constraint_jacobian_rank":
            rank,

        "case_i_health_surface_codimension_in_declared_coordinates":
            rank,

        "projective_symmetry_exists_before_case_i_relations":
            True,

        "projective_symmetry_alone_enforces_case_i_relations":
            False,

        "two_minus_case_i_q2_coefficient":
            two_minus_kinetic,

        "two_minus_case_i_constant_operator":
            two_minus_constant,

        "one_minus_case_i_q2_determinant_factor":
            one_minus_q2_factor,

        "one_minus_case_i_constant_determinant_term":
            one_minus_constant,

        "case_i_removes_unwanted_momentum_dependence":
            momentum_dependence_removed,

        "case_i_reduced_unwanted_blocks_remain_nondegenerate":
            unwanted_blocks_remain_nondegenerate,

        "case_i_mode_removal_established_as_new_gauge_null_direction":
            False,

        "generic_beta_witness":
            generic_beta_witness.tolist(),

        "generic_beta_normal_component":
            generic_normal_flow.tolist(),

        "generic_beta_normal_component_norm":
            generic_normal_norm,

        "generic_rg_flow_automatically_tangent":
            bool(
                generic_normal_norm
                <=
                TOL
            ),

        "generic_beta_witness_is_actual_beta_function":
            False,

        "actual_case_i_beta_functions_computed":
            False,

        "additional_nonaccidental_symmetry_enforcing_case_i_established":
            False,

        "case_i_radiative_stability_established":
            False,

        "technical_naturalness_gate_pass":
            False,

        "naturalness_status":
            "BLOCKED_PROTECTION_NOT_ESTABLISHED",

        "global_no_go_for_any_protected_case_i_completion":
            False,
    }


def h17a9r3_summary() -> dict[str, Any]:
    """Return conservative A9R3 classification."""

    provenance = a9r2_provenance_gate()

    geometry = covariant_projector_geometry_gate()

    equivariance = covariant_projector_gl_equivariance_gate()

    regression = flat_covariant_projector_regression_gate()

    clean = clean_covariant_source_gate()

    stress = same_action_clean_metric_stress_gate()

    ward = clean_same_action_diffeomorphism_ward_gate()

    protection = case_i_protection_audit()

    geometric_noether_green = bool(
        provenance[
            "a9r2_provenance_pass"
        ]
        and
        geometry[
            "lorentzian_metric"
        ]
        and
        geometry[
            "covariant_trace_zero"
        ]
        and
        geometry[
            "covariant_idempotent"
        ]
        and
        geometry[
            "covariant_gauge_image_annihilated"
        ]
        and
        geometry[
            "covariant_tf_symmetry_preserved"
        ]
        and
        geometry[
            "covariant_self_adjoint"
        ]
        and
        equivariance[
            "gl4_equivariance_pass"
        ]
        and
        regression[
            "flat_covariant_projector_matches_a9r2"
        ]
        and
        clean[
            "a9_numerator_preserved"
        ]
        and
        stress[
            "same_action_linearized_clean_metric_stress_matches_a9r1"
        ]
        and
        ward[
            "all_clean_same_action_linearized_diffeo_witnesses_pass"
        ]
    )

    naturalness_pass = protection[
        "technical_naturalness_gate_pass"
    ]

    promotable = bool(
        geometric_noether_green
        and
        naturalness_pass
    )

    if (
        geometric_noether_green
        and
        not naturalness_pass
    ):
        decision = (
            "YELLOW_BLOCKED_A9R3_COVARIANT_PROJECTOR_AND_"
            "SAME_ACTION_CLEAN_LINEARIZED_METRIC_STRESS_PASS__"
            "PERCACCI_SEZGIN_CASE_I_TECHNICAL_NATURALNESS_"
            "PROTECTION_NOT_ESTABLISHED"
        )

    elif promotable:
        decision = (
            "GREEN_PARTIAL_A9R3_COVARIANT_PROJECTOR_"
            "SAME_ACTION_LINEARIZED_NOETHER_AND_PROTECTION_PASS"
        )

    else:
        decision = (
            "RED_SCOPED_A9R3_COVARIANT_OR_SAME_ACTION_"
            "LINEARIZED_NOETHER_GATE_FAILED"
        )

    return {
        "branch":
            "032H17A9R3",

        "subgate":
            (
                "COVARIANT_PROJECTIVE_DISTORTION_"
                "SAME_ACTION_METRIC_STRESS_CASE_I_PROTECTION"
            ),

        "decision":
            decision,

        "a9r2_provenance_pass":
            provenance[
                "a9r2_provenance_pass"
            ],

        "covariant_geometric_projector_established":
            bool(
                geometry[
                    "covariant_trace_zero"
                ]
                and
                geometry[
                    "covariant_idempotent"
                ]
                and
                geometry[
                    "covariant_gauge_image_annihilated"
                ]
                and
                equivariance[
                    "gl4_equivariance_pass"
                ]
            ),

        "projector_gl4_equivariance_pass":
            equivariance[
                "gl4_equivariance_pass"
            ],

        "projector_flat_limit_matches_a9r2":
            regression[
                "flat_covariant_projector_matches_a9r2"
            ],

        "clean_a9_source_survives_covariant_projector":
            clean[
                "clean_source_unchanged"
            ],

        "clean_a9_exact_1plus_pole_numerator":
            clean[
                "exact_1plus_pole_numerator"
            ],

        "clean_a9_exact_1plus_pole_preserved":
            clean[
                "a9_numerator_preserved"
            ],

        "same_action_linearized_clean_metric_stress_derived":
            stress[
                "same_action_linearized_clean_metric_stress_matches_a9r1"
            ],

        "same_action_linearized_s032":
            stress[
                "action_derived_s032"
            ],

        "same_action_linearized_sigma_matches_unique_a9r1_solution":
            stress[
                "same_action_linearized_clean_metric_stress_matches_a9r1"
            ],

        "same_action_clean_linearized_diffeomorphism_ward_pass":
            ward[
                "all_clean_same_action_linearized_diffeo_witnesses_pass"
            ],

        "geometric_and_clean_linearized_noether_partial_green":
            geometric_noether_green,

        "full_global_world_spinor_covariance_established":
            False,

        "full_curved_world_spinor_metric_stress_derived":
            False,

        "full_nonlinear_matter_noether_identity_established":
            False,

        "case_i_health_surface_codimension":
            protection[
                "case_i_health_surface_codimension_in_declared_coordinates"
            ],

        "projective_symmetry_alone_enforces_case_i_health_relations":
            protection[
                "projective_symmetry_alone_enforces_case_i_relations"
            ],

        "case_i_mode_removal_is_new_gauge_null":
            protection[
                "case_i_mode_removal_established_as_new_gauge_null_direction"
            ],

        "additional_case_i_protecting_symmetry_established":
            protection[
                "additional_nonaccidental_symmetry_enforcing_case_i_established"
            ],

        "case_i_actual_beta_functions_computed":
            protection[
                "actual_case_i_beta_functions_computed"
            ],

        "case_i_radiative_stability_established":
            protection[
                "case_i_radiative_stability_established"
            ],

        "case_i_technical_naturalness_gate_pass":
            naturalness_pass,

        "current_ps_case_i_candidate_promotion_authorized":
            promotable,

        "current_ps_case_i_branch_status":
            (
                "BLOCKED_TECHNICAL_NATURALNESS"
                if not naturalness_pass
                else
                "PROMOTED"
            ),

        "unknown_protected_case_i_completion_globally_closed":
            False,

        "v26b1_metric_numerator_same_action_derived":
            False,

        "same_action_hook17_complete":
            False,

        "universal_physical_metric_established":
            False,

        "finite_payload_antigravity_established":
            False,

        "hook17_closed":
            False,

        "hook17_reference_capacity_rp1e12_j":
            HOOK17_REFERENCE_CAPACITY_RP1E12_J,

        "hook17_complete_energy_j":
            None,

        "strict_complete_operating_target_j":
            STRICT_COMPLETE_OPERATING_TARGET_J,

        "energy_optimization_authorized":
            False,

        "capacity_recalculation_authorized":
            False,

        "h17b_authorized":
            False,

        "physical_antigravity_model_found":
            False,

        "certified_sub10mj_model_found":
            False,

        "practical_device_found":
            False,

        "v26d_fallback_status":
            "RESUME_AUTHORIZED_IF_A9R3_BLOCKED",

        "v26d_resume_authorized":
            bool(
                geometric_noether_green
                and
                not naturalness_pass
            ),

        "v26e_status":
            "PAUSED_NOT_CLOSED",

        "next":
            (
                "032V26D_RESUME_PROTECTED_CT1_DHOST_KMM"
                if (
                    geometric_noether_green
                    and
                    not naturalness_pass
                )
                else
                "032H17A9R4_ONLY_IF_CASE_I_PROTECTION_IS_ESTABLISHED"
            ),

        "preserve_for_future":
            (
                "A9-A9R3 PROJECTIVE 1PLUS SOURCE/PROJECTOR/MATTER "
                "GEOMETRIC RESULTS REMAIN DURABLE PARTIAL RESULTS"
            ),

        "claim_scope":
            (
                "COVARIANT PROJECTIVE GEOMETRIC LIFT AND CLEAN "
                "LINEARIZED SAME-ACTION METRIC SOURCE; CURRENT "
                "P&S CASE-I HEALTH SURFACE BLOCKED ON UNESTABLISHED "
                "TECHNICAL NATURALNESS"
            ),
    }
