"""032V26B1R1 quadratic-hook off-state quantum-force preflight.

PURPOSE
-------
V26B1 found an algebraic active/off-state separation mechanism:

    g_phys = g + lambda Q(H,H) + ...

with:

    dQ/dH = 0 at H = 0

but:

    dQ/dH != 0 around an active background H_bar != 0.

That eliminates a TREE-LEVEL LINEAR off-state matter force.

It does not eliminate quantum exchange generated by the same quadratic
ordinary-matter vertex.

This module derives that unavoidable two-mediator descendant and asks whether
existing inverse-square-law tests already force the canonical active background
to carry more than the project's strict 10-MJ complete-energy objective.

The answer is tested rather than assumed.

QUADRATIC WORLDLINE VERTEX
--------------------------
Let X_A denote canonically normalized healthy bosonic modes and write the
nonrelativistic physical-metric perturbation as

    delta g_00
        =
    lambda M_AB X_A X_B.

For a point mass m,

    S_m
        approximately contains
    (m / 2) integral dt delta g_00.

For massless canonical Euclidean propagators

    <X_A(x) X_B(0)>
        =
    delta_AB / (4 pi^2 x^2),

the connected two-mediator exchange gives

    V_2(r)
        =
    - m1 m2 lambda^2 Tr(M^2)
      / (64 pi^3 r^3).

Only the magnitude is used for the empirical gate.

POWER-LAW GRAVITY NORMALIZATION
-------------------------------
Hoyle et al. parameterized short-range power-law corrections as

    V(r)
        =
    -G m1 m2 / r
    [
        1
        +
        beta_k
        (1 mm / r)^(k-1)
    ].

For k=3,

    beta_3
        =
    lambda^2 Tr(M^2)
    /
    [
        64 pi^3 G (1 mm)^2
    ].

The 2004 torsion-balance result reported

    |beta_3| < 2.8e-3

at 68 percent confidence.

This historical result is used as a conservative published empirical
preflight, not as a complete modern global fit.

ACTIVE-STATE NORMALIZATION
--------------------------
Choose a normalized classical field-space direction n_A and define

    q
        =
    n_A M_AB n_B.

The useful active response is

    Delta g_00
        =
    lambda q H^2.

Define the projector penalty

    R_P
        =
    Tr(M^2) / q^2.

For a real symmetric M and normalized n,

    R_P >= 1

by the Frobenius / Cauchy bound.

Hence the off-state force cannot be independently normalized away after the
active response is fixed.

However the classical background amplitude H is also free to increase while
the quadratic metric coefficient decreases. Therefore the empirical force
constraint becomes a LOWER bound on the required canonical active-field
amplitude, not automatically a no-go.

SPHERICAL CAPACITY PREFLIGHT
----------------------------
For one canonically normalized field-space direction with boundary value H on
a spherical region of radius R and Yukawa range ell, the minimum exterior
quadratic field energy of the decaying free solution is

    E_ext
        =
    2 pi R H^2
    (
        1 + R / ell
    )

in natural units.

For ell -> infinity,

    E_ext
        =
    2 pi R H^2.

This is a spherical canonical-field capacity bound / preflight.

It is not:

- a complete source energy;
- a support energy;
- a microscopic realization;
- a theorem for every tensor kinetic operator;
- a complete V26 energy ledger.

It is useful because if even this optimistic necessary field inventory exceeded
10 MJ, the quadratic hook portal could be rejected before action construction.

If instead it lies vastly below 10 MJ, the quantum-force descendant does not
by itself kill the architecture and an explicit same-action construction remains
scientifically justified.

RANGE
-----
The device-scale reference range is 0.20 m.

At the 1-mm normalization scale used in the power-law experiment,

    r / ell = 0.005

so a mediator with device-scale range is effectively massless for this
particular preflight.

CLAIM LIMITS
------------
This module does NOT establish:

- the actual healthy V26 hook propagator;
- a same-action Dirac source / propagator / metric bridge;
- the actual projector penalty;
- the sign of the operational acceleration;
- finite-payload response;
- source charge per joule;
- microscopic source energy;
- stability;
- naturalness;
- empirical viability of a completed model;
- a sub-10-MJ device.

No AGMINER database mutation is performed.

CLAIM_CLASSIFICATION=
SCOPED_QUADRATIC_HOOK_QUANTUM_FORCE_AND_CAPACITY_PREFLIGHT
"""

from __future__ import annotations

import math
from typing import Any


HBARC_EV_M = 1.973269804e-7
EV_J = 1.602176634e-19

# Newton's constant in natural units.
#
#     G_N ~= 6.70883e-39 GeV^-2
#         ~= 6.70883e-57 eV^-2
G_NEWTON_EV_M2 = 6.70883e-57

C_LIGHT_M_S = 299792458.0
STANDARD_GRAVITY_M_S2 = 9.80665

PAYLOAD_LENGTH_M = 0.10
FIELD_LOCALIZATION_RADIUS_M = 0.10
DEVICE_RANGE_M = 0.20

POWERLAW_REFERENCE_LENGTH_M = 1.0e-3
HOYLE_2004_BETA3_68_ABS = 2.8e-3

STRICT_ENERGY_TARGET_J = 1.0e7


def _positive(
    value: float,
    name: str,
) -> float:
    """Return a finite positive float."""
    result = float(
        value
    )

    if (
        not math.isfinite(
            result
        )
        or result <= 0.0
    ):
        raise ValueError(
            f"{name} must be finite and positive"
        )

    return result


def meters_to_ev_inverse(
    length_m: float,
) -> float:
    """Convert meters to inverse electron-volts."""
    length = _positive(
        length_m,
        "length_m",
    )

    return (
        length
        /
        HBARC_EV_M
    )


def joules_to_ev(
    energy_j: float,
) -> float:
    """Convert joules to electron-volts."""
    energy = _positive(
        energy_j,
        "energy_j",
    )

    return (
        energy
        /
        EV_J
    )


def ev_to_joules(
    energy_ev: float,
) -> float:
    """Convert electron-volts to joules."""
    energy = _positive(
        energy_ev,
        "energy_ev",
    )

    return (
        energy
        *
        EV_J
    )


def required_lapse_change(
    *,
    acceleration_m_s2: float = STANDARD_GRAVITY_M_S2,
    length_m: float = PAYLOAD_LENGTH_M,
) -> float:
    """Return |Delta g00| ~= 2 a L / c^2."""
    acceleration = _positive(
        acceleration_m_s2,
        "acceleration_m_s2",
    )

    length = _positive(
        length_m,
        "length_m",
    )

    return (
        2.0
        *
        acceleration
        *
        length
        /
        C_LIGHT_M_S**2
    )


def two_mediator_inverse_cube_coefficient() -> float:
    """Return the canonical two-boson coefficient 1/(64*pi^3).

    With

        delta g00 = lambda M_AB X_A X_B,

    and point-mass interaction

        (m/2) delta g00,

    Wick contraction and static Euclidean-time integration give

        |V(r)|
            =
        m1 m2 lambda^2 Tr(M^2)
        /
        (64 pi^3 r^3).
    """

    return (
        1.0
        /
        (
            64.0
            *
            math.pi**3
        )
    )


def beta3_from_active_coupling(
    *,
    active_coupling_ev_m2: float,
    projector_penalty: float = 1.0,
    reference_length_m: float = POWERLAW_REFERENCE_LENGTH_M,
) -> float:
    """Return beta_3 for lambda*q after canonical normalization.

    active_coupling_ev_m2 is

        |lambda q|,

    while projector_penalty is

        Tr(M^2) / q^2 >= 1.
    """

    coupling = _positive(
        active_coupling_ev_m2,
        "active_coupling_ev_m2",
    )

    penalty = _positive(
        projector_penalty,
        "projector_penalty",
    )

    if penalty < 1.0:
        raise ValueError(
            "projector_penalty must be >= 1"
        )

    reference = (
        meters_to_ev_inverse(
            reference_length_m
        )
    )

    return (
        coupling**2
        *
        penalty
        /
        (
            64.0
            *
            math.pi**3
            *
            G_NEWTON_EV_M2
            *
            reference**2
        )
    )


def active_coupling_limit_from_beta3(
    *,
    beta3_abs_limit: float = HOYLE_2004_BETA3_68_ABS,
    projector_penalty: float = 1.0,
    reference_length_m: float = POWERLAW_REFERENCE_LENGTH_M,
) -> dict[str, float]:
    """Return maximum |lambda q| allowed by the declared beta_3 bound."""
    beta_limit = _positive(
        beta3_abs_limit,
        "beta3_abs_limit",
    )

    penalty = _positive(
        projector_penalty,
        "projector_penalty",
    )

    if penalty < 1.0:
        raise ValueError(
            "projector_penalty must be >= 1"
        )

    reference = (
        meters_to_ev_inverse(
            reference_length_m
        )
    )

    coupling_max = (
        reference
        *
        math.sqrt(
            64.0
            *
            math.pi**3
            *
            G_NEWTON_EV_M2
            *
            beta_limit
            /
            penalty
        )
    )

    return {
        "beta3_abs_limit":
            beta_limit,

        "projector_penalty":
            penalty,

        "active_coupling_max_ev_m2":
            coupling_max,

        "equivalent_active_metric_scale_ev":
            1.0
            /
            math.sqrt(
                coupling_max
            ),

        "equivalent_active_metric_scale_tev":
            (
                1.0
                /
                math.sqrt(
                    coupling_max
                )
                /
                1.0e12
            ),
    }


def required_background_amplitude(
    *,
    active_coupling_ev_m2: float,
    delta_g00: float,
) -> dict[str, float]:
    """Return H required by |Delta g00| = |lambda q| H^2."""
    coupling = _positive(
        active_coupling_ev_m2,
        "active_coupling_ev_m2",
    )

    lapse = _positive(
        delta_g00,
        "delta_g00",
    )

    amplitude_squared = (
        lapse
        /
        coupling
    )

    return {
        "background_amplitude_squared_ev2":
            amplitude_squared,

        "background_amplitude_ev":
            math.sqrt(
                amplitude_squared
            ),

        "background_amplitude_kev":
            math.sqrt(
                amplitude_squared
            )
            /
            1.0e3,
    }


def spherical_capacity_energy_j(
    *,
    background_amplitude_ev: float,
    radius_m: float = FIELD_LOCALIZATION_RADIUS_M,
    range_m: float | None = None,
) -> dict[str, float]:
    """Return exterior canonical-field spherical capacity energy.

    The decaying Yukawa solution outside a sphere gives

        E = 2*pi*R*H^2*(1 + R/ell).

    ell=None is the massless limit.
    """

    amplitude = _positive(
        background_amplitude_ev,
        "background_amplitude_ev",
    )

    radius = _positive(
        radius_m,
        "radius_m",
    )

    radius_ev_inverse = (
        meters_to_ev_inverse(
            radius
        )
    )

    range_factor = 1.0

    if range_m is not None:
        range_value = _positive(
            range_m,
            "range_m",
        )

        range_factor = (
            1.0
            +
            radius
            /
            range_value
        )

    energy_ev = (
        2.0
        *
        math.pi
        *
        radius_ev_inverse
        *
        amplitude**2
        *
        range_factor
    )

    return {
        "radius_m":
            radius,

        "range_m":
            (
                float(
                    range_m
                )
                if range_m is not None
                else math.inf
            ),

        "range_factor":
            range_factor,

        "energy_ev":
            energy_ev,

        "energy_j":
            ev_to_joules(
                energy_ev
            ),
    }


def empirical_capacity_corridor(
    *,
    projector_penalty: float = 1.0,
    beta3_abs_limit: float = HOYLE_2004_BETA3_68_ABS,
    acceleration_m_s2: float = STANDARD_GRAVITY_M_S2,
    payload_length_m: float = PAYLOAD_LENGTH_M,
    localization_radius_m: float = FIELD_LOCALIZATION_RADIUS_M,
    device_range_m: float = DEVICE_RANGE_M,
) -> dict[str, Any]:
    """Return the combined inverse-cube / active-background capacity scout."""
    penalty = _positive(
        projector_penalty,
        "projector_penalty",
    )

    if penalty < 1.0:
        raise ValueError(
            "projector_penalty must be >= 1"
        )

    lapse = (
        required_lapse_change(
            acceleration_m_s2=
                acceleration_m_s2,

            length_m=
                payload_length_m,
        )
    )

    coupling = (
        active_coupling_limit_from_beta3(
            beta3_abs_limit=
                beta3_abs_limit,

            projector_penalty=
                penalty,
        )
    )

    background = (
        required_background_amplitude(
            active_coupling_ev_m2=
                coupling[
                    "active_coupling_max_ev_m2"
                ],

            delta_g00=
                lapse,
        )
    )

    massless_capacity = (
        spherical_capacity_energy_j(
            background_amplitude_ev=
                background[
                    "background_amplitude_ev"
                ],

            radius_m=
                localization_radius_m,

            range_m=
                None,
        )
    )

    range_capacity = (
        spherical_capacity_energy_j(
            background_amplitude_ev=
                background[
                    "background_amplitude_ev"
                ],

            radius_m=
                localization_radius_m,

            range_m=
                device_range_m,
        )
    )

    reconstructed_beta3 = (
        beta3_from_active_coupling(
            active_coupling_ev_m2=
                coupling[
                    "active_coupling_max_ev_m2"
                ],

            projector_penalty=
                penalty,
        )
    )

    return {
        "projector_penalty":
            penalty,

        "required_delta_g00":
            lapse,

        "empirical_beta3_abs_limit":
            beta3_abs_limit,

        "active_coupling_max_ev_m2":
            coupling[
                "active_coupling_max_ev_m2"
            ],

        "equivalent_active_metric_scale_tev":
            coupling[
                "equivalent_active_metric_scale_tev"
            ],

        "minimum_background_amplitude_kev":
            background[
                "background_amplitude_kev"
            ],

        "massless_capacity_energy_j":
            massless_capacity[
                "energy_j"
            ],

        "device_range_capacity_energy_j":
            range_capacity[
                "energy_j"
            ],

        "device_range_factor":
            range_capacity[
                "range_factor"
            ],

        "reconstructed_beta3":
            reconstructed_beta3,

        "capacity_energy_below_strict_10mj":
            bool(
                range_capacity[
                    "energy_j"
                ]
                <
                STRICT_ENERGY_TARGET_J
            ),

        "capacity_energy_fraction_of_10mj":
            (
                range_capacity[
                    "energy_j"
                ]
                /
                STRICT_ENERGY_TARGET_J
            ),

        "this_is_complete_source_energy":
            False,

        "this_is_complete_operating_energy":
            False,
    }


def projector_penalty_at_energy_target(
    *,
    beta3_abs_limit: float = HOYLE_2004_BETA3_68_ABS,
    energy_target_j: float = STRICT_ENERGY_TARGET_J,
    device_range_m: float = DEVICE_RANGE_M,
) -> dict[str, float]:
    """Return projector penalty needed for the capacity floor to reach target.

    At fixed empirical beta_3 limit,

        lambda_max proportional to R_P^-1/2

    and therefore

        E_capacity proportional to R_P^1/2.
    """

    target = _positive(
        energy_target_j,
        "energy_target_j",
    )

    unit = (
        empirical_capacity_corridor(
            projector_penalty=
                1.0,

            beta3_abs_limit=
                beta3_abs_limit,

            device_range_m=
                device_range_m,
        )
    )

    unit_energy = float(
        unit[
            "device_range_capacity_energy_j"
        ]
    )

    penalty = (
        target
        /
        unit_energy
    )**2

    return {
        "unit_projector_capacity_energy_j":
            unit_energy,

        "energy_target_j":
            target,

        "projector_penalty_for_target":
            penalty,

        "sqrt_projector_penalty_for_target":
            math.sqrt(
                penalty
            ),
    }


def range_massless_preflight(
    *,
    experiment_length_m: float = POWERLAW_REFERENCE_LENGTH_M,
    device_range_m: float = DEVICE_RANGE_M,
) -> dict[str, Any]:
    """Return whether the device-range mediator is effectively light at 1 mm."""
    experiment_length = _positive(
        experiment_length_m,
        "experiment_length_m",
    )

    device_range = _positive(
        device_range_m,
        "device_range_m",
    )

    ratio = (
        experiment_length
        /
        device_range
    )

    return {
        "experiment_length_m":
            experiment_length,

        "device_range_m":
            device_range,

        "m_times_r":
            ratio,

        "massless_preflight_valid":
            bool(
                ratio
                <=
                1.0e-2
            ),
    }


def v26b1r1_gate() -> dict[str, Any]:
    """Return conservative decision for the quadratic hook quantum-force gate."""
    nominal = (
        empirical_capacity_corridor(
            projector_penalty=
                1.0
        )
    )

    extreme = (
        empirical_capacity_corridor(
            projector_penalty=
                1.0e12
        )
    )

    target_penalty = (
        projector_penalty_at_energy_target()
    )

    range_gate = (
        range_massless_preflight()
    )

    return {
        "phase":
            "032V26B1R1",

        "claim_classification":
            (
                "SCOPED_QUADRATIC_HOOK_QUANTUM_FORCE_"
                "AND_CAPACITY_PREFLIGHT"
            ),

        "quadratic_metric_has_offstate_two_mediator_force":
            True,

        "offstate_linear_response_zero_implies_zero_quantum_force":
            False,

        "inverse_cube_empirical_constraint_applies_in_massless_preflight":
            range_gate[
                "massless_preflight_valid"
            ],

        "nominal_projector_capacity_floor_j":
            nominal[
                "device_range_capacity_energy_j"
            ],

        "projector_1e12_capacity_floor_j":
            extreme[
                "device_range_capacity_energy_j"
            ],

        "projector_penalty_required_to_hit_10mj":
            target_penalty[
                "projector_penalty_for_target"
            ],

        "empirical_inverse_cube_gate_closes_quadratic_hook_portal":
            False,

        "same_action_construction_still_required":
            True,

        "explicit_action_construction_authorized":
            True,

        "energy_optimization_authorized":
            False,

        "action_oracle_authorized":
            False,

        "agminer_database_mutation_authorized":
            False,

        "next":
            (
                "032V26C_EXPLICIT_SYMMETRY_COMPATIBLE_"
                "SAME_ACTION_HOOK_METRIC_CONSTRUCTION"
            ),
    }
