"""Local traction, bag-shape, fixed-number, and RG helpers for 032V19R1.

PURPOSE
-------
Close a physical gap deliberately left open by 032V19.

V19 established that a positive-energy false-vacuum fermion bag can realize
the spherical mean support pressure near the V18 anisotropic DEC support
floor.

It did not yet solve the local angle-dependent wall traction generated by the
dipolar canonical scalar field.

This module keeps four distinct objects separate:

1. global integrated stress ledgers;
2. local normal wall traction;
3. first-order l=2 wall-shape response;
4. exact positive-band source response after geometry changes.

SCIENTIFIC QUESTION
-------------------
Does a physical positive-energy support action remain compatible with the
finite-payload 1g target once local wall traction is imposed and the source
mean field is recomputed in the deformed geometry?

A second question is whether the existing fixed-order axial wavefunction
running problem can be repaired merely by changing the EFT cutoff.

CLAIM LIMITS
------------
This module does not establish:

- a nonlinear chi/Psi/phi field solution;
- complete local conservation of such a solved field;
- nonlinear l=2 stability;
- a renormalized fermion determinant;
- an outward-sign universal UV completion;
- empirical viability;
- complete operating energy;
- a practical antigravity device.
"""

from __future__ import annotations

import math

import numpy as np
from scipy.optimize import root

from antigravity_research.agminer.axial_dirac_meanfield import (
    axial_positive_band_integrals,
)
from antigravity_research.agminer.kinetic_conformal import (
    EV_J,
    HBARC_EV_M,
)


def sphere_volume_m3(
    radius_m: float,
) -> float:
    """Return spherical volume in cubic meters."""

    radius = float(radius_m)

    if radius <= 0.0:
        raise ValueError(
            "radius must be positive"
        )

    return (
        4.0
        * math.pi
        * radius**3
        / 3.0
    )


def spheroid_volume_m3(
    a_m: float,
    c_m: float,
) -> float:
    """Return axisymmetric spheroid volume."""

    a = float(a_m)
    c = float(c_m)

    if (
        a <= 0.0
        or c <= 0.0
    ):
        raise ValueError(
            "semi-axes must be positive"
        )

    return (
        4.0
        * math.pi
        * a**2
        * c
        / 3.0
    )


def spheroid_area_m2(
    a_m: float,
    c_m: float,
) -> float:
    """Return exact axisymmetric spheroid surface area."""

    a = float(a_m)
    c = float(c_m)

    if (
        a <= 0.0
        or c <= 0.0
    ):
        raise ValueError(
            "semi-axes must be positive"
        )

    scale = max(
        a,
        c,
    )

    if (
        abs(
            a
            - c
        )
        <=
        1.0e-12
        * scale
    ):
        return (
            4.0
            * math.pi
            * a**2
        )

    if c > a:
        eccentricity = math.sqrt(
            1.0
            - a**2
            / c**2
        )

        return (
            2.0
            * math.pi
            * a**2
            * (
                1.0
                +
                c
                / (
                    a
                    * eccentricity
                )
                * math.asin(
                    eccentricity
                )
            )
        )

    eccentricity = math.sqrt(
        1.0
        - c**2
        / a**2
    )

    return (
        2.0
        * math.pi
        * a**2
        * (
            1.0
            +
            (
                1.0
                - eccentricity**2
            )
            / eccentricity
            * math.atanh(
                eccentricity
            )
        )
    )


def spheroid_demag_z(
    a_m: float,
    c_m: float,
) -> float:
    """Return exact z demagnetization factor."""

    a = float(a_m)
    c = float(c_m)

    if (
        a <= 0.0
        or c <= 0.0
    ):
        raise ValueError(
            "semi-axes must be positive"
        )

    if (
        abs(
            a
            - c
        )
        <=
        1.0e-12
        * max(
            a,
            c,
        )
    ):
        return (
            1.0
            / 3.0
        )

    if c > a:
        eccentricity = math.sqrt(
            1.0
            - a**2
            / c**2
        )

        return (
            (
                1.0
                - eccentricity**2
            )
            /
            (
                2.0
                * eccentricity**3
            )
            * (
                math.log(
                    (
                        1.0
                        + eccentricity
                    )
                    /
                    (
                        1.0
                        - eccentricity
                    )
                )
                -
                2.0
                * eccentricity
            )
        )

    xi = math.sqrt(
        a**2
        / c**2
        - 1.0
    )

    return (
        (
            1.0
            + xi**2
        )
        / xi**3
        * (
            xi
            - math.atan(
                xi
            )
        )
    )


def local_spherical_traction_multipoles(
    *,
    fermion_pressure_perp_inventory_j: float,
    fermion_pressure_z_inventory_j: float,
    scalar_field_energy_j: float,
    sphere_volume_m3_value: float,
) -> dict[str, float]:
    """Return l=0 and l=2 normal traction coefficients on a sphere.

    Uniform anisotropic fermion pressure has

        p_n
            =
            p_perp sin^2(theta)
            +
            p_z cos^2(theta).

    Therefore

        p_n
            =
            p0
            +
            p2 P2(cos theta)

    with

        p0 V
            =
            (2 P_perp + P_z)/3

    and

        p2 V
            =
            2(P_z-P_perp)/3.

    For the canonical uniformly polarized scalar dipole, matching the
    interior and exterior spherical solutions gives local wall traction

        p_phi(theta)
            =
            (E_phi/V)
            cos^2(theta).

    Hence

        p0_phi V
            =
            E_phi/3

    and

        p2_phi V
            =
            2 E_phi/3.

    This local wall-traction decomposition is not the same object as the
    global integrated scalar stress tensor used for the V18 DEC support
    lower bound.
    """

    p_perp = float(
        fermion_pressure_perp_inventory_j
    )

    p_z = float(
        fermion_pressure_z_inventory_j
    )

    e_phi = float(
        scalar_field_energy_j
    )

    volume = float(
        sphere_volume_m3_value
    )

    if (
        e_phi < 0.0
        or volume <= 0.0
    ):
        raise ValueError(
            "invalid traction input"
        )

    fermion_l0_j = (
        2.0
        * p_perp
        + p_z
    ) / 3.0

    fermion_l2_j = (
        2.0
        * (
            p_z
            - p_perp
        )
        / 3.0
    )

    scalar_l0_j = (
        e_phi
        / 3.0
    )

    scalar_l2_j = (
        2.0
        * e_phi
        / 3.0
    )

    l0_j = (
        fermion_l0_j
        + scalar_l0_j
    )

    l2_j = (
        fermion_l2_j
        + scalar_l2_j
    )

    return {
        "fermion_l0_inventory_j":
            fermion_l0_j,

        "fermion_l2_inventory_j":
            fermion_l2_j,

        "scalar_l0_inventory_j":
            scalar_l0_j,

        "scalar_l2_inventory_j":
            scalar_l2_j,

        "total_l0_inventory_j":
            l0_j,

        "total_l2_inventory_j":
            l2_j,

        "total_l0_pressure_pa":
            l0_j
            / volume,

        "total_l2_pressure_pa":
            l2_j
            / volume,

        "scalar_pole_pressure_pa":
            e_phi
            / volume,

        "scalar_equator_pressure_pa":
            0.0,
    }


def false_vacuum_l0_support(
    *,
    radius_m: float,
    l0_pressure_pa: float,
    bag_fraction: float,
) -> dict[str, float]:
    """Return spherical l=0 false-vacuum plus wall support."""

    radius = float(
        radius_m
    )

    pressure = float(
        l0_pressure_pa
    )

    fraction = float(
        bag_fraction
    )

    if (
        radius <= 0.0
        or pressure <= 0.0
    ):
        raise ValueError(
            "positive radius and pressure required"
        )

    if (
        fraction < 0.0
        or fraction >= 1.0
    ):
        raise ValueError(
            "bag fraction must satisfy 0 <= x < 1"
        )

    volume = sphere_volume_m3(
        radius
    )

    area = (
        4.0
        * math.pi
        * radius**2
    )

    bag_density = (
        fraction
        * pressure
    )

    residual_pressure = (
        1.0
        - fraction
    ) * pressure

    tension = (
        radius
        * residual_pressure
        / 2.0
    )

    bag_energy = (
        bag_density
        * volume
    )

    wall_energy = (
        tension
        * area
    )

    return {
        "bag_fraction":
            fraction,

        "bag_energy_density_j_m3":
            bag_density,

        "wall_tension_j_m2":
            tension,

        "residual_wall_pressure_pa":
            residual_pressure,

        "sphere_bag_energy_j":
            bag_energy,

        "sphere_wall_energy_j":
            wall_energy,

        "sphere_support_energy_j":
            bag_energy
            + wall_energy,
    }


def linear_l2_shape_response(
    *,
    radius_m: float,
    l2_pressure_pa: float,
    wall_tension_j_m2: float,
) -> dict[str, float]:
    """Return first-order volume-preserving l=2 deformation.

    Write the wall as

        r(theta)
            =
            R
            [
                1
                +
                epsilon
                P2(cos theta)
            ].

    For constant isotropic surface tension sigma, the linearized curvature
    response of a spherical wall is

        delta(2H)_l
            =
            (l-1)(l+2)
            epsilon
            P_l
            / R.

    Therefore at l=2,

        epsilon
            =
            R p2
            /
            (4 sigma).

    The returned spheroid preserves the same first-order pole/equator aspect
    while enforcing exact volume conservation.

    This is a shape scout, not a nonlinear wall solution.
    """

    radius = float(
        radius_m
    )

    p2 = float(
        l2_pressure_pa
    )

    tension = float(
        wall_tension_j_m2
    )

    if (
        radius <= 0.0
        or tension <= 0.0
    ):
        raise ValueError(
            "positive radius and wall tension required"
        )

    epsilon = (
        radius
        * p2
        / (
            4.0
            * tension
        )
    )

    if (
        abs(
            epsilon
        )
        >= 0.5
    ):
        raise ValueError(
            "l=2 deformation outside small-shape regime"
        )

    aspect = (
        1.0
        + epsilon
    ) / (
        1.0
        - 0.5
        * epsilon
    )

    if aspect <= 0.0:
        raise ValueError(
            "invalid shape aspect"
        )

    a = (
        radius
        * aspect
        ** (
            -1.0
            / 3.0
        )
    )

    c = (
        radius
        * aspect
        ** (
            2.0
            / 3.0
        )
    )

    return {
        "epsilon_l2":
            epsilon,

        "pole_to_equator_aspect":
            aspect,

        "a_m":
            a,

        "c_m":
            c,

        "volume_ratio_to_reference_sphere":
            (
                spheroid_volume_m3(
                    a,
                    c,
                )
                /
                sphere_volume_m3(
                    radius
                )
            ),

        "demag_z":
            spheroid_demag_z(
                a,
                c,
            ),

        "surface_area_m2":
            spheroid_area_m2(
                a,
                c,
            ),
    }


def particle_number_from_state(
    *,
    mass_ev: float,
    axial_b_ev: float,
    chemical_potential_ev: float,
    flavors: int,
    volume_m3: float,
    order: int = 128,
) -> float:
    """Return total occupied positive-band particle number."""

    values = (
        axial_positive_band_integrals(
            mass_ev=
                float(
                    mass_ev
                ),

            axial_b_ev=
                float(
                    axial_b_ev
                ),

            chemical_potential_ev=
                float(
                    chemical_potential_ev
                ),

            order=
                int(
                    order
                ),
        )
    )

    return (
        int(
            flavors
        )
        * values[
            "number_density_ev3"
        ]
        * float(
            volume_m3
        )
        / HBARC_EV_M**3
    )


def fixed_number_meanfield_state(
    *,
    particle_number: float,
    volume_m3: float,
    demag_z: float,
    mass_ev: float,
    f_psi_ev: float,
    flavors: int,
    metric_scale_ev: float,
    initial_b_ev: float,
    initial_mu_ev: float,
    order: int = 96,
) -> dict[str, float]:
    """Solve fixed-number axial mean-field self-consistency.

    Unknowns are b and mu.

    The equations are

        N
            =
            N_f n(b,mu) V

    and

        b
            =
            N_z
            N_f J5(b,mu)
            /
            f^2.

    Hidden-fermion mass and derivative coupling are held fixed during each
    deformation solve.
    """

    number = float(
        particle_number
    )

    volume = float(
        volume_m3
    )

    nz = float(
        demag_z
    )

    mass = float(
        mass_ev
    )

    f_value = float(
        f_psi_ev
    )

    nf = int(
        flavors
    )

    metric_scale = float(
        metric_scale_ev
    )

    if (
        number <= 0.0
        or volume <= 0.0
        or not (
            0.0
            < nz
            < 1.0
        )
        or mass <= 0.0
        or f_value <= 0.0
        or nf < 1
        or metric_scale <= 0.0
    ):
        raise ValueError(
            "invalid fixed-number mean-field input"
        )

    volume_nat = (
        volume
        / HBARC_EV_M**3
    )

    def residual(
        log_values,
    ):
        b_value = math.exp(
            float(
                log_values[
                    0
                ]
            )
        )

        mu_value = math.exp(
            float(
                log_values[
                    1
                ]
            )
        )

        values = (
            axial_positive_band_integrals(
                mass_ev=
                    mass,

                axial_b_ev=
                    b_value,

                chemical_potential_ev=
                    mu_value,

                order=
                    int(
                        order
                    ),
            )
        )

        calculated_number = (
            nf
            * values[
                "number_density_ev3"
            ]
            * volume_nat
        )

        total_current = (
            nf
            * values[
                "axial_current_ev3"
            ]
        )

        self_consistent_b = (
            nz
            * total_current
            / f_value**2
        )

        if (
            calculated_number <= 0.0
            or self_consistent_b <= 0.0
        ):
            return np.array(
                [
                    1.0e6,
                    1.0e6,
                ],
                dtype=float,
            )

        return np.array(
            [
                math.log(
                    calculated_number
                    / number
                ),

                math.log(
                    self_consistent_b
                    / b_value
                ),
            ],
            dtype=float,
        )

    solved = root(
        residual,
        np.log(
            [
                float(
                    initial_b_ev
                ),

                float(
                    initial_mu_ev
                ),
            ]
        ),
        tol=
            1.0e-10,
    )

    if not solved.success:
        raise RuntimeError(
            "fixed-number axial mean-field solve failed"
        )

    b_value = math.exp(
        float(
            solved.x[
                0
            ]
        )
    )

    mu_value = math.exp(
        float(
            solved.x[
                1
            ]
        )
    )

    values = (
        axial_positive_band_integrals(
            mass_ev=
                mass,

            axial_b_ev=
                b_value,

            chemical_potential_ev=
                mu_value,

            order=
                max(
                    int(
                        order
                    ),
                    128,
                ),
        )
    )

    total_current = (
        nf
        * values[
            "axial_current_ev3"
        ]
    )

    q_value = (
        total_current
        /
        (
            f_value
            * metric_scale**2
        )
    )

    band_energy = (
        nf
        * values[
            "energy_density_ev4"
        ]
        * volume_nat
        * EV_J
    )

    pressure_perp = (
        nf
        * values[
            "pressure_perp_ev4"
        ]
        * volume_nat
        * EV_J
    )

    pressure_z = (
        nf
        * values[
            "pressure_z_ev4"
        ]
        * volume_nat
        * EV_J
    )

    field_energy = (
        0.5
        * nz
        * q_value**2
        * metric_scale**4
        * volume_nat
        * EV_J
    )

    calculated_number = (
        nf
        * values[
            "number_density_ev3"
        ]
        * volume_nat
    )

    cutoff = (
        4.0
        * math.pi
        * f_value
    )

    hard = max(
        mu_value,
        mass,
        b_value,
    )

    return {
        "axial_b_ev":
            b_value,

        "chemical_potential_ev":
            mu_value,

        "q":
            q_value,

        "particle_number":
            calculated_number,

        "particle_number_relative_error":
            (
                abs(
                    calculated_number
                    - number
                )
                / number
            ),

        "axial_current_ev3":
            total_current,

        "band_energy_j":
            band_energy,

        "field_energy_j":
            field_energy,

        "pressure_perp_inventory_j":
            pressure_perp,

        "pressure_z_inventory_j":
            pressure_z,

        "nda_cutoff_ev":
            cutoff,

        "hard_scale_ev":
            hard,

        "hard_scale_margin":
            cutoff
            / hard,

        "solver_residual_norm":
            float(
                np.linalg.norm(
                    residual(
                        solved.x
                    )
                )
            ),
    }


def f_for_declared_loop_cap(
    *,
    mass_ev: float,
    flavors: int,
    loop_proxy: float,
) -> float:
    """Return f satisfying L=N_f m^2/(4 pi^2 f^2)."""

    mass = float(
        mass_ev
    )

    nf = int(
        flavors
    )

    loop = float(
        loop_proxy
    )

    if (
        mass <= 0.0
        or nf < 1
        or loop <= 0.0
    ):
        raise ValueError(
            "invalid loop-cap input"
        )

    return (
        mass
        * math.sqrt(
            nf
            /
            (
                4.0
                * math.pi**2
                * loop
            )
        )
    )


def fixed_order_rg_structural_gate(
    *,
    loop_proxy: float,
    cutoff_ev: float,
    mass_ev: float,
    hard_scale_ev: float,
) -> dict[str, float | bool]:
    """Test whether any valid fixed-order cutoff can make Delta Z < 1.

    The declared V17/V18 diagnostic is

        Delta Z_LL
            =
            4 L
            log(Lambda/m).

    A source EFT must satisfy

        Lambda >= hard scale.

    Therefore the smallest fixed-order correction compatible with the
    occupied source is reached at

        Lambda = hard scale.
    """

    loop = float(
        loop_proxy
    )

    cutoff = float(
        cutoff_ev
    )

    mass = float(
        mass_ev
    )

    hard = float(
        hard_scale_ev
    )

    if (
        loop <= 0.0
        or cutoff <= mass
        or hard <= mass
    ):
        raise ValueError(
            "invalid RG structural-gate input"
        )

    delta_current = (
        4.0
        * loop
        * math.log(
            cutoff
            / mass
        )
    )

    delta_min_hard = (
        4.0
        * loop
        * math.log(
            hard
            / mass
        )
    )

    cutoff_for_delta_one = (
        mass
        * math.exp(
            1.0
            /
            (
                4.0
                * loop
            )
        )
    )

    loop_critical_at_cutoff = (
        1.0
        /
        (
            4.0
            * math.log(
                cutoff
                / mass
            )
        )
    )

    return {
        "delta_z_at_declared_cutoff":
            delta_current,

        "minimum_delta_z_with_cutoff_at_hard_scale":
            delta_min_hard,

        "cutoff_ev_for_delta_z_equal_one":
            cutoff_for_delta_one,

        "cutoff_for_delta_one_over_hard_scale":
            (
                cutoff_for_delta_one
                / hard
            ),

        "loop_critical_at_declared_cutoff":
            loop_critical_at_cutoff,

        "fixed_order_window_exists_above_hard_scale":
            (
                cutoff_for_delta_one
                >= hard
            ),
    }
