#!/usr/bin/env python3
"""Simulation 018A-6B2 — fine local multiscale fully coupled junction.

PURPOSE
-------
Resolve the microscopic Phi/sigma vortex core at adequate spatial resolution
without paying the cost of uniformly resolving the entire approximately
200-unit-wide wall/string domain at the same fine spacing.

018A-6B attempted simultaneous relaxation of:

    Phi amplitude;
    superconducting sigma amplitude;
    complex KLS wall field A;
    U(1)_X gauge links.

Its raw resolution sequence failed dramatically.

018A-6B1 then demonstrated that the failure was dominated by common-mode
Cartesian-lattice relaxation of the original 017P vortex:

    COMMON_MODE_RESIDUAL_RANGE_FRACTION
        =
        0.006400014...

and that matched KLS-specific quantities recovered:

    matched Sigma2 convergence;
    matched active-source health;
    matched variational identity;
    pure discrete envelope identity.

018A-6B1 also measured the actual microscopic core widths:

    Phi 10%-90% width
        =
        4.388744961936

    sigma 90%-10% width
        =
        3.137266860253.

The old fully coupled grids had only approximately 1.25-1.88 intervals across
the sigma transition.

That resolution is insufficient for continuum interpretation.

SCIENTIFIC QUESTION
-------------------
After resolving the microscopic junction/core with roughly 4-9 intervals
across the relevant Phi/sigma structures, does the KLS-specific fully coupled
relaxation converge to a finite local correction while preserving:

    one-sided wall termination;
    gauge-invariant phase locking;
    small perturbation of Sigma2;
    the string variational identity;
    healthy c_T and c_L;
    m=2..40 thin-string stability;
    active-source budget;
    radial stationarity?

MULTISCALE STRATEGY
-------------------
The outer wall and asymptotic vortex solution have already been established by:

    018A-5
    018A-6A.

The KLS-specific nonlinear backreaction was shown in 018A-6B1 to be localized
and small after matched subtraction.

Therefore this gate treats the large-scale 018A-6A field configuration as the
outer solution and refines the central wall/string junction where Phi, sigma
and gauge gradients are microscopic.

For each local fine patch:

    1. reconstruct the continuum 017P radial solution;
    2. construct and relax the 018A-6A complex A solution on the same patch;
    3. release Phi, sigma, A and gauge links simultaneously;
    4. independently relax the original 017P Phi/sigma/gauge system on the
       identical grid;
    5. subtract that base-string lattice relaxation.

Thus

    Delta E_KLS
      =
      Delta E_full
      -
      Delta E_base.

The fully coupled global junction estimate is then

    mu_J,estimate
      =
      mu_J,6A,global
      +
      Delta E_KLS.

The global fixed-background 018A-6A junction anchor is

    mu_J,6A,global
      =
      3.523059294668687e-3.

This quantity was separately shown to converge with domain and resolution.

The local fine calculation therefore supplies only the missing microscopic
backreaction correction; it does not re-estimate the long wall contribution
from an artificially truncated small patch.

SIGMA2 MATCHING
---------------
Use the same matched construction:

    Delta Sigma2_KLS
      =
      Delta Sigma2_full
      -
      Delta Sigma2_base

    Sigma2_full,matched
      =
      Sigma2_radial
      +
      Delta Sigma2_KLS.

ACTIVE-SOURCE MATCHING
----------------------
The high-resolution fixed-background 018A-6B0 endpoint active source is

    Lambda_J,fixed
      =
      4.070600791157473e-3.

The fine local coupled correction is

    Delta Lambda_KLS
      =
      Delta Lambda_full
      -
      Delta Lambda_base.

Then

    Lambda_J,matched
      =
      Lambda_J,fixed
      +
      Delta Lambda_KLS.

This explicitly removes the spurious active-source response generated by
relaxing the sampled original vortex on the Cartesian grid.

RESOLUTION SEQUENCE
-------------------
Fixed local half-width:

    L = 20.

Run:

    N=51
        dx=0.8

    N=65
        dx=0.625

    N=81
        dx=0.5.

At dx=0.5 this gives approximately:

    Phi 10%-90%
        8.78 intervals

    sigma 90%-10%
        6.27 intervals.

This is qualitatively different from 018A-6B.

PATCH-SIZE SEQUENCE
-------------------
Hold

    dx = 0.5

and vary:

    L=16, N=65

    L=20, N=81

    L=24, N=97.

If the KLS-specific correction is truly localized near the junction, the
matched correction must converge as the fine patch expands.

COMMON-GRID CHI CONTINUATION
----------------------------
For cost control use

    L=20
    N=65
    dx=0.625

at

    chi =
      0.00425
      0.00450
      0.00475.

For each chi:

    1. calculate the global fixed-background 018A-6A junction energy using the
       common N=81, L=100 discretization;

    2. calculate the fine local fully coupled correction;

    3. form

           A_eff
             =
             A_string
             +
             mu_fixed_global
             +
             Delta E_KLS;

    4. form matched Sigma2;

    5. test

           dA_eff/dchi
             =
             -Sigma2.

FULLY COUPLED MORPHOLOGY
------------------------
The selected N=81, L=20 solution must retain:

    A approximately zero along the negative-x wall center;

    A approximately at vacuum magnitude on the positive-x side;

    gauge-invariant phase locking away from the core and wall;

    Phi vortex core pinned at the origin.

EOS AND STABILITY
-----------------
From the matched chi continuation calculate:

    c_T^2 =
      1 /
      [
        1
        +
        2 chi Sigma2/A_eff
      ]

and

    c_L^2 =
      1 /
      [
        1
        +
        2 chi
        (dSigma2/dchi)
        /
        Sigma2
      ].

Repeat the journaled 017P m=2..40 cubic discriminant/root test.

STATIONARITY
------------
Use the selected matched full junction energy in both:

    one-junction bookkeeping;

    two-junction adversarial bookkeeping.

PASS CONDITIONS
---------------
This gate is green only if:

    FINE_CORE_RESOLUTION=PASS

    FINE_FULL_SOLVERS=PASS

    FINE_BASE_CONTROL_SOLVERS=PASS

    FINE_MATCHED_RESOLUTION_CONVERGENCE=PASS

    FINE_MATCHED_PATCH_CONVERGENCE=PASS

    FINE_WALL_TERMINATION=PASS

    FINE_RELATIVE_PHASE_LOCKING=PASS

    FINE_MATCHED_ACTIVE_SOURCE_BUDGET=PASS

    FINE_MATCHED_VARIATIONAL_IDENTITY=PASS

    FINE_EOS_HEALTH=PASS

    FINE_M2_TO_M40_STABILITY=PASS

    FINE_ONE_JUNCTION_STATIONARITY=PASS

    FINE_TWO_JUNCTION_STATIONARITY=PASS.

PROMOTION CONDITION
-------------------
A green result supports:

    FULLY_COUPLED_LOCAL_2D_KLS_JUNCTION
        =
        SUPPORTED_WITH_FINE_CORE_AND_MATCHED_OUTER_SOLUTION

at the straight-string/junction level.

That is sufficient to stop local microscopic-junction escalation and move to:

    018A7_COMPLETE_MICROSCOPIC_GRAVITY_CLOSEOUT.

018A7 must still test:

    mandatory total active mass;
    finite-payload outward acceleration;
    kernel leverage;
    complete energy bookkeeping;
    robustness.

Only a green 018A7 can make 018A green and authorize 018B.

FALSIFICATION
-------------
Do not promote if the fine matched correction:

    fails resolution convergence;
    fails patch-size convergence;
    becomes order-one compared with the 017P line scale;
    destroys wall termination;
    destroys variational consistency;
    drives EOS instability;
    destroys radial stationarity;
    creates a fatal active-source correction.

CLAIM CLASSIFICATION
--------------------
PROJECT_DERIVED_018A_FINE_LOCAL_MULTISCALE_FULLY_COUPLED_KLS_JUNCTION

PRACTICAL CLAIM
---------------
This run cannot establish a practical antigravity device.
"""

from __future__ import annotations

import importlib.util
import math
from pathlib import Path
import sys

import numpy as np


ROOT = Path(__file__).resolve().parents[1]

AUDIT = (
    ROOT
    / "simulations"
    / "018a6b1_matched_lattice_control_audit.py"
)


def load_module(
    name: str,
    path: Path,
):
    """Load an existing verified project simulation without running its main."""

    spec = importlib.util.spec_from_file_location(
        name,
        path,
    )

    if (
        spec is None
        or spec.loader is None
    ):
        raise RuntimeError(
            f"Unable to load {path}"
        )

    module = importlib.util.module_from_spec(
        spec
    )

    sys.modules[
        name
    ] = module

    try:
        spec.loader.exec_module(
            module
        )
    except Exception:
        sys.modules.pop(
            name,
            None,
        )
        raise

    return module


audit = load_module(
    "ag018a6b1_fine_multiscale",
    AUDIT,
)

fc = audit.fc
m = audit.m


# ============================================================================
# Physical anchors.
# ============================================================================

CHI_SELECTED = 0.00475

CHI_VALUES = (
    0.00425,
    0.00450,
    0.00475,
)

OMEGA = fc.OMEGA_SELECTED
K_LONG = fc.K_SELECTED

GLOBAL_FIXED_JUNCTION_ENERGY = (
    3.523059294668687e-3
)

GLOBAL_FIXED_JUNCTION_ACTIVE = (
    4.070600791157473e-3
)

PHI_WIDTH = (
    4.388744961936
)

SIGMA_WIDTH = (
    3.137266860253
)


# ============================================================================
# Numerical cases.
# ============================================================================

RESOLUTION_CASES = (
    (51, 20.0),
    (65, 20.0),
    (81, 20.0),
)

PATCH_CASES = (
    (65, 16.0),
    (81, 20.0),
    (97, 24.0),
)

CHI_CASE = (
    65,
    20.0,
)

GLOBAL_FIXED_CHI_CASE = (
    81,
    100.0,
)


# ============================================================================
# Gates.
# ============================================================================

MIN_SELECTED_PHI_INTERVALS = 8.0
MIN_SELECTED_SIGMA_INTERVALS = 6.0

MAX_CORRECTION_RESOLUTION_RANGE = 5.0e-4
MAX_SIGMA2_RESOLUTION_RANGE = 5.0e-4

MAX_CORRECTION_PATCH_RANGE = 5.0e-4
MAX_SIGMA2_PATCH_RANGE = 5.0e-4

MAX_NEGATIVE_WALL_A_OVER_F = 0.03
MIN_POSITIVE_A_OVER_F = 0.92

MAX_PHASE_LOCK_RMS = 2.0e-3

MAX_ACTIVE_PAIR_FRACTION = 0.01

MAX_VARIATIONAL_RELERR = 0.02

MIN_SCALE_SEPARATION = 10.0


FULL_CACHE = {}
BASE_CACHE = {}
FIXED_GLOBAL_CACHE = {}


def full_case(
    chi: float,
    n: int,
    box_half: float,
):
    """Solve or reuse one fine fully coupled local patch."""

    key = (
        round(
            float(
                chi
            ),
            9,
        ),
        int(
            n
        ),
        float(
            box_half
        ),
    )

    if key not in FULL_CACHE:

        FULL_CACHE[
            key
        ] = fc.solve_full_case(
            chi,
            n,
            box_half,
        )

    return FULL_CACHE[
        key
    ]


def base_case(
    chi: float,
    n: int,
    box_half: float,
):
    """Solve or reuse one matched original-017P local control."""

    key = (
        round(
            float(
                chi
            ),
            9,
        ),
        int(
            n
        ),
        float(
            box_half
        ),
    )

    if key not in BASE_CACHE:

        BASE_CACHE[
            key
        ] = audit.solve_base_case(
            chi,
            n,
            box_half,
        )

    return BASE_CACHE[
        key
    ]


def global_fixed_case(
    chi: float,
):
    """Return the common-grid large-domain fixed-background 018A-6A endpoint."""

    key = round(
        float(
            chi
        ),
        9,
    )

    if key not in FIXED_GLOBAL_CACHE:

        m.CHI_SELECTED = float(
            chi
        )

        radial = (
            m.solve_017p_background()
        )

        fixed = (
            m.run_case(
                radial,
                n=GLOBAL_FIXED_CHI_CASE[
                    0
                ],
                box_half=GLOBAL_FIXED_CHI_CASE[
                    1
                ],
            )
        )

        diag = (
            m.diagnose_017p(
                radial
            )
        )

        FIXED_GLOBAL_CACHE[
            key
        ] = (
            fixed,
            diag,
        )

    return FIXED_GLOBAL_CACHE[
        key
    ]


def matched_local(
    chi: float,
    n: int,
    box_half: float,
):
    """Return fine KLS-specific correction with base lattice relaxation removed."""

    full = full_case(
        chi,
        n,
        box_half,
    )

    base = base_case(
        chi,
        n,
        box_half,
    )

    delta_e = (
        full.relaxation_delta_energy
        -
        base.delta_energy
    )

    delta_sigma2 = (
        full.delta_sigma2
        -
        base.delta_sigma2
    )

    sigma2 = (
        full.sigma2_background
        +
        delta_sigma2
    )

    full_active = (
        fc.active_source_diagnostics(
            full
        )
    )

    delta_active = (
        full_active[
            "active_relaxation_delta"
        ]
        -
        base.delta_active
    )

    endpoint_active = (
        GLOBAL_FIXED_JUNCTION_ACTIVE
        +
        delta_active
    )

    active_pair = (
        4.0
        *
        full.sigma2_background
        *
        (
            OMEGA**2
            +
            K_LONG**2
        )
    )

    active_fraction = (
        2.0
        *
        abs(
            endpoint_active
        )
        /
        active_pair
    )

    return {
        "full":
            full,

        "base":
            base,

        "delta_e":
            float(
                delta_e
            ),

        "delta_sigma2":
            float(
                delta_sigma2
            ),

        "sigma2":
            float(
                sigma2
            ),

        "delta_active":
            float(
                delta_active
            ),

        "endpoint_active":
            float(
                endpoint_active
            ),

        "active_fraction":
            float(
                active_fraction
            ),
    }


def local_morphology(
    full,
):
    """Measure topology/locking on a local fine patch."""

    p = full.problem

    x = (
        p.fixed_result.problem.x
    )

    radius = (
        p.fixed_result.problem.radius
    )

    center = int(
        np.argmin(
            np.abs(
                x
            )
        )
    )

    L = (
        full.box_half
    )

    negative = (
        (
            x
            >
            -0.75
            *
            L
        )
        &
        (
            x
            <
            -0.45
            *
            L
        )
    )

    positive = (
        (
            x
            >
            0.45
            *
            L
        )
        &
        (
            x
            <
            0.75
            *
            L
        )
    )

    negative_wall = float(
        np.max(
            np.abs(
                full.a[
                    negative,
                    center,
                ]
            )
        )
        /
        m.F_A
    )

    positive_recovery = float(
        np.min(
            np.abs(
                full.a[
                    positive,
                    center,
                ]
            )
        )
        /
        m.F_A
    )

    phi = (
        full.f
        *
        p.phi_phase
    )

    a_amp = np.abs(
        full.a
    )

    lock_cos = (
        np.real(
            np.conj(
                phi
            )
            *
            full.a
            *
            full.a
        )
        /
        np.maximum(
            full.f
            *
            a_amp
            *
            a_amp,
            1.0e-30,
        )
    )

    lock_mask = (
        (
            radius
            >
            8.0
        )
        &
        (
            full.f
            >
            0.90
        )
        &
        (
            a_amp
            >
            0.5
            *
            m.F_A
        )
    )

    if not np.any(
        lock_mask
    ):
        phase_lock = math.inf
    else:

        phase_lock = float(
            np.sqrt(
                np.mean(
                    (
                        1.0
                        -
                        lock_cos[
                            lock_mask
                        ]
                    ) ** 2
                )
            )
        )

    return {
        "negative_wall":
            negative_wall,

        "positive_recovery":
            positive_recovery,

        "phase_lock":
            phase_lock,

        "core_f":
            float(
                full.f[
                    center,
                    center,
                ]
            ),

        "core_a_over_f":
            float(
                np.abs(
                    full.a[
                        center,
                        center,
                    ]
                )
                /
                m.F_A
            ),
    }


def range_value(
    values,
) -> float:
    """Return max-min for a sequence."""

    array = np.asarray(
        values,
        dtype=float,
    )

    return float(
        np.max(
            array
        )
        -
        np.min(
            array
        )
    )


def main() -> None:
    """Execute the fine-core multiscale promotion gate."""

    original_chi = float(
        m.CHI_SELECTED
    )

    print(
        "=== ANTIGRAVITY_RESEARCH 018A-6B2 ==="
    )

    print(
        "QUESTION="
        "DOES_THE_FULLY_COUPLED_KLS_JUNCTION_CONVERGE_AFTER_THE_MICROSCOPIC_017P_CORE_IS_ACTUALLY_RESOLVED"
    )

    # ========================================================================
    # Resolution adequacy.
    # ========================================================================

    print(
        "\n=== DECLARED FINE-CORE RESOLUTION ==="
    )

    for (
        n,
        L,
    ) in RESOLUTION_CASES:

        dx = (
            2.0
            *
            L
            /
            (
                n
                -
                1
            )
        )

        print(
            "FINE_RESOLUTION "
            f"N={n} "
            f"L={L:.3f} "
            f"DX={dx:.12f} "
            f"PHI_INTERVALS={PHI_WIDTH / dx:.9f} "
            f"SIGMA_INTERVALS={SIGMA_WIDTH / dx:.9f}"
        )

    selected_dx = (
        2.0
        *
        RESOLUTION_CASES[
            -1
        ][
            1
        ]
        /
        (
            RESOLUTION_CASES[
                -1
            ][
                0
            ]
            -
            1
        )
    )

    selected_phi_intervals = (
        PHI_WIDTH
        /
        selected_dx
    )

    selected_sigma_intervals = (
        SIGMA_WIDTH
        /
        selected_dx
    )

    fine_resolution_pass = (
        selected_phi_intervals
        >=
        MIN_SELECTED_PHI_INTERVALS

        and
        selected_sigma_intervals
        >=
        MIN_SELECTED_SIGMA_INTERVALS
    )

    print(
        "SELECTED_PHI_INTERVALS="
        f"{selected_phi_intervals:.12f}"
    )

    print(
        "SELECTED_SIGMA_INTERVALS="
        f"{selected_sigma_intervals:.12f}"
    )

    print(
        "FINE_CORE_RESOLUTION="
        f"{'PASS' if fine_resolution_pass else 'FAIL'}"
    )

    # ========================================================================
    # Fine resolution convergence.
    # ========================================================================

    print(
        "\n=== FINE MATCHED RESOLUTION CONVERGENCE ==="
    )

    resolution_records = []

    for (
        n,
        L,
    ) in RESOLUTION_CASES:

        record = matched_local(
            CHI_SELECTED,
            n,
            L,
        )

        resolution_records.append(
            record
        )

        full = record[
            "full"
        ]

        base = record[
            "base"
        ]

        print(
            "FINE_MATCHED_RESOLUTION "
            f"N={n} "
            f"L={L:.3f} "
            f"DX={full.dx:.12f} "
            f"FULL_OPT={'PASS' if full.success else 'FAIL'} "
            f"BASE_OPT={'PASS' if base.success else 'FAIL'} "
            f"FULL_DELTA_E={full.relaxation_delta_energy:+.15e} "
            f"BASE_DELTA_E={base.delta_energy:+.15e} "
            f"KLS_DELTA_E={record['delta_e']:+.15e} "
            f"KLS_DELTA_SIGMA2={record['delta_sigma2']:+.15e} "
            f"SIGMA2_MATCHED={record['sigma2']:.15e} "
            f"ENDPOINT_ACTIVE={record['endpoint_active']:+.15e} "
            f"ACTIVE_PAIR_FRACTION={record['active_fraction']:.15e} "
            f"FULL_GRAD_RMS={full.grad_rms:.6e} "
            f"FULL_GRAD_MAX={full.grad_max:.6e} "
            f"BASE_GRAD_RMS={base.grad_rms:.6e} "
            f"BASE_GRAD_MAX={base.grad_max:.6e}"
        )

    full_solver_pass = all(
        record[
            "full"
        ].success
        for record
        in resolution_records
    )

    base_solver_pass = all(
        record[
            "base"
        ].success
        for record
        in resolution_records
    )

    resolution_delta_e_range = (
        range_value(
            [
                record[
                    "delta_e"
                ]
                for record
                in resolution_records
            ]
        )
    )

    resolution_delta_sigma_range = (
        range_value(
            [
                record[
                    "delta_sigma2"
                ]
                for record
                in resolution_records
            ]
        )
    )

    resolution_pass = (
        resolution_delta_e_range
        <
        MAX_CORRECTION_RESOLUTION_RANGE

        and
        resolution_delta_sigma_range
        <
        MAX_SIGMA2_RESOLUTION_RANGE
    )

    print(
        "FINE_KLS_DELTA_E_RESOLUTION_RANGE="
        f"{resolution_delta_e_range:.15e}"
    )

    print(
        "FINE_KLS_DELTA_SIGMA2_RESOLUTION_RANGE="
        f"{resolution_delta_sigma_range:.15e}"
    )

    print(
        "FINE_FULL_SOLVERS="
        f"{'PASS' if full_solver_pass else 'FAIL'}"
    )

    print(
        "FINE_BASE_CONTROL_SOLVERS="
        f"{'PASS' if base_solver_pass else 'FAIL'}"
    )

    print(
        "FINE_MATCHED_RESOLUTION_CONVERGENCE="
        f"{'PASS' if resolution_pass else 'FAIL'}"
    )

    selected_record = (
        resolution_records[
            -1
        ]
    )

    selected_full = (
        selected_record[
            "full"
        ]
    )

    # ========================================================================
    # Patch-size convergence.
    # ========================================================================

    print(
        "\n=== FINE PATCH-SIZE CONVERGENCE AT DX=0.5 ==="
    )

    patch_records = []

    for (
        n,
        L,
    ) in PATCH_CASES:

        record = matched_local(
            CHI_SELECTED,
            n,
            L,
        )

        patch_records.append(
            record
        )

        print(
            "FINE_PATCH "
            f"N={n} "
            f"L={L:.3f} "
            f"DX={record['full'].dx:.12f} "
            f"KLS_DELTA_E={record['delta_e']:+.15e} "
            f"KLS_DELTA_SIGMA2={record['delta_sigma2']:+.15e} "
            f"ACTIVE_PAIR_FRACTION={record['active_fraction']:.15e} "
            f"FULL_OPT={'PASS' if record['full'].success else 'FAIL'} "
            f"BASE_OPT={'PASS' if record['base'].success else 'FAIL'}"
        )

    patch_delta_e_range = (
        range_value(
            [
                record[
                    "delta_e"
                ]
                for record
                in patch_records
            ]
        )
    )

    patch_delta_sigma_range = (
        range_value(
            [
                record[
                    "delta_sigma2"
                ]
                for record
                in patch_records
            ]
        )
    )

    patch_pass = (
        patch_delta_e_range
        <
        MAX_CORRECTION_PATCH_RANGE

        and
        patch_delta_sigma_range
        <
        MAX_SIGMA2_PATCH_RANGE

        and
        all(
            record[
                "full"
            ].success
            and
            record[
                "base"
            ].success
            for record
            in patch_records
        )
    )

    print(
        "FINE_KLS_DELTA_E_PATCH_RANGE="
        f"{patch_delta_e_range:.15e}"
    )

    print(
        "FINE_KLS_DELTA_SIGMA2_PATCH_RANGE="
        f"{patch_delta_sigma_range:.15e}"
    )

    print(
        "FINE_MATCHED_PATCH_CONVERGENCE="
        f"{'PASS' if patch_pass else 'FAIL'}"
    )

    # ========================================================================
    # Selected topology / morphology.
    # ========================================================================

    print(
        "\n=== FINE SELECTED FULL-COUPLED MORPHOLOGY ==="
    )

    morph = local_morphology(
        selected_full
    )

    print(
        "FINE_NEGATIVE_WALL_A_OVER_F="
        f"{morph['negative_wall']:.15e}"
    )

    print(
        "FINE_POSITIVE_RECOVERY_A_OVER_F="
        f"{morph['positive_recovery']:.15e}"
    )

    print(
        "FINE_PHASE_LOCK_RMS="
        f"{morph['phase_lock']:.15e}"
    )

    print(
        "FINE_CORE_PHI="
        f"{morph['core_f']:.15e}"
    )

    print(
        "FINE_CORE_A_OVER_F="
        f"{morph['core_a_over_f']:.15e}"
    )

    termination_pass = (
        morph[
            "negative_wall"
        ]
        <
        MAX_NEGATIVE_WALL_A_OVER_F

        and
        morph[
            "positive_recovery"
        ]
        >
        MIN_POSITIVE_A_OVER_F
    )

    phase_pass = (
        morph[
            "phase_lock"
        ]
        <
        MAX_PHASE_LOCK_RMS
    )

    print(
        "FINE_WALL_TERMINATION="
        f"{'PASS' if termination_pass else 'FAIL'}"
    )

    print(
        "FINE_RELATIVE_PHASE_LOCKING="
        f"{'PASS' if phase_pass else 'FAIL'}"
    )

    selected_active_pass = (
        selected_record[
            "active_fraction"
        ]
        <
        MAX_ACTIVE_PAIR_FRACTION
    )

    print(
        "FINE_MATCHED_SELECTED_ENDPOINT_ACTIVE="
        f"{selected_record['endpoint_active']:+.15e}"
    )

    print(
        "FINE_MATCHED_SELECTED_ACTIVE_PAIR_FRACTION="
        f"{selected_record['active_fraction']:.15e}"
    )

    print(
        "FINE_MATCHED_ACTIVE_SOURCE_BUDGET="
        f"{'PASS' if selected_active_pass else 'FAIL'}"
    )

    # ========================================================================
    # Common-grid chi continuation.
    # ========================================================================

    print(
        "\n=== FINE MATCHED CHI CONTINUATION ==="
    )

    chi_records = []

    for chi in CHI_VALUES:

        local = matched_local(
            chi,
            CHI_CASE[
                0
            ],
            CHI_CASE[
                1
            ],
        )

        fixed_global, diag = (
            global_fixed_case(
                chi
            )
        )

        mu_effective = (
            fixed_global.junction_excess_energy
            +
            local[
                "delta_e"
            ]
        )

        a_effective = (
            diag.a_string
            +
            mu_effective
        )

        sigma_effective = (
            diag.sigma2
            +
            local[
                "delta_sigma2"
            ]
        )

        chi_records.append(
            {
                "chi":
                    float(
                        chi
                    ),

                "mu":
                    float(
                        mu_effective
                    ),

                "a":
                    float(
                        a_effective
                    ),

                "sigma2":
                    float(
                        sigma_effective
                    ),
            }
        )

        print(
            "FINE_CHI "
            f"CHI={chi:.9f} "
            f"MU_FIXED_GLOBAL={fixed_global.junction_excess_energy:+.15e} "
            f"LOCAL_KLS_CORRECTION={local['delta_e']:+.15e} "
            f"MU_MATCHED_FULL={mu_effective:+.15e} "
            f"A_EFF={a_effective:.15e} "
            f"SIGMA2_MATCHED={sigma_effective:.15e}"
        )

    chi_array = np.array(
        [
            item[
                "chi"
            ]
            for item
            in chi_records
        ],
        dtype=float,
    )

    a_array = np.array(
        [
            item[
                "a"
            ]
            for item
            in chi_records
        ],
        dtype=float,
    )

    sigma_array = np.array(
        [
            item[
                "sigma2"
            ]
            for item
            in chi_records
        ],
        dtype=float,
    )

    a_poly = np.polyfit(
        chi_array,
        a_array,
        2,
    )

    sigma_poly = np.polyfit(
        chi_array,
        sigma_array,
        2,
    )

    d_a = float(
        np.polyval(
            np.polyder(
                a_poly
            ),
            CHI_SELECTED,
        )
    )

    d_sigma = float(
        np.polyval(
            np.polyder(
                sigma_poly
            ),
            CHI_SELECTED,
        )
    )

    sigma_selected = float(
        sigma_array[
            -1
        ]
    )

    a_selected = float(
        a_array[
            -1
        ]
    )

    variational_relerr = (
        abs(
            d_a
            +
            sigma_selected
        )
        /
        sigma_selected
    )

    variational_pass = (
        variational_relerr
        <
        MAX_VARIATIONAL_RELERR
    )

    print(
        "FINE_DA_EFF_DCHI="
        f"{d_a:+.15e}"
    )

    print(
        "FINE_DSIGMA2_DCHI="
        f"{d_sigma:+.15e}"
    )

    print(
        "FINE_MATCHED_VARIATIONAL_RELERR="
        f"{variational_relerr:.15e}"
    )

    print(
        "FINE_MATCHED_VARIATIONAL_IDENTITY="
        f"{'PASS' if variational_pass else 'FAIL'}"
    )

    ct2 = (
        1.0
        /
        (
            1.0
            +
            2.0
            *
            CHI_SELECTED
            *
            sigma_selected
            /
            a_selected
        )
    )

    cl2 = (
        1.0
        /
        (
            1.0
            +
            2.0
            *
            CHI_SELECTED
            *
            d_sigma
            /
            sigma_selected
        )
    )

    eos_pass = (
        0.0
        <
        ct2
        <=
        1.0

        and
        0.0
        <
        cl2
        <=
        1.0
    )

    print(
        "FINE_CT2="
        f"{ct2:.15e}"
    )

    print(
        "FINE_CL2="
        f"{cl2:.15e}"
    )

    print(
        "FINE_EOS_HEALTH="
        f"{'PASS' if eos_pass else 'FAIL'}"
    )

    (
        stability_pass,
        min_disc,
        max_imag,
        worst_mode,
    ) = (
        fc.extrinsic_stability(
            ct2,
            cl2,
        )
    )

    print(
        "FINE_MIN_M2_TO_M40_DISCRIMINANT="
        f"{min_disc:+.15e}"
    )

    print(
        f"FINE_WORST_MODE={worst_mode}"
    )

    print(
        "FINE_MAX_ROOT_IMAG="
        f"{max_imag:.15e}"
    )

    print(
        "FINE_M2_TO_M40_STABILITY="
        f"{'PASS' if stability_pass else 'FAIL'}"
    )

    # ========================================================================
    # Stationarity using selected fine estimate.
    # ========================================================================

    print(
        "\n=== FINE MATCHED STATIONARITY ==="
    )

    selected_mu = (
        GLOBAL_FIXED_JUNCTION_ENERGY
        +
        selected_record[
            "delta_e"
        ]
    )

    print(
        "FINE_SELECTED_GLOBAL_MU_ESTIMATE="
        f"{selected_mu:+.15e}"
    )

    stationarity_results = {}

    for count in (
        1,
        2,
    ):

        case = (
            fc.stationarity(
                selected_mu,
                count,
            )
        )

        stationarity_results[
            count
        ] = case

        print(
            "FINE_STATIONARITY "
            f"JUNCTION_COUNT={count} "
            f"W_EFF={float(case['w_eff']):.15e} "
            f"Q_REQ={float(case.get('q_req', math.nan)):.15e} "
            f"N_REQ={float(case.get('n_req', math.nan)):.15e} "
            f"N_INT={int(case.get('n_integer', 0.0))} "
            f"R_REQ={float(case.get('radius', math.nan)):.15e} "
            f"R_OVER_WALL90={float(case.get('radius_over_wall', math.nan)):.12f} "
            f"R_OVER_CORE={float(case.get('radius_over_core', math.nan)):.12f} "
            f"INTEGER_MISMATCH={float(case.get('mismatch', math.nan)):.15e} "
            f"PASS={'YES' if case['passed'] else 'NO'}"
        )

    one_stationarity = bool(
        stationarity_results[
            1
        ][
            "passed"
        ]
    )

    two_stationarity = bool(
        stationarity_results[
            2
        ][
            "passed"
        ]
    )

    print(
        "FINE_ONE_JUNCTION_STATIONARITY="
        f"{'PASS' if one_stationarity else 'FAIL'}"
    )

    print(
        "FINE_TWO_JUNCTION_STATIONARITY="
        f"{'PASS' if two_stationarity else 'FAIL'}"
    )

    # ========================================================================
    # Decision.
    # ========================================================================

    overall_green = (
        fine_resolution_pass

        and
        full_solver_pass

        and
        base_solver_pass

        and
        resolution_pass

        and
        patch_pass

        and
        termination_pass

        and
        phase_pass

        and
        selected_active_pass

        and
        variational_pass

        and
        eos_pass

        and
        stability_pass

        and
        one_stationarity

        and
        two_stationarity
    )

    print(
        "\n=== 018A-6B2 DECISION ==="
    )

    print(
        "FINE_CORE_RESOLUTION="
        f"{'PASS' if fine_resolution_pass else 'FAIL'}"
    )

    print(
        "FINE_FULL_SOLVERS="
        f"{'PASS' if full_solver_pass else 'FAIL'}"
    )

    print(
        "FINE_BASE_CONTROL_SOLVERS="
        f"{'PASS' if base_solver_pass else 'FAIL'}"
    )

    print(
        "FINE_MATCHED_RESOLUTION_CONVERGENCE="
        f"{'PASS' if resolution_pass else 'FAIL'}"
    )

    print(
        "FINE_MATCHED_PATCH_CONVERGENCE="
        f"{'PASS' if patch_pass else 'FAIL'}"
    )

    print(
        "FINE_WALL_TERMINATION="
        f"{'PASS' if termination_pass else 'FAIL'}"
    )

    print(
        "FINE_RELATIVE_PHASE_LOCKING="
        f"{'PASS' if phase_pass else 'FAIL'}"
    )

    print(
        "FINE_MATCHED_ACTIVE_SOURCE_BUDGET="
        f"{'PASS' if selected_active_pass else 'FAIL'}"
    )

    print(
        "FINE_MATCHED_VARIATIONAL_IDENTITY="
        f"{'PASS' if variational_pass else 'FAIL'}"
    )

    print(
        "FINE_EOS_HEALTH="
        f"{'PASS' if eos_pass else 'FAIL'}"
    )

    print(
        "FINE_M2_TO_M40_STABILITY="
        f"{'PASS' if stability_pass else 'FAIL'}"
    )

    print(
        "FINE_ONE_JUNCTION_STATIONARITY="
        f"{'PASS' if one_stationarity else 'FAIL'}"
    )

    print(
        "FINE_TWO_JUNCTION_STATIONARITY="
        f"{'PASS' if two_stationarity else 'FAIL'}"
    )

    print(
        "018A6B2_FINE_LOCAL_MULTISCALE_FULL_COUPLED_JUNCTION="
        f"{'GREEN' if overall_green else 'RED'}"
    )

    if overall_green:

        print(
            "FULLY_COUPLED_LOCAL_2D_KLS_JUNCTION="
            "SUPPORTED_WITH_FINE_CORE_AND_MATCHED_OUTER_SOLUTION"
        )

        print(
            "018A6B_COARSE_RED_FINAL_INTERPRETATION="
            "NUMERICAL_UNDERRESOLUTION_NOT_PHYSICAL_FAILURE"
        )

        print(
            "NEXT="
            "018A7_COMPLETE_MICROSCOPIC_GRAVITY_CLOSEOUT"
        )

    else:

        print(
            "FULLY_COUPLED_LOCAL_2D_KLS_JUNCTION="
            "NOT_YET_ESTABLISHED"
        )

        print(
            "NEXT="
            "IDENTIFY_FINE_RESOLUTION_OR_PATCH_CHANNEL_FAILURE_BEFORE_GRAVITY"
        )

    print(
        "FINITE_PAYLOAD_GRAVITY_WITH_COMPLETE_NEW_SECTOR="
        "NOT_YET_TESTED"
    )

    print(
        "POSITIVE_TOTAL_ACTIVE_MASS_WITH_COMPLETE_NEW_SECTOR="
        "NOT_YET_TESTED"
    )

    print(
        "FULL_018A_GATE="
        "NOT_YET_GREEN"
    )

    print(
        "018B_FULL_FINITE_THICKNESS_DRUM="
        "NOT_YET_AUTHORIZED"
    )

    print(
        "PRACTICAL_ANTIGRAVITY_DEVICE="
        "NO"
    )

    print(
        "CLAIM_CLASSIFICATION="
        "PROJECT_DERIVED_018A_FINE_LOCAL_MULTISCALE_FULLY_COUPLED_KLS_JUNCTION"
    )

    m.CHI_SELECTED = (
        original_chi
    )


if __name__ == "__main__":
    main()
