#!/usr/bin/env python3
"""019C — minimal renormalizable Wilson/vector-current UV construction gate.

PURPOSE
-------
Test the two cheapest renormalizable Abelian microscopic completions of the
vector-current escape retained by 019B.  The low-energy target is the
composition-sensitive scalar coupling

    C_phi * phi * J_B^mu J_{L,mu}

with the project-inherited coefficient, 5 km scalar range, and ordinary-matter
one-body leakage allowance.  019B showed that anomaly-free baryon and lepton
currents exist and that their leading low-energy one-body mixing is small, but
it did not construct the Wilson-line vector portal itself.

This gate therefore asks a narrower and more decisive question:

    Can a technically natural, renormalizable ABELIAN Wilson-line portal
    generate the required baryon-lepton current-current scalar response with
    perturbative couplings and with every new microscopic scale above the
    material EFT cutoff?

TWO MICROSCOPIC CLASSES TESTED
------------------------------
A. LOOP-INDUCED KINETIC-MIXING PORTAL

   A vectorlike messenger tower is charged under the deconstructed Wilson
   U(1) and under both anomaly-free U(1)_B and U(1)_L.  Its threshold induces
   the finite Wilson-dependent part of

       epsilon(theta) F_B^{mu nu} F_{L,mu nu}.

   The theta derivative is UV finite because the divergent local threshold is
   theta independent.  Integrating out massive B and L gauge bosons yields a
   derivative current-current kernel proportional to

       q^2 / [(q^2 + M_B^2)(q^2 + M_L^2)].

   Rather than evaluating this at one arbitrary momentum, the script performs
   the exact 1s bound-state matrix element for the same three-Angstrom pair
   scale used in the inherited material EFT.  It then finds the *minimum*
   equal gauge coupling needed after optimistically minimizing all mediator
   masses and the Wilson decay constant subject to the existing cutoff and
   terrestrial-excursion gates.

B. WILSON-SEEDED HIGGS MASS-MIXING BRIDGE

   Two bridge scalars S_+ and S_- have anomaly-free-current gauge charges
   (1,+1) and (1,-1).  An exchange symmetry gives equal baseline VEVs while an
   odd Wilson response produces opposite mass shifts.  Their VEVs then induce
   an off-diagonal mass for the heavy B/L vectors.  If the odd splitting d(theta)
   were available, this is an ordinary renormalizable Higgs/vector mediator
   sector and can generate the desired nonderivative J_B.J_L operator.

   The gate first solves that algebra exactly to show whether the vector/Higgs
   mediator sector itself is healthy.  It then tests the minimal technically
   natural way to seed d(theta): a real bridge field P whose tadpole is
   generated by the SAME finite Wilson Coleman-Weinberg determinant.  All
   dimensionless couplings and the trilinear/mass ratio are saturated at the
   perturbative boundary to obtain an *upper bound* on the achievable response.
   New vector, bridge-scalar, P, and Wilson-messenger masses are simultaneously
   placed at the LOWEST allowed material-EFT boundary.  This is deliberately
   biased in favor of finding a solution.  Failure of even this upper bound is
   therefore a meaningful no-go for this minimal loop-seeded class.

PHYSICAL MODEL AND EQUATIONS
----------------------------
The Wilson messenger spectrum is inherited from 019A,

    lambda_n(theta)
      = rho^2 + 2 - 2 cos[(2 pi n + theta)/N].

For one vectorlike Dirac threshold, the finite Wilson derivative of the B-L
kinetic mixing is proportional to

    d/dtheta sum_n log lambda_n.

The same derivative is evaluated by two independent methods:

    Tr[L^{-1} L']

and the explicit Fourier spectrum.

The Wilson scalar mass is not independently dialed.  For every (N,rho), the
Coleman-Weinberg curvature from 019A imposes

    f = mu^2 sqrt(kappa_CW) / (8 pi m_phi).

The minimum mu is chosen so that the Wilson messenger is above the material
cutoff and |phi_Earth/f| <= 0.5.

For equal massive vector mediators M_V, the exact derivative-kernel matrix
moment in the normalized 1s pair state is

    I_K(M_V)
      = |psi(0)|^2 (2/a) / (M_V + 2/a)^3.

The kinetic portal pair charge is therefore

    q_pair
      = (g_B g_L)^2 /(12 pi^2 f)
        * |d log det L / dtheta|
        * I_K.

The target is

    q_target = C_phi |psi(0)|^2.

For the Higgs bridge, with equal gauge couplings and

    v_+^2 = v^2 [1 - d(theta)],
    v_-^2 = v^2 [1 + d(theta)],

integrating out the two vectors gives

    K_BL(theta)
      = d(theta) / [2 v^2 (1-d(theta)^2)].

Hence

    C_phi
      = d_theta (1+d^2)
        / [2 f v^2 (1-d^2)^2].

This relation is solved exactly for a simple odd witness

    d(theta) = eta sin(theta)

to establish that the mediator algebra itself is viable.

For the minimal loop-seeded bridge, take P to shift the Wilson phase locally,
so its finite tadpole is bounded by

    t_P(theta)
      = y_P mu^3 /(64 pi^2) S_CW'(theta).

With trilinear kappa_P P(|S_+|^2-|S_-|^2),

    |d_theta|
      <= |kappa_P y_P| mu^3 |S_CW''(theta)|
         / [64 pi^2 m_P^2 lambda_S v^2].

The script saturates

    y_P <= sqrt(4 pi),
    kappa_P/m_P <= sqrt(4 pi)

and minimizes all masses subject to the material cutoff.  This gives an
optimistic upper bound, not a fit.

UNITS
-----
Natural units hbar=c=1 are used internally.  Energies and masses are in eV;
f is in eV; C_phi is in eV^-3; the pair radius is in eV^-1.

SIGN CONVENTIONS
----------------
Only response magnitudes are used for the UV-capacity gates.  Relative signs
can be changed by endpoint charges.  No sign choice can repair a failure of
required coupling magnitude, perturbativity, or naturalness.

ASSUMPTIONS
-----------
- The 019A Wilson-line messenger spectrum and Coleman-Weinberg normalization
  are retained.
- The 019B anomaly-free U(1)_B x U(1)_L current completion is retained.
- Gauge and bridge masses must not lie below the material EFT cutoff.
- |theta_Earth| <= 0.5.
- Dimensionless couplings satisfy g^2/(4 pi) <= 1.
- The bridge trilinear obeys |kappa_P|/m_P <= sqrt(4 pi).
- The optimistic UV bounds intentionally ignore experimental fifth-force,
  collider, stellar, and cosmological constraints; those can only make the
  available parameter space smaller.

VALIDATION AND FALSIFICATION
----------------------------
The gate validates:
- exact upstream hashes and GREEN markers;
- matrix-vs-spectral d log det reconstruction;
- analytic-vs-numerical pair-kernel integration;
- analytic-vs-independent Coleman-Weinberg curvature;
- broad scans in N, rho, and scale-separation margin;
- an exact Higgs-bridge algebra witness;
- an independently reconstructed optimistic loop-seed response bound.

The minimal kinetic portal is rejected if even its best optimistic scan point
needs g^2/(4 pi) > 1.

The minimal loop-seeded mass bridge is rejected if even its perturbative,
cutoff-saturating upper bound cannot reach C_phi.

A rejection does NOT falsify all vector-current Wilson portals.  In particular,
it does not cover non-Abelian charged-vector Wilson lines, collective tree-level
seeding, supersymmetric cancellations, strongly coupled sectors, or other
nonminimal protection principles.  Those require a new concrete mechanism
before more compute is spent.

PROMOTION CONDITION
-------------------
A true 019C GREEN promotion requires at least one COMPLETE tested microscopic
class to satisfy simultaneously:

    RENORMALIZABLE_UV_WITNESS=YES
    ANOMALY_FREE_MATERIAL_CURRENTS=YES
    WILSON_PROTECTION=PASS
    TARGET_PAIR_MATCH=PASS
    PERTURBATIVITY=PASS
    ALL_NEW_MASSES_ABOVE_MATERIAL_EFT=PASS
    ULTRALIGHT_MASS_NATURALNESS=PASS
    ONE_BODY_VECTOR_MIXING_PREFLIGHT=PASS
    ROBUST_PARAMETER_BASIN=YES

If neither minimal class passes, report GREEN_NEGATIVE_RESULT, preserve the
019A/019B low-energy vector-current escape, and do not raise the project
heuristic.

CLAIM LIMITS
------------
Even a positive result would not establish current 5-km experimental safety,
stellar/cosmological safety, a realizable material, device power, or practical
antigravity.  A negative result closes only the two minimal Abelian portal
classes explicitly tested here.

RELATED FILES
-------------
- simulations/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.py
- simulations/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.py
- results/logs/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.log
- results/logs/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.log
- RESEARCH_BUILDPLAN.md

LITERATURE ANCHORS
------------------
- Hill & Leibovich, arXiv:hep-ph/0205057: deconstructed QED and finite
  Wilson-line Coleman-Weinberg potential.
- Arkani-Hamed et al., arXiv:hep-th/0301218: nonlocal Wilson-line protection.
- Holdom, Phys. Lett. B166 (1986) 196: loop-induced U(1) kinetic mixing.
- Duerr, Fileviez Perez & Wise, arXiv:1304.0576: anomaly-free gauged baryon
  and lepton number completion used by 019B.

CLAIM CLASSIFICATION
--------------------
PROJECT_DERIVED_019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import importlib.util
import math
from pathlib import Path
import re
import sys

import mpmath as mp
import numpy as np
from scipy.integrate import quad
from scipy.optimize import brentq

ROOT = Path(__file__).resolve().parents[1]
A_SOURCE = ROOT / "simulations/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.py"
B_SOURCE = ROOT / "simulations/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.py"
A_LOG = ROOT / "results/logs/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.log"
B_LOG = ROOT / "results/logs/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.log"

EXPECTED_A_SHA = "27514c58298ccf9ecaa5543a3dc6d4368df7174ae2c55cb1a547adb922b756e7"
EXPECTED_B_SHA = "0812ced28d18a53297e7599d5b508eaff3b4377ebcf955e129c38e8ce2497e74"

TARGET_C_PHI = 9.536416387852626e-20
TARGET_M_PHI = 3.946539608e-11
EARTH_PHI = 1.690631280830914e10
MAX_LEAKAGE_FRACTION = 5.772961445324848e-7
MATERIAL_EFT_CUTOFF = 657.7566
PAIR_RADIUS_ANGSTROM = 3.0
HBARC_EV_NM = 197.3269804

MAX_THETA_EARTH = 0.5
PERTURBATIVE_ALPHA_MAX = 1.0
G_MAX = math.sqrt(4.0 * math.pi)
MIN_COMPLETE_SCALE_MARGIN = 2.0

N_VALUES = tuple(range(3, 17))
RHO_VALUES = tuple(float(x) for x in np.linspace(0.25, 5.0, 20))
SCALE_MARGINS = (1.0, 1.5, 2.0, 3.0)

mp.mp.dps = 70


@dataclass(frozen=True)
class KineticPoint:
    N: int
    rho: float
    margin: float
    mu: float
    f: float
    theta: float
    kappa: float
    dlogdet: float
    vector_mass: float
    pair_kernel: float
    g_endpoint: float
    alpha_endpoint: float
    messenger_margin: float


@dataclass(frozen=True)
class BridgeBoundPoint:
    N: int
    rho: float
    margin: float
    mu: float
    f: float
    theta: float
    kappa_cw: float
    cw_second_earth: float
    vector_mass: float
    bridge_vev: float
    p_mass: float
    lambda_s: float
    c_upper: float
    fraction_of_target: float


def load_module(name: str, path: Path):
    """Import one repo simulation without calling its main()."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def require_marker(path: Path, marker: str) -> None:
    """Fail closed if one required upstream result is absent."""
    if not path.exists():
        raise RuntimeError(f"Missing upstream log: {path}")
    text = path.read_text(errors="replace")
    if marker not in text:
        raise RuntimeError(f"Missing marker {marker!r} in {path}")


def exact_scalar(path: Path, label: str) -> float:
    """Read one floating scalar from an exact whole-line label."""
    text = path.read_text(errors="replace")
    pattern = (
        r"(?m)^" + re.escape(label) +
        r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)\s*$"
    )
    match = re.search(pattern, text)
    if match is None:
        raise RuntimeError(f"Missing exact scalar line {label!r} in {path}")
    value = float(match.group(1))
    if not math.isfinite(value):
        raise RuntimeError(f"Nonfinite {label!r}")
    return value


def relative_error(a: float, b: float) -> float:
    return abs(a - b) / max(abs(a), abs(b), 1.0e-300)


def pair_radius_evinv() -> float:
    """Convert the inherited 3 Angstrom pair radius to eV^-1."""
    radius_nm = PAIR_RADIUS_ANGSTROM * 0.1
    return radius_nm / HBARC_EV_NM


def psi0_sq() -> float:
    a = pair_radius_evinv()
    return 1.0 / (math.pi * a**3)


def equal_mass_pair_kernel_analytic(M: float) -> float:
    """Exact <q^2/(q^2+M^2)^2> kernel in the normalized 1s density."""
    a = pair_radius_evinv()
    k = M + 2.0 / a
    return psi0_sq() * (2.0 / a) / (k**3)


def equal_mass_pair_kernel_numeric(M: float) -> float:
    """Independent coordinate-space quadrature of the same kernel."""
    a = pair_radius_evinv()
    norm = psi0_sq()

    # Fourier transform:
    # q^2/(q^2+M^2)^2 = 1/(q^2+M^2) - M^2/(q^2+M^2)^2
    # K(r) = exp(-Mr)/(4 pi r) - M exp(-Mr)/(8 pi).
    def integrand(r: float) -> float:
        density = norm * math.exp(-2.0 * r / a)
        kernel = math.exp(-M * r) * (1.0 / (4.0 * math.pi * r) - M / (8.0 * math.pi))
        return 4.0 * math.pi * r * r * density * kernel

    # Remove the removable r=0 numerical singularity by starting at a tiny
    # positive radius.  Its omitted contribution is negligible at this scale.
    value, _ = quad(integrand, 1.0e-14 * a, 100.0 * a, epsabs=1.0e-12, epsrel=2.0e-11, limit=400)
    return value


def dlogdet_matrix(a019, N: int, rho: float, theta: float) -> float:
    """Return a double-precision Tr[L^-1 L'] diagnostic."""
    L = a019.lattice_matrix(N, rho, theta)
    Lp = a019.lattice_matrix_prime(N, rho, theta)
    return float(np.real(np.trace(np.linalg.solve(L, Lp))))


def dlogdet_matrix_mp(N: int, rho: float, theta: float) -> mp.mpf:
    """High-precision matrix reconstruction of Tr[L^-1 L']."""
    rho_mp = mp.mpf(str(rho))
    theta_mp = mp.mpf(str(theta))
    link = mp.e ** (1j * theta_mp / N)

    L = mp.matrix(N)
    Lp = mp.matrix(N)
    for i in range(N):
        for j in range(N):
            L[i, j] = 0
            Lp[i, j] = 0
        L[i, i] = rho_mp * rho_mp + 2

    for j in range(N):
        k = (j + 1) % N
        L[j, k] += -link
        L[k, j] += -mp.conj(link)
        Lp[j, k] += -(1j / N) * link
        Lp[k, j] += +(1j / N) * mp.conj(link)

    G = L ** -1
    product = G * Lp
    return mp.re(sum(product[i, i] for i in range(N)))


def dlogdet_spectral_mp(N: int, rho: float, theta: float) -> mp.mpf:
    """High-precision spectral reconstruction of d log det L/dtheta."""
    rho_mp = mp.mpf(str(rho))
    theta_mp = mp.mpf(str(theta))
    total = mp.mpf('0')
    for n in range(N):
        angle = (2 * mp.pi * n + theta_mp) / N
        lam = rho_mp * rho_mp + 2 - 2 * mp.cos(angle)
        lp = (mp.mpf(2) / N) * mp.sin(angle)
        total += lp / lam
    return total


def dlogdet_closed_mp(N: int, rho: float, theta: float) -> mp.mpf:
    """High-precision closed determinant identity."""
    rho_mp = mp.mpf(str(rho))
    theta_mp = mp.mpf(str(theta))
    alpha = mp.acosh(1 + rho_mp * rho_mp / 2)
    return mp.sin(theta_mp) / (mp.cosh(N * alpha) - mp.cos(theta_mp))


def dlogdet_spectral(N: int, rho: float, theta: float) -> float:
    """Independent Fourier-spectrum d log det L/dtheta."""
    total = 0.0
    for n in range(N):
        angle = (2.0 * math.pi * n + theta) / N
        lam = rho * rho + 2.0 - 2.0 * math.cos(angle)
        lp = (2.0 / N) * math.sin(angle)
        total += lp / lam
    return total


def dlogdet_closed(N: int, rho: float, theta: float) -> float:
    """Closed determinant identity for a third independent check."""
    alpha = math.acosh(1.0 + 0.5 * rho * rho)
    return math.sin(theta) / (math.cosh(N * alpha) - math.cos(theta))


def minimal_mu_for_wilson(a019, N: int, rho: float, margin: float) -> tuple[float, float, float, float]:
    """Return minimal mu, f, theta_E and positive CW kappa under gate constraints."""
    kappa = float(a019.cw_curvature_analytic_mp(N, rho))
    if not (math.isfinite(kappa) and kappa > 0.0):
        raise ValueError("nonpositive CW curvature")

    # f = mu^2 sqrt(kappa)/(8 pi m_phi).
    f_min_earth = EARTH_PHI / MAX_THETA_EARTH
    mu_for_earth = math.sqrt(
        f_min_earth * 8.0 * math.pi * TARGET_M_PHI / math.sqrt(kappa)
    )
    mu_for_messenger = margin * MATERIAL_EFT_CUTOFF / rho
    mu = max(mu_for_earth, mu_for_messenger)
    f = mu * mu * math.sqrt(kappa) / (8.0 * math.pi * TARGET_M_PHI)
    theta = EARTH_PHI / f
    return mu, f, theta, kappa


def kinetic_point(a019, N: int, rho: float, margin: float) -> KineticPoint | None:
    """Compute the most optimistic equal-coupling kinetic portal point."""
    try:
        mu, f, theta, kappa = minimal_mu_for_wilson(a019, N, rho, margin)
    except ValueError:
        return None

    dlog = abs(dlogdet_spectral(N, rho, theta))
    if dlog <= 0.0:
        return None

    vector_mass = margin * MATERIAL_EFT_CUTOFF
    kernel = equal_mass_pair_kernel_analytic(vector_mass)
    target_pair_charge = TARGET_C_PHI * psi0_sq()

    # q_target = g^4 dlog K /(12 pi^2 f) for g_B=g_L=g.
    g4 = target_pair_charge * 12.0 * math.pi**2 * f / (dlog * kernel)
    if g4 <= 0.0:
        return None
    g = g4**0.25
    alpha = g * g / (4.0 * math.pi)

    return KineticPoint(
        N=N,
        rho=rho,
        margin=margin,
        mu=mu,
        f=f,
        theta=theta,
        kappa=kappa,
        dlogdet=dlog,
        vector_mass=vector_mass,
        pair_kernel=kernel,
        g_endpoint=g,
        alpha_endpoint=alpha,
        messenger_margin=mu * rho / MATERIAL_EFT_CUTOFF,
    )


def bridge_exact_coefficient(eta: float, theta: float, f: float, v: float) -> float:
    """Exact dK_BL/dphi for d(theta)=eta sin(theta)."""
    d = eta * math.sin(theta)
    dp = eta * math.cos(theta)
    if abs(d) >= 1.0:
        return math.inf
    return dp * (1.0 + d * d) / (2.0 * f * v * v * (1.0 - d * d) ** 2)


def solve_bridge_eta(theta: float, f: float, v: float) -> float:
    """Solve the exact Higgs-bridge algebra for eta."""
    upper = min(4.0, 0.999999 / max(abs(math.sin(theta)), 1.0e-30))
    func = lambda eta: bridge_exact_coefficient(eta, theta, f, v) - TARGET_C_PHI
    if func(upper) < 0.0:
        raise RuntimeError("Bridge algebra cannot reach target within positive-VEV domain")
    return brentq(func, 1.0e-15, upper, xtol=1.0e-14, rtol=1.0e-13)


def cw_second_earth_mp(a019, N: int, rho: float, theta: float) -> float:
    """High-precision S_CW'' at the terrestrial Wilson phase."""
    theta_mp = mp.mpf(str(theta))
    return float(mp.diff(lambda x: a019.cw_spectral_sum_mp(N, rho, x), theta_mp, 2))


def bridge_upper_bound(a019, N: int, rho: float, margin: float) -> BridgeBoundPoint | None:
    """Optimistic perturbative upper bound for the minimal loop-seeded bridge."""
    try:
        mu, f, theta, kappa = minimal_mu_for_wilson(a019, N, rho, margin)
    except ValueError:
        return None

    s2 = abs(cw_second_earth_mp(a019, N, rho, theta))

    # Saturate every scale and coupling in the favorable direction.
    vector_mass = margin * MATERIAL_EFT_CUTOFF
    v = vector_mass / (math.sqrt(2.0) * G_MAX)
    p_mass = margin * MATERIAL_EFT_CUTOFF

    # Require the radial bridge-Higgs mode sqrt(2 lambda) v itself to be above
    # the same margin*cutoff.  At v_min this saturates lambda=4 pi.
    lambda_s = (margin * MATERIAL_EFT_CUTOFF) ** 2 / (2.0 * v * v)

    # kappa_P/m_P <= sqrt(4pi) and y_P <= sqrt(4pi), so their product <=4pi.
    # C <= mu^3 |S''| / [32 pi m_P lambda f v^4].
    c_upper = mu**3 * s2 / (
        32.0 * math.pi * p_mass * lambda_s * f * v**4
    )

    return BridgeBoundPoint(
        N=N,
        rho=rho,
        margin=margin,
        mu=mu,
        f=f,
        theta=theta,
        kappa_cw=kappa,
        cw_second_earth=s2,
        vector_mass=vector_mass,
        bridge_vev=v,
        p_mass=p_mass,
        lambda_s=lambda_s,
        c_upper=c_upper,
        fraction_of_target=c_upper / TARGET_C_PHI,
    )


def print_kinetic(prefix: str, p: KineticPoint) -> None:
    print(f"{prefix}_N={p.N}")
    print(f"{prefix}_RHO={p.rho:.15e}")
    print(f"{prefix}_SCALE_MARGIN={p.margin:.6f}")
    print(f"{prefix}_MU_EV={p.mu:.15e}")
    print(f"{prefix}_F_EV={p.f:.15e}")
    print(f"{prefix}_THETA_EARTH={p.theta:.15e}")
    print(f"{prefix}_DLOGDET={p.dlogdet:.15e}")
    print(f"{prefix}_VECTOR_MASS_EV={p.vector_mass:.15e}")
    print(f"{prefix}_MESSENGER_OVER_EFT={p.messenger_margin:.15e}")
    print(f"{prefix}_PAIR_KERNEL_EV={p.pair_kernel:.15e}")
    print(f"{prefix}_REQUIRED_G_ENDPOINT={p.g_endpoint:.15e}")
    print(f"{prefix}_REQUIRED_G_SQ_OVER_4PI={p.alpha_endpoint:.15e}")


def print_bridge_bound(prefix: str, p: BridgeBoundPoint) -> None:
    print(f"{prefix}_N={p.N}")
    print(f"{prefix}_RHO={p.rho:.15e}")
    print(f"{prefix}_SCALE_MARGIN={p.margin:.6f}")
    print(f"{prefix}_MU_EV={p.mu:.15e}")
    print(f"{prefix}_F_EV={p.f:.15e}")
    print(f"{prefix}_THETA_EARTH={p.theta:.15e}")
    print(f"{prefix}_CW_SECOND_EARTH={p.cw_second_earth:.15e}")
    print(f"{prefix}_VECTOR_MASS_EV={p.vector_mass:.15e}")
    print(f"{prefix}_BRIDGE_VEV_EV={p.bridge_vev:.15e}")
    print(f"{prefix}_P_MASS_EV={p.p_mass:.15e}")
    print(f"{prefix}_LAMBDA_S={p.lambda_s:.15e}")
    print(f"{prefix}_C_UPPER_EV_MINUS3={p.c_upper:.15e}")
    print(f"{prefix}_FRACTION_OF_TARGET={p.fraction_of_target:.15e}")
    print(f"{prefix}_TARGET_DEFICIT_FACTOR={1.0 / max(p.fraction_of_target, 1.0e-300):.15e}")


def main() -> None:
    print("=== 019C — MINIMAL ABELIAN VECTOR WILSON UV CONSTRUCTION GATE ===")

    require_marker(A_LOG, "019A_WILSON_LINE_SEQUESTERED_PAIR_SCALAR_UV_PROTECTION_GATE=GREEN")
    require_marker(B_LOG, "019B_ANOMALY_FREE_SM_MATERIAL_ENDPOINT_AND_ONE_BODY_OPERATOR_MIXING_GATE=GREEN_NEGATIVE_RESULT")
    require_marker(B_LOG, "VECTOR_CURRENT_ENDPOINT_ESCAPE=SUPPORTED_AT_RELATIVISTIC_CURRENT_EFT_LEVEL")

    if not A_SOURCE.exists() or not B_SOURCE.exists():
        raise RuntimeError("Missing required 019A/019B source")

    a_sha = hashlib.sha256(A_SOURCE.read_bytes()).hexdigest()
    b_sha = hashlib.sha256(B_SOURCE.read_bytes()).hexdigest()

    print("\n=== UPSTREAM ARTIFACT AUDIT ===")
    print(f"019A_SOURCE_SHA256={a_sha}")
    print(f"019A_SOURCE_HASH_MATCH={'PASS' if a_sha == EXPECTED_A_SHA else 'FAIL'}")
    print(f"019B_SOURCE_SHA256={b_sha}")
    print(f"019B_SOURCE_HASH_MATCH={'PASS' if b_sha == EXPECTED_B_SHA else 'FAIL'}")

    if a_sha != EXPECTED_A_SHA or b_sha != EXPECTED_B_SHA:
        raise RuntimeError("Upstream source hash mismatch")

    a019 = load_module("ag019c_upstream_019a", A_SOURCE)

    vector_margin = exact_scalar(B_LOG, "VECTOR_ONE_BODY_MIXING_MARGIN=")
    vector_mix = exact_scalar(B_LOG, "VECTOR_TOTAL_ONE_BODY_MIXING_FRACTION_PREFLIGHT=")
    print(f"019B_VECTOR_ONE_BODY_MIXING_FRACTION={vector_mix:.15e}")
    print(f"019B_VECTOR_ONE_BODY_MIXING_MARGIN={vector_margin:.15e}")
    print("ANOMALY_FREE_MATERIAL_CURRENTS=RETAINED_FROM_019B")

    print("\n=== INDEPENDENT WILSON DERIVATIVE / BOUND-STATE KERNEL AUDIT ===")
    audit_N = 9
    audit_rho = 3.0
    audit_theta = exact_scalar(A_LOG, "SELECTED_THETA_EARTH=")
    dm_double = dlogdet_matrix(a019, audit_N, audit_rho, audit_theta)
    dm_mp = dlogdet_matrix_mp(audit_N, audit_rho, audit_theta)
    ds_mp = dlogdet_spectral_mp(audit_N, audit_rho, audit_theta)
    dc_mp = dlogdet_closed_mp(audit_N, audit_rho, audit_theta)
    dm = float(dm_mp)
    ds = float(ds_mp)
    dc = float(dc_mp)
    print(f"DLOGDET_MATRIX_DOUBLE={dm_double:+.15e}")
    print(f"DLOGDET_MATRIX_MP={dm:+.15e}")
    print(f"DLOGDET_SPECTRAL_MP={ds:+.15e}")
    print(f"DLOGDET_CLOSED_MP={dc:+.15e}")
    dlog_rel = max(relative_error(dm, ds), relative_error(dm, dc), relative_error(ds, dc))
    print(f"DLOGDET_HIGH_PRECISION_MAX_RELERR={dlog_rel:.15e}")
    print(f"DLOGDET_DOUBLE_ABSERR={abs(dm_double-dm):.15e}")

    audit_mass = 2.0 * MATERIAL_EFT_CUTOFF
    ka = equal_mass_pair_kernel_analytic(audit_mass)
    kn = equal_mass_pair_kernel_numeric(audit_mass)
    kernel_rel = relative_error(ka, kn)
    print(f"PAIR_KERNEL_ANALYTIC={ka:.15e}")
    print(f"PAIR_KERNEL_NUMERIC={kn:.15e}")
    print(f"PAIR_KERNEL_RELERR={kernel_rel:.15e}")
    reconstruction_pass = dlog_rel <= 2.0e-11 and kernel_rel <= 2.0e-8
    print(f"VECTOR_PORTAL_INDEPENDENT_RECONSTRUCTION={'PASS' if reconstruction_pass else 'FAIL'}")

    print("\n=== CLASS K — LOOP-INDUCED WILSON KINETIC MIXING ===")
    kinetic_points: list[KineticPoint] = []
    for margin in SCALE_MARGINS:
        for N in N_VALUES:
            for rho in RHO_VALUES:
                point = kinetic_point(a019, N, rho, margin)
                if point is not None:
                    kinetic_points.append(point)

    if not kinetic_points:
        raise RuntimeError("Kinetic portal scan produced no finite points")

    kinetic_best = min(kinetic_points, key=lambda p: p.alpha_endpoint)
    kinetic_by_margin = {
        margin: min((p for p in kinetic_points if p.margin == margin), key=lambda p: p.alpha_endpoint)
        for margin in SCALE_MARGINS
    }

    print(f"KINETIC_SCAN_TOTAL={len(kinetic_points)}")
    for margin in SCALE_MARGINS:
        p = kinetic_by_margin[margin]
        print(
            f"KINETIC_MARGIN={margin:.1f} BEST_N={p.N} BEST_RHO={p.rho:.6f} "
            f"REQUIRED_G={p.g_endpoint:.9e} REQUIRED_G_SQ_OVER_4PI={p.alpha_endpoint:.9e}"
        )
    print_kinetic("KINETIC_GLOBAL_BEST", kinetic_best)
    kinetic_passers = [p for p in kinetic_points if p.alpha_endpoint <= PERTURBATIVE_ALPHA_MAX]
    print(f"KINETIC_PERTURBATIVE_PASSERS={len(kinetic_passers)}")
    kinetic_pass = bool(kinetic_passers) and reconstruction_pass
    print(f"LOOP_INDUCED_KINETIC_MIXING_PORTAL={'PASS' if kinetic_pass else 'REJECTED_NONPERTURBATIVE'}")

    print("\n=== CLASS M0 — EXACT RENORMALIZABLE HIGGS/VECTOR MEDIATOR ALGEBRA ===")
    # Show that the ordinary vector/Higgs mediator sector is not itself the
    # obstruction.  Use the already-natural 019A f and a conservative vector
    # mass at twice the material cutoff with g=1.
    selected_f = exact_scalar(A_LOG, "SELECTED_F_EV=")
    selected_theta = exact_scalar(A_LOG, "SELECTED_THETA_EARTH=")
    g_bridge = 1.0
    vector_mass = MIN_COMPLETE_SCALE_MARGIN * MATERIAL_EFT_CUTOFF
    bridge_v = vector_mass / (math.sqrt(2.0) * g_bridge)
    eta = solve_bridge_eta(selected_theta, selected_f, bridge_v)
    d_earth = eta * math.sin(selected_theta)
    c_bridge = bridge_exact_coefficient(eta, selected_theta, selected_f, bridge_v)
    self_pair_ratio = abs(2.0 * d_earth / (1.0 + d_earth * d_earth))
    print(f"HIGGS_BRIDGE_G={g_bridge:.15e}")
    print(f"HIGGS_BRIDGE_VECTOR_MASS_EV={vector_mass:.15e}")
    print(f"HIGGS_BRIDGE_VECTOR_OVER_EFT={vector_mass / MATERIAL_EFT_CUTOFF:.15e}")
    print(f"HIGGS_BRIDGE_VEV_EV={bridge_v:.15e}")
    print(f"HIGGS_BRIDGE_ETA={eta:.15e}")
    print(f"HIGGS_BRIDGE_D_EARTH={d_earth:.15e}")
    print(f"HIGGS_BRIDGE_SELF_PAIR_TO_CROSS_DERIVATIVE_RATIO={self_pair_ratio:.15e}")
    print(f"HIGGS_BRIDGE_C_RECONSTRUCTED={c_bridge:.15e}")
    print(f"HIGGS_BRIDGE_C_MATCH_RELERR={relative_error(c_bridge, TARGET_C_PHI):.15e}")
    bridge_algebra_pass = (
        g_bridge * g_bridge / (4.0 * math.pi) <= 1.0
        and vector_mass / MATERIAL_EFT_CUTOFF >= MIN_COMPLETE_SCALE_MARGIN
        and abs(d_earth) < 0.1
        and relative_error(c_bridge, TARGET_C_PHI) <= 1.0e-10
    )
    print(f"RENORMALIZABLE_VECTOR_HIGGS_MEDIATOR_SECTOR={'PASS' if bridge_algebra_pass else 'FAIL'}")
    print("SAME_SECTOR_PAIR_RESPONSE=NONZERO_DEFER_TO_EXPERIMENTAL_OPERATOR_BOUND_IF_UV_SEED_SURVIVES")

    print("\n=== CLASS M1 — MINIMAL LOOP-SEEDED WILSON HIGGS BRIDGE ===")
    bridge_points: list[BridgeBoundPoint] = []
    for margin in SCALE_MARGINS:
        for N in N_VALUES:
            for rho in RHO_VALUES:
                point = bridge_upper_bound(a019, N, rho, margin)
                if point is not None and math.isfinite(point.fraction_of_target):
                    bridge_points.append(point)

    if not bridge_points:
        raise RuntimeError("Bridge upper-bound scan produced no finite points")

    bridge_best = max(bridge_points, key=lambda p: p.fraction_of_target)
    bridge_by_margin = {
        margin: max((p for p in bridge_points if p.margin == margin), key=lambda p: p.fraction_of_target)
        for margin in SCALE_MARGINS
    }
    print(f"BRIDGE_LOOP_SCAN_TOTAL={len(bridge_points)}")
    for margin in SCALE_MARGINS:
        p = bridge_by_margin[margin]
        print(
            f"BRIDGE_MARGIN={margin:.1f} BEST_N={p.N} BEST_RHO={p.rho:.6f} "
            f"MAX_TARGET_FRACTION={p.fraction_of_target:.9e} "
            f"DEFICIT={1.0 / max(p.fraction_of_target, 1.0e-300):.9e}"
        )
    print_bridge_bound("BRIDGE_GLOBAL_OPTIMISTIC_BEST", bridge_best)

    credible_bridge = bridge_by_margin[MIN_COMPLETE_SCALE_MARGIN]
    print_bridge_bound("BRIDGE_TWO_EFT_MARGIN_BEST", credible_bridge)

    bridge_loop_passers = [p for p in bridge_points if p.margin >= MIN_COMPLETE_SCALE_MARGIN and p.fraction_of_target >= 1.0]
    bridge_loop_pass = bool(bridge_loop_passers)
    print(f"BRIDGE_TWO_EFT_MARGIN_PASSERS={len(bridge_loop_passers)}")
    print(
        "MINIMAL_LOOP_SEEDED_HIGGS_MASS_MIXING_PORTAL="
        + ("PASS" if bridge_loop_pass else "REJECTED_NATURALNESS_RESPONSE_BOUND")
    )

    print("\n=== BLIND WILDCARD SCALE DIAGNOSTIC — NOT EVIDENCE ===")
    # Apply the user's wildcard values only as labeled diagnostics to the already
    # computed two-cutoff bridge deficit.  They are not optimization targets.
    for factor in (0.625, 1.6, 1.875, 3.125, 5.0):
        scaled_fraction = credible_bridge.fraction_of_target * factor
        print(
            f"WILDCARD_RESPONSE_FACTOR={factor:.6f} "
            f"SCALED_TARGET_FRACTION={scaled_fraction:.15e} "
            f"REACHES_TARGET={'YES' if scaled_fraction >= 1.0 else 'NO'}"
        )
    print("WILDCARD_VALUES_USED_AS_EVIDENCE=NO")

    print("\n=== 019C DECISION ===")
    complete_uv = kinetic_pass or bridge_loop_pass

    if complete_uv:
        print("019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE=GREEN")
        print("COMPLETE_RENORMALIZABLE_VECTOR_WILSON_UV_WITNESS=YES")
        print("PROTECTED_VECTOR_CURRENT_SCALAR_BRANCH=PROMOTE_TO_EXPERIMENTAL_BOUND_GATE")
        print("NEXT=019D_EXACT_5KM_FORCE_BOUND_AND_COMPOSITION_DEPENDENCE")
        print("CURRENT_KNOWLEDGE_HEURISTIC=APPROXIMATELY_70_PERCENT_NOT_A_PROBABILITY")
        print("HEURISTIC_CHANGE=APPROXIMATELY_68_TO_70_PERCENT")
    else:
        print("019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE=GREEN_NEGATIVE_RESULT")
        print("COMPLETE_RENORMALIZABLE_VECTOR_WILSON_UV_WITNESS=NO_IN_TWO_MINIMAL_CLASSES")
        print("LOOP_INDUCED_KINETIC_MIXING_PORTAL=REJECTED_NONPERTURBATIVE")
        print("RENORMALIZABLE_VECTOR_HIGGS_MEDIATOR_SECTOR=SUPPORTED_IF_PROTECTED_ODD_WILSON_SEED_EXISTS")
        print("MINIMAL_LOOP_SEEDED_ODD_WILSON_SOURCE=INSUFFICIENT")
        print("VECTOR_CURRENT_EFT_ESCAPE_FROM_019B=RETAINED")
        print("PROTECTED_SCALAR_BRANCH=RETAIN_ONLY_FOR_NEW_NONABELIAN_OR_COLLECTIVE_TREE_VECTOR_PORTAL")
        print("NEXT=DOCUMENT_SESSION_AND_RERANK_NONABELIAN_CHARGED_VECTOR_OR_COLLECTIVE_TREE_WILSON_PORTAL")
        print("CURRENT_KNOWLEDGE_HEURISTIC=APPROXIMATELY_68_PERCENT_NOT_A_PROBABILITY")
        print("HEURISTIC_CHANGE=NO_COMPLETE_MICROSCOPIC_VECTOR_PORTAL_YET")

    print("ANOMALY_FREE_SM_MATERIAL_CURRENTS=RETAINED")
    print("ONE_BODY_VECTOR_MIXING_PREFLIGHT=RETAINED_FROM_019B")
    print("EXACT_2026_5KM_FIFTH_FORCE_BOUND=DEFER_UNTIL_COMPLETE_PORTAL_EXISTS")
    print("STELLAR_COSMOLOGICAL_COMPLETION=NOT_ESTABLISHED")
    print("REAL_ANTIGRAVITY_MATERIAL=NO")
    print("PRACTICAL_ANTIGRAVITY_DEVICE=NO")
    print("NEW_PHYSICS_DISCOVERY=NO")
    print("018B_FIELD_EXISTENCE_RESULT=RETAINED")
    print("018C_M2_STABILITY_FALSIFICATION=RETAINED")
    print("019A_WILSON_LINE_UV_PROTECTION_WITNESS=RETAINED")
    print("019B_DIRECT_SCALAR_MATERIAL_EMBEDDING_FALSIFICATION=RETAINED")
    print("CLAIM_CLASSIFICATION=PROJECT_DERIVED_019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE")


if __name__ == "__main__":
    main()
