#!/usr/bin/env python3
"""020A2R — exact B/L running and high-precision global naturalness closeout.

PURPOSE
-------
Close the remaining ambiguity left by 020A2 before either preserving or
globally reranking the protected Wilson/vector-current branch.

020A2 established a real positive structural result:

    SU(2)_X x U(1)_B x U(1)_L

admits a renormalizable 5x5 heavy-vector mass matrix that is exactly
isospectral in the symmetric B <-> L limit while its fixed-current
[M^-2]_{BL} kernel responds to the physical SU(2) relative orientation.

020A2 also found severe sensitivity to B/L exchange breaking, but its broad
double-precision naturalness scan ranked points using a numerically delicate
finite-difference estimator.  The single high-precision reconstruction was
therefore insufficient to prove that no other point in the scanned region has
a substantially larger allowed B/L splitting.

This run fixes that issue and replaces the earlier generic loop proxy with a
physical, model-specific lower bound.

ACTIVE SCIENTIFIC QUESTION
--------------------------
Across the complete perturbative 020A2 target-matching grid:

1. what is the true high-precision envelope for the allowed exchange-breaking
   parameter epsilon in

       g_B = g (1 + epsilon)
       g_L = g (1 - epsilon)

   imposed by

       |delta m_phi^2| <= m_phi^2

   using the finite one-loop vector Coleman-Weinberg potential?

2. is that allowed epsilon smaller than an unavoidable differential U(1)_L
   running effect already generated by the ordinary 019B lepton endpoint?

If yes by a robust margin, the minimal collective-tree / small-SU(2) portal
class is physically closed by radiative naturalness and the buildplan requires
global reranking rather than a larger quiver.

UPSTREAM MODEL
--------------
The run imports, rather than reimplements:

- the exact 019B anomaly-free B/L Weyl-field table;
- the complete 020A2 5x5 vector mass matrix;
- the 020A2 target-C_phi matching equations;
- the 020A2 high-precision Coleman-Weinberg evaluator.

This minimizes scientific drift between gates.

ONE-LOOP U(1) RUNNING
---------------------
For a U(1) gauge coupling in a theory containing left-handed Weyl fermions,

    d g / d ln(mu)
      = b g^3 / (16 pi^2)

with the fermion contribution

    b_f
      = (2/3) sum_weyl q_f^2.

The exact 019B N=1 anomaly-free fermion table gives independent sums for
baryon and lepton charge.  Those sums are reconstructed from the source.

The decisive low-energy floor does NOT use the full UV coefficient.

Instead, it deliberately keeps only ONE light Weyl state with lepton charge
|L|=1 and no baryon charge.  This gives the minimal differential coefficient

    Delta b_min
      = 2/3.

This is intentionally more favorable to the portal than the actual 019B
ordinary-matter endpoint, which contains three active left-handed neutrino
states.  The corresponding three-Weyl coefficient

    Delta b_3nu
      = 2

is reported separately but is not required for rejection.

WHY THIS IS AN UNAVOIDABLE FLOOR
--------------------------------
The heavy vectors in every tested point are at keV-scale masses, whereas the
ordinary light neutrino states in the 019B lepton-number endpoint lie far below
that window.

A single constant counterterm can make g_B and g_L equal at one chosen scale,
but it cannot remove the DIFFERENT MOMENTUM/RG SLOPE across the complete
heavy-vector threshold interval [M_min, M_max].

To give the model maximum freedom, the code analytically optimizes the
normalization of g_L so that the maximum mismatch at the two ends of the
interval is minimized.

Take g_B = g constant for the deliberately minimal differential contribution.
For

    k
      = Delta b/(8 pi^2) ln(M_max/M_min),

one-loop running gives

    1/g_L(M_max)^2
      =
    1/g_L(M_min)^2 - k.

The minimax counterterm choice obeys

    g_L(M_min) g_L(M_max)
      =
    g_B^2,

which makes the endpoint exchange-breaking parameters equal and opposite.
The resulting minimum possible maximum

    epsilon_RG_floor
      =
    min_counterterm max_mu
    |(g_B-g_L(mu))/(g_B+g_L(mu))|

is therefore a conservative physical floor.

Any additional light lepton states, threshold asymmetries, unequal scalar
sectors, or UV B/L beta-function differences only strengthen the conclusion.

HIGH-PRECISION GLOBAL NATURALNESS ENVELOPE
------------------------------------------
The full original 020A2 perturbative grid is reconstructed.

For each point:

1. set u so the lightest vector is exactly at the preferred

       M_min = 2 Lambda_mat

   boundary;

2. solve the actual target C_phi for kappa;

3. evaluate |delta m_phi^2|/m_phi^2 using the 020A2 mpmath 60-digit
   Coleman-Weinberg implementation at a small exchange breaking;

4. solve the exact high-precision root

       |delta m_phi^2(epsilon)|/m_phi^2 = 1

   for the most promising candidates;

5. compare the exact allowed epsilon with the one-Weyl and three-neutrino
   minimax RG floors across that same point's complete vector spectrum.

This directly fixes the broad-scan ranking ambiguity exposed after 020A2.

VALIDATION
----------
The run validates:

- exact upstream GREEN/negative markers;
- exact 019B charge-square sums with rational arithmetic;
- high-precision vs small-epsilon linearity;
- complete reconstruction of every original 020A2 target-matching point;
- exact root solution for the top high-precision candidates;
- analytic minimax RG floor against a brute-force counterterm scan;
- one-Weyl and three-Weyl robustness;
- blind wildcard v/u checks, explicitly not evidence.

FALSIFICATION / STOP RULE
-------------------------
The minimal Wilson/vector-current class is closed at this gate only if:

    GLOBAL_HP_TARGET_MATCH_POINTS > 0

and over EVERY tested target-matching point

    epsilon_RG_floor_one_Weyl
      >
    epsilon_allowed_HP

by a robust margin.

Using only one Weyl lepton state makes this deliberately conservative.

If this condition holds, then:

    MINIMAL_COLLECTIVE_TREE_CLASS = CLOSED
    SMALL_SU2_NONABELIAN_GATE = CLOSED
    LARGER_QUIVER_RESCUE = DO_NOT_ESCALATE
    GLOBAL_RERANK = REQUIRED

This does NOT invalidate:

- 019A Wilson-line protection as a field-theory witness;
- 019B anomaly-free vector-current EFT endpoint;
- 019C heavy-vector/Higgs algebra;
- 020A1 isospectral representation mathematics;
- 020A2 renormalizable isospectral current-response mathematics.

It invalidates the tested minimal route combining them into an ultralight,
technically natural material portal.

PROMOTION CONDITION
-------------------
If any robust point instead satisfies

    epsilon_RG_floor_one_Weyl
      <=
    epsilon_allowed_HP

then the branch survives 020A2R and should proceed to the explicit
external-Wilson / collective-transfer-spurion construction.

CLAIM LIMITS
------------
This run is not an experimental fifth-force fit and does not establish a real
material or practical antigravity device.

If negative, its strongest permitted statement is a project-derived
radiative-naturalness obstruction for the explicitly tested minimal
SU(2)_X x U(1)_B x U(1)_L isospectral portal with the 019B total-lepton-number
ordinary-matter endpoint.

CLAIM CLASSIFICATION
--------------------
PROJECT_DERIVED_020A2R_EXACT_BL_RUNNING_AND_HP_GLOBAL_NATURALNESS_CLOSEOUT
"""

from __future__ import annotations

from fractions import Fraction
import hashlib
import importlib.util
import math
from pathlib import Path
import re
import sys

import mpmath as mp
import numpy as np
from scipy.optimize import brentq, minimize_scalar


ROOT = Path(__file__).resolve().parents[1]

B_SOURCE = ROOT / "simulations/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.py"
A2_SOURCE = ROOT / "simulations/020a2_nonabelian_isospectral_bl_current_embedding_naturalness_gate.py"

A_LOG = ROOT / "results/logs/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.log"
B_LOG = ROOT / "results/logs/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.log"
C_LOG = ROOT / "results/logs/019c_vector_wilson_portal_minimal_uv_construction_gate.log"
A1_LOG = ROOT / "results/logs/020a1_collective_isospectral_vector_rotation_representation_gate.log"
A2_LOG = ROOT / "results/logs/020a2_nonabelian_isospectral_bl_current_embedding_naturalness_gate.log"

EXPECTED_020A2_SHA256 = "8478124e69426fd43edc41e62b2f0a09594c68155a428abbacdea33c4cf62f7d"

# One light left-handed Weyl lepton with |L|=1:
# b = (2/3) q^2 = 2/3.
DELTA_B_ONE_WEYL = 2.0 / 3.0

# Three active left-handed neutrino Weyl states:
DELTA_B_THREE_NEUTRINOS = 2.0

# High-precision envelope settings.
EPS_PROBE = 1.0e-6
EPS_PROBE_HALF = 5.0e-7
EPS_PROBE_DOUBLE = 2.0e-6
TOP_ROOT_CANDIDATES = 40

# Root bracket for exact allowed epsilon.
EPS_ROOT_MIN = 1.0e-12
EPS_ROOT_MAX = 1.0e-3

# Decision thresholds.
MAX_HP_LINEARITY_RELSPREAD = 1.0e-3
MIN_CLOSEOUT_DEFICIT = 10.0
MIN_RG_VALIDITY_DENOMINATOR = 0.10

# Blind wildcard diagnostics only.
BLIND_WILDCARD_RATIOS = (1.6, 1.875, 3.125, 0.625, 5.0)


def require_marker(path: Path, marker: str) -> None:
    """Require an exact upstream scientific marker."""

    if not path.exists():
        raise RuntimeError(f"Missing upstream log: {path}")

    text = path.read_text(errors="replace")
    if marker not in text:
        raise RuntimeError(
            f"Missing required marker in {path.name}: {marker}"
        )


def exact_scalar(path: Path, prefix: str) -> float:
    """Read one scalar from an exact executed-log prefix."""

    pattern = re.compile(
        rf"^{re.escape(prefix)}([+\-0-9.eE]+)$",
        re.MULTILINE,
    )
    match = pattern.search(path.read_text(errors="replace"))
    if match is None:
        raise RuntimeError(
            f"Could not find {prefix!r} in {path.name}"
        )
    value = float(match.group(1))
    if not math.isfinite(value):
        raise RuntimeError(
            f"Nonfinite scalar for {prefix!r} in {path.name}"
        )
    return value


def sha256(path: Path) -> str:
    """Return SHA-256 for one scientific source file."""

    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_module(name: str, path: Path):
    """Import a repository simulation without invoking its main()."""

    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module

    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(name, None)
        raise

    return module


def charge_square_sum(fields, which: str) -> Fraction:
    """Return exact sum of Weyl charge squares including multiplicities."""

    total = Fraction(0)

    for field in fields:
        charge = (
            field.baryon
            if which == "B"
            else field.lepton
        )
        multiplicity = (
            field.generations
            * field.color_dim
            * field.su2_dim
        )
        total += multiplicity * charge * charge

    return total


def fermion_beta_coefficient(charge_square: Fraction) -> Fraction:
    """Return exact one-loop U(1) Weyl-fermion beta coefficient."""

    return Fraction(2, 3) * charge_square


def epsilon_from_couplings(g_b: float, g_l: float) -> float:
    """Return the 020A2 exchange-breaking parameter epsilon."""

    return (g_b - g_l) / (g_b + g_l)


def optimized_rg_floor(
    g_b: float,
    delta_b: float,
    mass_ratio: float,
) -> tuple[float, float, float, float]:
    """Return the exact one-loop minimax differential-running floor.

    We retain only the differential beta-function contribution delta_b and
    deliberately set the baryonic contribution to zero.

    The normalization of g_L is optimized so that endpoint epsilon values are
    equal and opposite.

    Returns:
        floor,
        g_l_low,
        g_l_high,
        denominator_high
    """

    if g_b <= 0.0:
        raise ValueError("g_b must be positive")
    if delta_b <= 0.0:
        raise ValueError("delta_b must be positive")
    if mass_ratio <= 1.0:
        raise ValueError("mass_ratio must exceed one")

    k = (
        delta_b
        / (8.0 * math.pi**2)
        * math.log(mass_ratio)
    )

    # Let y = g_L(low)^2.
    # Minimax condition:
    #
    #     g_L(low) * g_L(high) = g_B^2
    #
    # together with
    #
    #     g_L(high)^2 = y / (1 - k y)
    #
    # gives
    #
    #     y^2 + k g_B^4 y - g_B^4 = 0.
    #
    g4 = g_b**4
    discriminant = k * k * g4 * g4 + 4.0 * g4

    y = (
        -k * g4
        + math.sqrt(discriminant)
    ) / 2.0

    if y <= 0.0:
        raise RuntimeError("Invalid minimax low-scale coupling")

    denominator = 1.0 - k * y
    if denominator <= 0.0:
        raise RuntimeError(
            "One-loop U(1) running hits a Landau singularity "
            "inside the tested vector spectrum"
        )

    g_l_low = math.sqrt(y)
    g_l_high = math.sqrt(y / denominator)

    eps_low = epsilon_from_couplings(g_b, g_l_low)
    eps_high = epsilon_from_couplings(g_b, g_l_high)

    floor = max(abs(eps_low), abs(eps_high))

    return floor, g_l_low, g_l_high, denominator


def brute_force_rg_floor(
    g_b: float,
    delta_b: float,
    mass_ratio: float,
) -> float:
    """Independent numerical minimization of the endpoint RG mismatch."""

    k = (
        delta_b
        / (8.0 * math.pi**2)
        * math.log(mass_ratio)
    )

    def objective(g_l_low: float) -> float:
        denominator = 1.0 - k * g_l_low * g_l_low
        if denominator <= 0.0:
            return 1.0e6

        g_l_high = g_l_low / math.sqrt(denominator)

        return max(
            abs(epsilon_from_couplings(g_b, g_l_low)),
            abs(epsilon_from_couplings(g_b, g_l_high)),
        )

    result = minimize_scalar(
        objective,
        bounds=(0.25 * g_b, 1.75 * g_b),
        method="bounded",
        options={
            "xatol": 1.0e-14,
            "maxiter": 1000,
        },
    )

    if not result.success:
        raise RuntimeError("Brute-force RG minimization failed")

    return float(result.fun)


def high_precision_ratio(
    a2,
    epsilon: float,
    point: dict[str, float],
    selected_f: float,
) -> float:
    """Evaluate the inherited 020A2 finite-CW naturalness ratio."""

    return a2.naturalness_ratio_high_precision(
        epsilon,
        point["kappa"],
        point["g_x"],
        point["g"],
        point["u"],
        point["r"],
        selected_f,
    )


def solve_exact_allowed_epsilon(
    a2,
    point: dict[str, float],
    selected_f: float,
) -> float:
    """Solve high-precision |delta m_phi^2|/m_phi^2 = 1."""

    def residual(log10_epsilon: float) -> float:
        epsilon = 10.0**log10_epsilon
        ratio = high_precision_ratio(
            a2,
            epsilon,
            point,
            selected_f,
        )
        return ratio - 1.0

    lo = math.log10(EPS_ROOT_MIN)
    hi = math.log10(EPS_ROOT_MAX)

    f_lo = residual(lo)
    f_hi = residual(hi)

    if f_lo > 0.0:
        # Allowed value lies below our already extremely small bracket.
        return EPS_ROOT_MIN

    if f_hi < 0.0:
        # This would mean the point is far more natural than anticipated.
        # Enlarge conservatively but remain inside the small-breaking regime.
        hi2 = math.log10(0.05)
        f_hi2 = residual(hi2)
        if f_hi2 < 0.0:
            return 0.05
        hi = hi2

    root = brentq(
        residual,
        lo,
        hi,
        xtol=1.0e-10,
        rtol=1.0e-10,
        maxiter=100,
    )

    return 10.0**root


def reconstruct_global_grid(
    a2,
    selected_f: float,
    theta_earth: float,
) -> list[dict[str, float]]:
    """Reconstruct every target-matching point in the original 020A2 grid."""

    candidates: list[dict[str, float]] = []

    for g_x_raw in a2.GX_GRID:
        for g_raw in a2.G_GRID:
            g_x = float(g_x_raw)
            g = float(g_raw)

            if (
                g_x > a2.PERTURBATIVE_G_MAX
                or g > a2.PERTURBATIVE_G_MAX
            ):
                continue

            for r_raw in a2.R_GRID:
                r = float(r_raw)

                u = a2.scale_u_to_margin(
                    g_x,
                    g,
                    r,
                )
                if u is None:
                    continue

                kappa = a2.solve_kappa(
                    theta_earth,
                    selected_f,
                    g_x,
                    g,
                    u,
                    r,
                )
                if kappa is None or kappa > a2.MAX_KAPPA:
                    continue

                masses = np.sqrt(
                    np.linalg.eigvalsh(
                        a2.physical_mass2(
                            0.0,
                            g_x,
                            g,
                            u,
                            r,
                        )
                    )
                )

                point = {
                    "g_x": g_x,
                    "g": g,
                    "r": r,
                    "u": float(u),
                    "v": float(u * r),
                    "kappa": float(kappa),
                    "min_mass": float(masses[0]),
                    "max_mass": float(masses[-1]),
                    "mass_ratio": float(masses[-1] / masses[0]),
                }

                ratio_probe = high_precision_ratio(
                    a2,
                    EPS_PROBE,
                    point,
                    selected_f,
                )

                if (
                    not math.isfinite(ratio_probe)
                    or ratio_probe <= 0.0
                ):
                    continue

                epsilon_allowed_est = EPS_PROBE / ratio_probe

                floor_one, _, _, denom_one = optimized_rg_floor(
                    g,
                    DELTA_B_ONE_WEYL,
                    point["mass_ratio"],
                )

                floor_three, _, _, denom_three = optimized_rg_floor(
                    g,
                    DELTA_B_THREE_NEUTRINOS,
                    point["mass_ratio"],
                )

                point.update(
                    {
                        "ratio_probe": ratio_probe,
                        "epsilon_allowed_est": epsilon_allowed_est,
                        "floor_one_est": floor_one,
                        "floor_three_est": floor_three,
                        "deficit_one_est": floor_one / epsilon_allowed_est,
                        "deficit_three_est": floor_three / epsilon_allowed_est,
                        "denom_one": denom_one,
                        "denom_three": denom_three,
                    }
                )

                candidates.append(point)

    return candidates


def main() -> None:
    """Execute the complete 020A2R closeout."""

    print(
        "=== 020A2R — EXACT B/L RUNNING + "
        "HIGH-PRECISION GLOBAL NATURALNESS CLOSEOUT ==="
    )

    # --------------------------------------------------------------
    # Upstream fail-closed audit.
    # --------------------------------------------------------------
    require_marker(
        B_LOG,
        "ANOMALY_FREE_U1B_X_U1L_COMPLETION=PASS",
    )
    require_marker(
        B_LOG,
        "VECTOR_CURRENT_ONE_BODY_MIXING_PREFLIGHT=PASS",
    )
    require_marker(
        C_LOG,
        "019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE=GREEN_NEGATIVE_RESULT",
    )
    require_marker(
        A1_LOG,
        "SU2_RENORMALIZABLE_ISOSPECTRAL_REPRESENTATION=PASS",
    )
    require_marker(
        A2_LOG,
        "RENORMALIZABLE_FULL5X5_ISOSPECTRAL_VECTOR_WITNESS=PASS",
    )
    require_marker(
        A2_LOG,
        "TARGET_C_PHI_MATCH=PASS",
    )
    require_marker(
        A2_LOG,
        "020A2_NONABELIAN_ISOSPECTRAL_CURRENT_EMBEDDING_GATE=GREEN_NEGATIVE_RESULT",
    )

    if not B_SOURCE.exists():
        raise RuntimeError(f"Missing 019B source: {B_SOURCE}")
    if not A2_SOURCE.exists():
        raise RuntimeError(f"Missing 020A2 source: {A2_SOURCE}")

    a2_sha = sha256(A2_SOURCE)

    print("\n=== UPSTREAM SOURCE AUDIT ===")
    print(f"020A2_SOURCE_SHA256={a2_sha}")
    print(f"020A2_EXPECTED_SHA256={EXPECTED_020A2_SHA256}")
    print(
        "020A2_SOURCE_HASH_MATCH="
        + (
            "PASS"
            if a2_sha == EXPECTED_020A2_SHA256
            else "FAIL"
        )
    )

    if a2_sha != EXPECTED_020A2_SHA256:
        raise RuntimeError(
            "020A2 source hash changed; closeout must audit the "
            "actually executed source before proceeding"
        )

    b = load_module("ag020a2r_019b", B_SOURCE)
    a2 = load_module("ag020a2r_020a2", A2_SOURCE)

    selected_f = exact_scalar(
        A_LOG,
        "SELECTED_F_EV=",
    )
    theta_earth = exact_scalar(
        A_LOG,
        "SELECTED_THETA_EARTH=",
    )

    print(f"SELECTED_F_EV={selected_f:.15e}")
    print(f"SELECTED_THETA_EARTH={theta_earth:.15e}")

    # --------------------------------------------------------------
    # A. Exact 019B charge-square / beta-function audit.
    # --------------------------------------------------------------
    print("\n=== A — EXACT 019B B/L ONE-LOOP CHARGE-SQUARE AUDIT ===")

    fields = b.build_bl_completion_fields()

    sum_b2 = charge_square_sum(fields, "B")
    sum_l2 = charge_square_sum(fields, "L")

    beta_b = fermion_beta_coefficient(sum_b2)
    beta_l = fermion_beta_coefficient(sum_l2)
    delta_beta = beta_l - beta_b

    print(
        "019B_WEYL_SUM_B2="
        f"{sum_b2.numerator}/{sum_b2.denominator}"
    )
    print(
        "019B_WEYL_SUM_L2="
        f"{sum_l2.numerator}/{sum_l2.denominator}"
    )
    print(
        "019B_FERMION_BETA_B="
        f"{beta_b.numerator}/{beta_b.denominator}"
    )
    print(
        "019B_FERMION_BETA_L="
        f"{beta_l.numerator}/{beta_l.denominator}"
    )
    print(
        "019B_FERMION_DELTA_BETA_L_MINUS_B="
        f"{delta_beta.numerator}/{delta_beta.denominator}"
    )

    # Extra 019B anomaly-canceling fermions carry equal B and L magnitudes.
    # Therefore they cannot erase the B/L charge-square difference inherited
    # from ordinary matter.
    print(
        "019B_ANOMALY_EXOTICS_CANCEL_B_L_BETA_DIFFERENCE="
        "NO"
    )
    print(
        "CONSERVATIVE_ONE_LIGHT_WEYL_DELTA_BETA="
        f"{DELTA_B_ONE_WEYL:.15e}"
    )
    print(
        "ACTUAL_THREE_ACTIVE_NEUTRINO_DELTA_BETA="
        f"{DELTA_B_THREE_NEUTRINOS:.15e}"
    )

    # --------------------------------------------------------------
    # B. Reconstruct global target-matching grid with HP naturalness.
    # --------------------------------------------------------------
    print("\n=== B — HIGH-PRECISION GLOBAL 020A2 GRID RECONSTRUCTION ===")

    candidates = reconstruct_global_grid(
        a2,
        selected_f,
        theta_earth,
    )

    if not candidates:
        raise RuntimeError(
            "No 020A2 target-matching points reconstructed"
        )

    print(
        f"GLOBAL_HP_TARGET_MATCH_POINTS={len(candidates)}"
    )

    # Rank ONLY by high-precision allowed-epsilon estimate.
    candidates.sort(
        key=lambda point: point["epsilon_allowed_est"],
        reverse=True,
    )

    provisional_best = candidates[0]

    print(
        "GLOBAL_HP_PROVISIONAL_BEST_GX="
        f"{provisional_best['g_x']:.15e}"
    )
    print(
        "GLOBAL_HP_PROVISIONAL_BEST_G="
        f"{provisional_best['g']:.15e}"
    )
    print(
        "GLOBAL_HP_PROVISIONAL_BEST_V_OVER_U="
        f"{provisional_best['r']:.15e}"
    )
    print(
        "GLOBAL_HP_PROVISIONAL_BEST_KAPPA="
        f"{provisional_best['kappa']:.15e}"
    )
    print(
        "GLOBAL_HP_PROVISIONAL_EPSILON_ALLOWED_EST="
        f"{provisional_best['epsilon_allowed_est']:.15e}"
    )
    print(
        "GLOBAL_HP_PROVISIONAL_ONE_WEYL_DEFICIT_EST="
        f"{provisional_best['deficit_one_est']:.15e}"
    )

    # --------------------------------------------------------------
    # C. Exact high-precision roots for top global candidates.
    # --------------------------------------------------------------
    print("\n=== C — EXACT HP ALLOWED-EPSILON ROOTS FOR TOP CANDIDATES ===")

    top = candidates[: min(TOP_ROOT_CANDIDATES, len(candidates))]

    exact_rows: list[dict[str, float]] = []

    for rank, point in enumerate(top, start=1):
        allowed_exact = solve_exact_allowed_epsilon(
            a2,
            point,
            selected_f,
        )

        floor_one, g_l_low_one, g_l_high_one, denom_one = optimized_rg_floor(
            point["g"],
            DELTA_B_ONE_WEYL,
            point["mass_ratio"],
        )
        floor_three, _, _, denom_three = optimized_rg_floor(
            point["g"],
            DELTA_B_THREE_NEUTRINOS,
            point["mass_ratio"],
        )

        row = dict(point)
        row.update(
            {
                "allowed_exact": allowed_exact,
                "floor_one": floor_one,
                "floor_three": floor_three,
                "deficit_one": floor_one / allowed_exact,
                "deficit_three": floor_three / allowed_exact,
                "g_l_low_one": g_l_low_one,
                "g_l_high_one": g_l_high_one,
                "denom_one_exact": denom_one,
                "denom_three_exact": denom_three,
            }
        )
        exact_rows.append(row)

        if rank <= 8:
            print(
                f"TOP{rank:02d}_GX={point['g_x']:.9e} "
                f"G={point['g']:.9e} "
                f"R={point['r']:.9e} "
                f"KAPPA={point['kappa']:.9e} "
                f"MASS_RATIO={point['mass_ratio']:.9e} "
                f"EPS_ALLOWED={allowed_exact:.9e} "
                f"ONE_WEYL_FLOOR={floor_one:.9e} "
                f"ONE_WEYL_DEFICIT={floor_one / allowed_exact:.9e}"
            )

    exact_rows.sort(
        key=lambda point: point["allowed_exact"],
        reverse=True,
    )
    best_allowed = exact_rows[0]

    # To prove the global rejection, the relevant quantity is the smallest
    # RG-floor / allowed-epsilon deficit.  The exact roots were evaluated for
    # the candidates with the largest HP allowed epsilon; all omitted points
    # have smaller allowed estimates.  We nevertheless evaluate a conservative
    # global estimate for every point and compare with the exact top set.
    min_est_deficit = min(
        point["deficit_one_est"]
        for point in candidates
    )

    min_exact_deficit = min(
        point["deficit_one"]
        for point in exact_rows
    )
    best_deficit = min(
        exact_rows,
        key=lambda point: point["deficit_one"],
    )

    print(
        "GLOBAL_HP_MAX_EPSILON_ALLOWED_EXACT="
        f"{best_allowed['allowed_exact']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_GX="
        f"{best_allowed['g_x']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_G="
        f"{best_allowed['g']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_V_OVER_U="
        f"{best_allowed['r']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_KAPPA="
        f"{best_allowed['kappa']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_MIN_VECTOR_EV="
        f"{best_allowed['min_mass']:.15e}"
    )
    print(
        "GLOBAL_HP_MAX_ALLOWED_MAX_VECTOR_EV="
        f"{best_allowed['max_mass']:.15e}"
    )

    print(
        "GLOBAL_MIN_ONE_WEYL_DEFICIT_EST_ALL_POINTS="
        f"{min_est_deficit:.15e}"
    )
    print(
        "GLOBAL_MIN_ONE_WEYL_DEFICIT_EXACT_TOP_SET="
        f"{min_exact_deficit:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_GX="
        f"{best_deficit['g_x']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_G="
        f"{best_deficit['g']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_V_OVER_U="
        f"{best_deficit['r']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_EPS_ALLOWED="
        f"{best_deficit['allowed_exact']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_ONE_WEYL_RG_FLOOR="
        f"{best_deficit['floor_one']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_ONE_WEYL_FACTOR="
        f"{best_deficit['deficit_one']:.15e}"
    )
    print(
        "GLOBAL_MIN_DEFICIT_THREE_NEUTRINO_FACTOR="
        f"{best_deficit['deficit_three']:.15e}"
    )

    # --------------------------------------------------------------
    # D. HP linearity at the true best-allowed point.
    # --------------------------------------------------------------
    print("\n=== D — HIGH-PRECISION SMALL-EPSILON LINEARITY ===")

    ratio_half = high_precision_ratio(
        a2,
        EPS_PROBE_HALF,
        best_allowed,
        selected_f,
    )
    ratio_center = high_precision_ratio(
        a2,
        EPS_PROBE,
        best_allowed,
        selected_f,
    )
    ratio_double = high_precision_ratio(
        a2,
        EPS_PROBE_DOUBLE,
        best_allowed,
        selected_f,
    )

    slopes = (
        ratio_half / EPS_PROBE_HALF,
        ratio_center / EPS_PROBE,
        ratio_double / EPS_PROBE_DOUBLE,
    )

    linearity_relspread = (
        max(slopes) - min(slopes)
    ) / max(abs(slopes[1]), 1.0e-300)

    print(
        "GLOBAL_HP_LINEARITY_RELSPREAD="
        f"{linearity_relspread:.15e}"
    )
    print(
        "GLOBAL_HP_LINEARITY="
        + (
            "PASS"
            if linearity_relspread <= MAX_HP_LINEARITY_RELSPREAD
            else "FAIL"
        )
    )

    # --------------------------------------------------------------
    # E. Independent analytic-vs-brute RG minimax validation.
    # --------------------------------------------------------------
    print("\n=== E — INDEPENDENT RG MINIMAX VALIDATION ===")

    analytic_floor, _, _, denominator = optimized_rg_floor(
        best_deficit["g"],
        DELTA_B_ONE_WEYL,
        best_deficit["mass_ratio"],
    )
    brute_floor = brute_force_rg_floor(
        best_deficit["g"],
        DELTA_B_ONE_WEYL,
        best_deficit["mass_ratio"],
    )

    rg_relerr = abs(
        analytic_floor / brute_floor - 1.0
    )

    print(
        "RG_MINIMAX_ANALYTIC_FLOOR="
        f"{analytic_floor:.15e}"
    )
    print(
        "RG_MINIMAX_BRUTE_FLOOR="
        f"{brute_floor:.15e}"
    )
    print(
        "RG_MINIMAX_RELERR="
        f"{rg_relerr:.15e}"
    )
    print(
        "RG_ONE_LOOP_DENOMINATOR_AT_HIGH_END="
        f"{denominator:.15e}"
    )
    print(
        "RG_MINIMAX_VALIDATION="
        + (
            "PASS"
            if (
                rg_relerr <= 1.0e-5
                and denominator >= MIN_RG_VALIDITY_DENOMINATOR
            )
            else "FAIL"
        )
    )

    # --------------------------------------------------------------
    # F. Blind wildcard diagnostics, not evidence.
    # --------------------------------------------------------------
    print("\n=== BLIND WILDCARD V/U DIAGNOSTICS — NOT EVIDENCE ===")

    for ratio in BLIND_WILDCARD_RATIOS:
        nearest = min(
            candidates,
            key=lambda point: abs(point["r"] - ratio),
        )

        print(
            f"WILDCARD_TARGET_R={ratio:.6f} "
            f"NEAREST_GRID_R={nearest['r']:.9e} "
            f"GX={nearest['g_x']:.9e} "
            f"G={nearest['g']:.9e} "
            f"EPS_ALLOWED_EST={nearest['epsilon_allowed_est']:.9e} "
            f"ONE_WEYL_DEFICIT_EST={nearest['deficit_one_est']:.9e}"
        )

    print("BLIND_WILDCARD_VALUES_USED_AS_EVIDENCE=NO")

    # --------------------------------------------------------------
    # G. Final fail-closed decision.
    # --------------------------------------------------------------
    print("\n=== 020A2R DECISION ===")

    source_pass = (
        a2_sha == EXPECTED_020A2_SHA256
    )

    hp_pass = (
        linearity_relspread <= MAX_HP_LINEARITY_RELSPREAD
    )

    rg_validation_pass = (
        rg_relerr <= 1.0e-5
        and denominator >= MIN_RG_VALIDITY_DENOMINATOR
    )

    # The estimated all-grid minimum must already be far above one, and the
    # exact top set must independently confirm the same conclusion.
    robust_closeout = (
        source_pass
        and hp_pass
        and rg_validation_pass
        and min_est_deficit >= MIN_CLOSEOUT_DEFICIT
        and min_exact_deficit >= MIN_CLOSEOUT_DEFICIT
    )

    if robust_closeout:
        print(
            "020A2R_EXACT_BL_RUNNING_AND_HP_GLOBAL_NATURALNESS_CLOSEOUT="
            "GREEN_NEGATIVE_RESULT"
        )
        print(
            "HIGH_PRECISION_GLOBAL_NATURALNESS_ENVELOPE="
            "RECONSTRUCTED"
        )
        print(
            "ONE_LIGHT_WEYL_LEPTON_RUNNING_ALONE_EXCEEDS_ALLOWED_SPLITTING="
            "YES"
        )
        print(
            "THREE_ACTIVE_NEUTRINO_RUNNING_EXCEEDS_ALLOWED_SPLITTING="
            "YES"
        )
        print(
            "MINIMAL_B_L_EXCHANGE_SYMMETRIC_SU2_PORTAL="
            "CLOSED_BY_PHYSICAL_RG_NATURALNESS"
        )
        print(
            "020A_MINIMAL_COLLECTIVE_TREE_CLASS="
            "CLOSED_IN_TESTED_CLASSES"
        )
        print(
            "020A_SMALL_SU2_NONABELIAN_GATE="
            "CLOSED_IN_TESTED_MINIMAL_CLASS"
        )
        print(
            "LARGER_QUIVER_OR_MIRROR_MATTER_RESCUE="
            "DO_NOT_ESCALATE_WITHOUT_NEW_INDEPENDENT_PROTECTION_PRINCIPLE"
        )
        print("GLOBAL_RERANK=REQUIRED")
        print(
            "NEXT="
            "GLOBAL_RERANK_FOR_NEW_STRUCTURAL_SCALING_MECHANISM"
        )
    else:
        print(
            "020A2R_EXACT_BL_RUNNING_AND_HP_GLOBAL_NATURALNESS_CLOSEOUT="
            "NOT_CLOSED"
        )
        print(
            "MINIMAL_B_L_EXCHANGE_SYMMETRIC_SU2_PORTAL="
            "RETAINS_A_SURVIVING_POINT_OR_VALIDATION_GAP"
        )
        print(
            "NEXT="
            "INSPECT_SURVIVING_POINT_BEFORE_GLOBAL_RERANK"
        )

    # Preserve previous positive and negative results.
    print("006D_CONSTRUCTIVE_LINEARIZED_GR_RESULT=RETAINED")
    print("018B_FIELD_EXISTENCE_RESULT=RETAINED")
    print("018C_M2_STABILITY_FALSIFICATION=RETAINED")
    print("019A_WILSON_LINE_UV_PROTECTION_WITNESS=RETAINED")
    print("019B_ANOMALY_FREE_VECTOR_CURRENT_ENDPOINT=RETAINED")
    print("019C_VECTOR_HIGGS_MEDIATOR_ALGEBRA=RETAINED")
    print("020A1_ISOSPECTRAL_REPRESENTATION_RESULT=RETAINED")
    print("020A2_RENORMALIZABLE_ISOSPECTRAL_CURRENT_RESPONSE=RETAINED")
    print("COMPLETE_MICROSCOPIC_VECTOR_WILSON_UV_WITNESS=NO")
    print(
        "CURRENT_KNOWLEDGE_HEURISTIC="
        "APPROXIMATELY_68_PERCENT_NOT_A_PROBABILITY"
    )
    print(
        "HEURISTIC_CHANGE="
        "NONE_NEGATIVE_CLOSEOUT_INCREASES_KNOWLEDGE_NOT_DEVICE_MATURITY"
    )
    print("REAL_ANTIGRAVITY_MATERIAL=NO")
    print("PRACTICAL_ANTIGRAVITY_DEVICE=NO")
    print("NEW_PHYSICS_DISCOVERY=NO")
    print(
        "CLAIM_CLASSIFICATION="
        "PROJECT_DERIVED_020A2R_EXACT_BL_RUNNING_AND_HP_GLOBAL_NATURALNESS_CLOSEOUT"
    )


if __name__ == "__main__":
    main()
