#!/usr/bin/env python3
"""020A1 — collective/ispectral Wilson-vector representation and naturalness gate.

PURPOSE
-------
Test the cheapest structural route left after 019C:

    protected ultralight Wilson/pNGB mode
        -> tree or collective-tree heavy-vector response
        -> C_phi * phi * J_B^mu J_L,mu

without repeating the two minimal Abelian loop mechanisms already rejected.

SCIENTIFIC QUESTION
-------------------
Can the required vector-current response be generated by rotating a heavy-vector
eigenbasis rather than changing heavy-vector eigenvalues, so that the desired
tree-level current-current kernel is nonzero while the leading vector
Coleman-Weinberg potential remains insensitive to the ultralight angle?

This gate tests five logically separate statements:

1. Pure Abelian link kinetic terms are phase-blind at tree level.
2. A conventional eigenvalue-splitting response has a severe one-loop
   naturalness problem at the required 2x material-EFT separation.
3. An ideal isospectral 2x2 mass rotation exactly preserves spectral
   invariants while matching the required C_phi with modest rotation.
4. The actual 019C S_+/S_- Abelian charge assignments obstruct a neutral
   continuous rotator at renormalizable level.
5. A minimal SU(2) fundamental+adjoint Higgs sector gives an explicit
   renormalizable isospectral vector-mass representation under an exact
   Phi -> -Phi symmetry, but identifying that same relative angle directly
   with the 5-km scalar and coupling it directly to SU(2) currents fails a
   model-independent two-scale response bound.

The run is therefore a representation/naturalness gate, not a complete 020A
promotion.  A GREEN_NEGATIVE_RESULT may still be highly informative by
authorizing the buildplan's small-group non-Abelian transfer gate.

PHYSICAL MODEL AND EQUATIONS
----------------------------
A. Abelian phase blindness

For a scalar link Sigma_i = v_i exp(i alpha_i) with fixed U(1)^n charge vector
q_i, canonical kinetic terms give

    (M_V^2)_ab
      = sum_i v_i^2 g_a g_b q_ia q_ib

which is independent of alpha_i.  Therefore a phase-only Wilson variable
cannot directly seed an Abelian gauge-boson mass matrix through |D Sigma|^2.

B. Conventional splitting comparison

Use

    M^2(theta)
      = M_V^2 [[1, eta theta],
               [eta theta, 1]]

near theta=0.  Then

    C_phi = g_B g_L eta / (f M_V^2).

The renormalization-scale derivative of the vector Coleman-Weinberg curvature is

    |d m_phi^2 / d ln Q|
      = 3 M_V^4 eta^2 / (8 pi^2 f^2)

and eliminating eta gives

    |d m_phi^2 / d ln Q|
      = 3 C_phi^2 M_V^8
        / [8 pi^2 (g_B g_L)^2].

This comparison is deliberately maximally favorable to the splitting model by
using g_B g_L = 4 pi.

C. Isospectral rotation

Use

    M^2(theta)
      = R(beta)
        diag(M_1^2, M_2^2)
        R(beta)^T,

    beta(theta) = kappa sin(theta).

The heavy-vector spectrum is independent of theta, but

    [M^-2]_BL
      = 1/2 (1/M_1^2 - 1/M_2^2) sin(2 beta)

so the pair coefficient is

    C_phi
      = (g_B g_L / f)
        |(1/M_1^2 - 1/M_2^2)
          cos(2 beta) beta_theta|.

D. Abelian bridge-charge obstruction

019C uses

    q(S_+) = (1,+1),
    q(S_-) = (1,-1)

under U(1)_B x U(1)_L.  The off-diagonal bilinear S_+^dagger S_- carries

    q = (0,-2).

A gauge-neutral rotator cannot therefore generate the off-diagonal
renormalizable mixing needed for a continuous S_+/S_- basis rotation.
A new field/spurion carrying the charge difference is mandatory.

E. SU(2) isospectral representation

Take an SU(2)_X gauge theory with one complex fundamental H and one real
adjoint Phi^a.  With

    <H> = u / sqrt(2),

the fundamental contributes an isotropic vector mass

    m_0^2 I,
    m_0^2 = g_X^2 u^2 / 4.

For

    <Phi^a> = v n^a(theta),

the adjoint contributes

    g_X^2 v^2 (I - n n^T).

Hence

    M_X^2(theta)
      = m_0^2 I
        + g_X^2 v^2 (I - n n^T)

with exact theta-independent eigenvalues

    {m_0^2,
     m_0^2 + g_X^2 v^2,
     m_0^2 + g_X^2 v^2}.

For SU(2), Phi^2 is proportional to the identity.  With exact Phi -> -Phi,
the orientation-sensitive cubic H^dagger Phi H is forbidden and
H^dagger Phi^2 H is orientation independent.  Thus this field content is a
minimal renormalizable isospectral representation witness.

However, if this same relative angle is itself the 5-km scalar with decay
constant f_rel, integrating out the gauge field gives

    f_rel = u v / sqrt(u^2 + 4 v^2),

so f_rel <= u/2.  Direct SU(2)-current coupling then obeys

    C_phi <= 4/(f_rel u^2) <= 1/f_rel^3.

The terrestrial excursion requirement |phi_Earth/f_rel| <= 0.5 therefore
places a model-independent upper bound on this direct identification.

UNITS
-----
Natural units hbar=c=1.  Masses and decay constants are in eV.

INPUTS
------
The run reads the executed 019A/019B/019C logs and uses:
- selected 019A f and theta_Earth;
- project target C_phi and m_phi;
- material EFT cutoff.

OUTPUTS
-------
The run prints:
- upstream marker audit;
- Abelian phase-blindness result;
- conventional splitting naturalness ratios;
- exact isospectral target match and independent finite-difference check;
- spectral-invariant drift;
- blind wildcard mass-ratio diagnostics, explicitly not evidence;
- Abelian bridge charge audit;
- SU(2) Pauli identity / spectrum audit;
- direct-SU(2) two-scale upper bound;
- a fail-closed decision and next action.

ASSUMPTIONS AND LIMITATIONS
---------------------------
- This is not yet a complete anomaly calculation; 019B's anomaly-free
  U(1)_B x U(1)_L endpoint result is inherited.
- The ideal 2x2 isospectral matrix is an algebraic target, not by itself a UV
  completion.
- The SU(2) representation witness does not yet provide a gauge-consistent
  B/L current embedding or an external-Wilson-to-SU(2) transfer sector.
- The direct-SU(2) scaling bound applies only when the SU(2) relative angle
  itself is identified with the ultralight scalar and ordinary currents couple
  directly through the same SU(2) gauge coupling.
- Experimental fifth-force, stellar, cosmological, real-material, device-power,
  and practical-energy gates remain deferred.

VALIDATION / FALSIFICATION
--------------------------
The ideal isospectral witness passes only if:
- analytic and finite-difference d[M^-2]_BL/dtheta agree;
- eigenvalues, Tr M^2, and Tr M^4 are theta independent numerically;
- target C_phi is matched at the actual terrestrial theta;
- the required rotation coefficient is perturbatively modest.

The minimal Abelian collective phase-only class is structurally rejected if:
- canonical Abelian link masses are phase blind; and
- a neutral renormalizable rotator cannot mix the actual S_+/S_- charge states.

The direct SU(2)-pNGB identification is rejected if its absolute upper bound on
C_phi lies below the target.

PERMITTED CLAIM
---------------
At most:
- a project-derived structural no-go for the explicitly tested minimal
  Abelian phase-only/neutral-rotator class;
- an exact algebraic isospectral response witness;
- a minimal renormalizable SU(2) isospectral representation witness;
- a direct-SU(2)-pNGB scaling obstruction.

This run cannot claim a complete microscopic Wilson-vector portal.

LITERATURE ANCHORS
------------------
- Arkani-Hamed, Cohen & Georgi, arXiv:hep-ph/0105239: dimensional
  deconstruction / theory-space protection of extended pNGB degrees of freedom.
- Arkani-Hamed, Cohen, Katz & Nelson, arXiv:hep-ph/0206021: collective
  symmetry breaking and cancellation of one-loop quadratic pNGB mass terms.
- Hosotani, arXiv:hep-ph/0504272: non-Abelian Wilson-line phases can control
  gauge symmetry breaking and vector masses.

CLAIM CLASSIFICATION
--------------------
PROJECT_DERIVED_020A1_COLLECTIVE_ISOSPECTRAL_VECTOR_REPRESENTATION_GATE
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path
import re

import numpy as np
from scipy.optimize import brentq


ROOT = Path(__file__).resolve().parents[1]

A_SOURCE = ROOT / "simulations/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.py"
B_SOURCE = ROOT / "simulations/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.py"
C_SOURCE = ROOT / "simulations/019c_vector_wilson_portal_minimal_uv_construction_gate.py"

A_LOG = ROOT / "results/logs/019a_wilson_line_sequestered_pair_scalar_uv_protection_gate.log"
B_LOG = ROOT / "results/logs/019b_anomaly_free_sm_material_endpoint_and_one_body_mixing_gate.log"
C_LOG = ROOT / "results/logs/019c_vector_wilson_portal_minimal_uv_construction_gate.log"

TARGET_C_PHI = 9.536416387852626e-20
TARGET_M_PHI = 3.946539608e-11
EARTH_PHI = 1.690631280830914e10
MATERIAL_EFT_CUTOFF = 657.7566

MAX_RELERR = 2.0e-8
MAX_SPECTRAL_DRIFT = 2.0e-12
MAX_ROTATION_KAPPA = 0.1

# Blind wildcard checks are diagnostics only, never evidence or optimization.
BLIND_WILDCARD_MASS_RATIOS = (1.6, 1.875, 3.125, 0.625, 5.0)


def require_marker(path: Path, marker: str) -> None:
    """Require one exact upstream scientific marker."""

    if not path.exists():
        raise RuntimeError(f"Missing upstream artifact: {path}")

    text = path.read_text(errors="replace")
    if marker not in text:
        raise RuntimeError(f"Missing marker {marker!r} in {path}")


def exact_scalar(path: Path, label: str) -> float:
    """Read one finite floating-point scalar following an exact label."""

    if not path.exists():
        raise RuntimeError(f"Missing upstream artifact: {path}")

    text = path.read_text(errors="replace")
    number = r"([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)"
    match = re.search(re.escape(label) + number, text)
    if match is None:
        raise RuntimeError(f"Missing scalar label {label!r} in {path}")

    value = float(match.group(1))
    if not math.isfinite(value):
        raise RuntimeError(f"Nonfinite scalar after {label!r} in {path}")
    return value


def relerr(a: float, b: float) -> float:
    """Symmetric relative error with a tiny absolute floor."""

    return abs(a - b) / max(abs(a), abs(b), 1.0e-300)


def sha256(path: Path) -> str:
    """Return SHA-256 for one source file."""

    if not path.exists():
        raise RuntimeError(f"Missing source file: {path}")
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rotation2(beta: float) -> np.ndarray:
    """Return a real 2x2 orthogonal rotation."""

    c = math.cos(beta)
    s = math.sin(beta)
    return np.array([[c, -s], [s, c]], dtype=float)


def isospectral_mass2(theta: float, kappa: float, m1: float, m2: float) -> np.ndarray:
    """Return the exact 2x2 isospectral mass-squared matrix."""

    beta = kappa * math.sin(theta)
    r = rotation2(beta)
    d = np.diag([m1 * m1, m2 * m2])
    return r @ d @ r.T


def isospectral_inverse_cross_analytic(
    theta: float,
    kappa: float,
    m1: float,
    m2: float,
) -> float:
    """Return analytic [M^-2]_BL for the 2x2 isospectral witness."""

    beta = kappa * math.sin(theta)
    return 0.5 * (1.0 / m1**2 - 1.0 / m2**2) * math.sin(2.0 * beta)


def isospectral_inverse_cross_derivative_analytic(
    theta: float,
    kappa: float,
    m1: float,
    m2: float,
) -> float:
    """Return analytic d[M^-2]_BL/dtheta."""

    beta = kappa * math.sin(theta)
    beta_prime = kappa * math.cos(theta)
    return (
        (1.0 / m1**2 - 1.0 / m2**2)
        * math.cos(2.0 * beta)
        * beta_prime
    )


def isospectral_cphi(
    theta: float,
    kappa: float,
    m1: float,
    m2: float,
    f: float,
    g_b: float = 1.0,
    g_l: float = 1.0,
) -> float:
    """Return the target low-energy coefficient for the ideal rotation."""

    deriv = isospectral_inverse_cross_derivative_analytic(
        theta,
        kappa,
        m1,
        m2,
    )
    return abs(g_b * g_l * deriv / f)


def solve_isospectral_kappa(
    theta: float,
    m1: float,
    m2: float,
    f: float,
    g_b: float = 1.0,
    g_l: float = 1.0,
) -> float:
    """Solve the small positive rotation coefficient that matches C_phi."""

    def residual(kappa: float) -> float:
        return isospectral_cphi(theta, kappa, m1, m2, f, g_b, g_l) - TARGET_C_PHI

    upper = 1.0
    if residual(upper) < 0.0:
        raise RuntimeError("Ideal isospectral witness cannot reach target below kappa=1")
    return brentq(residual, 1.0e-15, upper, xtol=1.0e-14, rtol=1.0e-13)


def finite_difference_cross_derivative(
    theta: float,
    kappa: float,
    m1: float,
    m2: float,
    step: float = 1.0e-5,
) -> float:
    """Independently reconstruct d[M^-2]_BL/dtheta by matrix inversion."""

    def cross(t: float) -> float:
        inv = np.linalg.inv(isospectral_mass2(t, kappa, m1, m2))
        return float(inv[0, 1])

    return (cross(theta + step) - cross(theta - step)) / (2.0 * step)


def conventional_split_naturalness_ratio(
    vector_mass: float,
    g_product: float,
) -> float:
    """Return |d m_phi^2/d lnQ| / m_phi^2 for the split-eigenvalue model."""

    dm2 = (
        3.0
        * TARGET_C_PHI**2
        * vector_mass**8
        / (8.0 * math.pi**2 * g_product**2)
    )
    return dm2 / TARGET_M_PHI**2


def pauli_matrices() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return sigma_x, sigma_y, sigma_z."""

    sx = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
    sy = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
    sz = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)
    return sx, sy, sz


def su2_adjoint_matrix(phi: np.ndarray) -> np.ndarray:
    """Return Phi = phi^a sigma^a / 2 in the fundamental representation."""

    sx, sy, sz = pauli_matrices()
    return 0.5 * (phi[0] * sx + phi[1] * sy + phi[2] * sz)


def su2_vector_mass2(
    beta: float,
    g_x: float,
    u: float,
    v: float,
) -> np.ndarray:
    """Return SU(2) vector mass-squared from one fundamental + one adjoint."""

    n = np.array([math.sin(beta), 0.0, math.cos(beta)], dtype=float)
    m0_sq = g_x * g_x * u * u / 4.0
    adj_sq = g_x * g_x * v * v
    return m0_sq * np.eye(3) + adj_sq * (np.eye(3) - np.outer(n, n))


def main() -> None:
    """Execute the complete 020A1 structural gate."""

    print("=== 020A1 — COLLECTIVE / ISOSPECTRAL VECTOR REPRESENTATION GATE ===")

    require_marker(
        A_LOG,
        "019A_WILSON_LINE_SEQUESTERED_PAIR_SCALAR_UV_PROTECTION_GATE=GREEN",
    )
    require_marker(
        B_LOG,
        "019B_ANOMALY_FREE_SM_MATERIAL_ENDPOINT_AND_ONE_BODY_OPERATOR_MIXING_GATE=GREEN_NEGATIVE_RESULT",
    )
    require_marker(
        C_LOG,
        "019C_MINIMAL_ABELIAN_VECTOR_WILSON_UV_CONSTRUCTION_GATE=GREEN_NEGATIVE_RESULT",
    )
    require_marker(
        C_LOG,
        "RENORMALIZABLE_VECTOR_HIGGS_MEDIATOR_SECTOR=SUPPORTED_IF_PROTECTED_ODD_WILSON_SEED_EXISTS",
    )

    selected_f = exact_scalar(A_LOG, "SELECTED_F_EV=")
    selected_theta = exact_scalar(A_LOG, "SELECTED_THETA_EARTH=")

    print("\n=== UPSTREAM SCIENTIFIC AUDIT ===")
    print(f"019A_SOURCE_SHA256={sha256(A_SOURCE)}")
    print(f"019B_SOURCE_SHA256={sha256(B_SOURCE)}")
    print(f"019C_SOURCE_SHA256={sha256(C_SOURCE)}")
    print("019A_WILSON_PROTECTION=RETAINED")
    print("019B_ANOMALY_FREE_VECTOR_CURRENT_ENDPOINT=RETAINED")
    print("019C_VECTOR_HIGGS_MEDIATOR_ALGEBRA=RETAINED")
    print(f"SELECTED_F_EV={selected_f:.15e}")
    print(f"SELECTED_THETA_EARTH={selected_theta:.15e}")

    print("\n=== A — PURE ABELIAN LINK PHASE-BLINDNESS ===")
    # For fixed moduli/charges, the canonical Abelian gauge mass matrix contains
    # q_i q_i^T |v_i|^2 only.  Demonstrate phase independence with a nontrivial
    # two-link numerical reconstruction.
    charges = (
        np.array([1.0, -2.0]),
        np.array([3.0, 1.0]),
    )
    vevs = (1.7, 0.9)
    couplings = np.array([0.71, 1.13])

    def abelian_mass_from_links(phases: tuple[float, float]) -> np.ndarray:
        # phases are deliberately unused after |D Sigma|^2 is formed.
        del phases
        result = np.zeros((2, 2), dtype=float)
        for q, v in zip(charges, vevs, strict=True):
            gq = couplings * q
            result += v * v * np.outer(gq, gq)
        return result

    abelian_samples = (
        (0.0, 0.0),
        (0.173, -0.287),
        (1.6, 3.125),
        (-0.625, 5.0),
    )
    abelian_ref = abelian_mass_from_links(abelian_samples[0])
    abelian_max_drift = max(
        np.linalg.norm(abelian_mass_from_links(p) - abelian_ref, ord=np.inf)
        for p in abelian_samples[1:]
    )
    abelian_phase_blind = abelian_max_drift <= 1.0e-14

    print("ABELIAN_CANONICAL_MASS_FORM=sum_i(v_i^2*g_a*g_b*q_ia*q_ib)")
    print(f"ABELIAN_PHASE_SCAN_MAX_MATRIX_DRIFT={abelian_max_drift:.15e}")
    print(f"PURE_ABELIAN_LINK_VECTOR_MASS_PHASE_BLINDNESS={'PASS' if abelian_phase_blind else 'FAIL'}")
    print("PURE_ABELIAN_PHASE_ONLY_TREE_MTHETA=ZERO")

    print("\n=== B — CONVENTIONAL EIGENVALUE-SPLITTING NATURALNESS ===")
    g_product_max = 4.0 * math.pi
    split_ratios = {}
    for margin in (1.0, 1.5, 2.0, 3.0):
        mass = margin * MATERIAL_EFT_CUTOFF
        ratio = conventional_split_naturalness_ratio(mass, g_product_max)
        split_ratios[margin] = ratio
        print(
            f"SPLIT_MARGIN_{str(margin).replace('.', 'P')}_"
            f"DM2_PER_LOG_OVER_TARGET_MPHI2={ratio:.15e}"
        )
    split_2x_fail = split_ratios[2.0] > 1.0
    print(f"CONVENTIONAL_COLLECTIVE_SPLIT_NATURALNESS_AT_2X={'FAIL' if split_2x_fail else 'PASS'}")

    print("\n=== C — IDEAL ISOSPECTRAL ROTATION TARGET MATCH ===")
    m1 = 2.0 * MATERIAL_EFT_CUTOFF
    m2 = 4.0 * MATERIAL_EFT_CUTOFF
    kappa = solve_isospectral_kappa(selected_theta, m1, m2, selected_f)
    beta_earth = kappa * math.sin(selected_theta)
    c_match = isospectral_cphi(selected_theta, kappa, m1, m2, selected_f)
    analytic_deriv = isospectral_inverse_cross_derivative_analytic(
        selected_theta,
        kappa,
        m1,
        m2,
    )
    fd_deriv = finite_difference_cross_derivative(
        selected_theta,
        kappa,
        m1,
        m2,
    )
    deriv_relerr = relerr(analytic_deriv, fd_deriv)

    theta_samples = np.linspace(-0.5, 0.5, 41)
    eig_ref = np.linalg.eigvalsh(isospectral_mass2(0.0, kappa, m1, m2))
    tr2_ref = float(np.trace(isospectral_mass2(0.0, kappa, m1, m2)))
    tr4_ref = float(np.trace(isospectral_mass2(0.0, kappa, m1, m2) ** 2))

    max_eig_rel_drift = 0.0
    max_tr2_rel_drift = 0.0
    max_tr4_rel_drift = 0.0
    for theta in theta_samples:
        mat = isospectral_mass2(theta, kappa, m1, m2)
        eig = np.linalg.eigvalsh(mat)
        max_eig_rel_drift = max(
            max_eig_rel_drift,
            float(np.max(np.abs(eig - eig_ref) / np.maximum(np.abs(eig_ref), 1.0e-300))),
        )
        max_tr2_rel_drift = max(
            max_tr2_rel_drift,
            relerr(float(np.trace(mat)), tr2_ref),
        )
        max_tr4_rel_drift = max(
            max_tr4_rel_drift,
            relerr(float(np.trace(mat @ mat)), tr4_ref),
        )

    isospectral_pass = (
        relerr(c_match, TARGET_C_PHI) <= MAX_RELERR
        and deriv_relerr <= MAX_RELERR
        and max_eig_rel_drift <= MAX_SPECTRAL_DRIFT
        and max_tr2_rel_drift <= MAX_SPECTRAL_DRIFT
        and max_tr4_rel_drift <= MAX_SPECTRAL_DRIFT
        and abs(kappa) <= MAX_ROTATION_KAPPA
    )

    print(f"ISOSPECTRAL_M1_EV={m1:.15e}")
    print(f"ISOSPECTRAL_M2_EV={m2:.15e}")
    print(f"ISOSPECTRAL_KAPPA={kappa:.15e}")
    print(f"ISOSPECTRAL_BETA_EARTH={beta_earth:.15e}")
    print(f"ISOSPECTRAL_C_RECONSTRUCTED={c_match:.15e}")
    print(f"ISOSPECTRAL_C_MATCH_RELERR={relerr(c_match, TARGET_C_PHI):.15e}")
    print(f"ISOSPECTRAL_DMINV_ANALYTIC={analytic_deriv:.15e}")
    print(f"ISOSPECTRAL_DMINV_FINITE_DIFFERENCE={fd_deriv:.15e}")
    print(f"ISOSPECTRAL_DERIVATIVE_RELERR={deriv_relerr:.15e}")
    print(f"ISOSPECTRAL_MAX_EIGENVALUE_REL_DRIFT={max_eig_rel_drift:.15e}")
    print(f"ISOSPECTRAL_MAX_TR_M2_REL_DRIFT={max_tr2_rel_drift:.15e}")
    print(f"ISOSPECTRAL_MAX_TR_M4_REL_DRIFT={max_tr4_rel_drift:.15e}")
    print(f"IDEAL_ISOSPECTRAL_VECTOR_RESPONSE={'PASS' if isospectral_pass else 'FAIL'}")
    print("PURE_VECTOR_CW_THETA_DEPENDENCE_FOR_IDEAL_ISOSPECTRAL_SECTOR=ZERO_BY_SPECTRUM")

    print("\n=== BLIND WILDCARD MASS-RATIO DIAGNOSTICS — NOT EVIDENCE ===")
    for ratio in BLIND_WILDCARD_MASS_RATIOS:
        wildcard_m2 = ratio * m1
        try:
            wildcard_kappa = solve_isospectral_kappa(
                selected_theta,
                m1,
                wildcard_m2,
                selected_f,
            )
            wildcard_c = isospectral_cphi(
                selected_theta,
                wildcard_kappa,
                m1,
                wildcard_m2,
                selected_f,
            )
            print(
                "WILDCARD_RATIO="
                f"{ratio:.6f} "
                f"KAPPA={wildcard_kappa:.15e} "
                f"C_RELERR={relerr(wildcard_c, TARGET_C_PHI):.15e} "
                f"M2_OVER_EFT={wildcard_m2 / MATERIAL_EFT_CUTOFF:.6f}"
            )
        except RuntimeError:
            print(f"WILDCARD_RATIO={ratio:.6f} NO_TARGET_SOLUTION_BELOW_KAPPA_1")
    print("BLIND_WILDCARD_VALUES_USED_AS_EVIDENCE=NO")

    print("\n=== D — ACTUAL 019C BRIDGE CHARGE / ROTATOR AUDIT ===")
    q_plus = np.array([1, 1], dtype=int)
    q_minus = np.array([1, -1], dtype=int)
    q_bilinear = q_minus - q_plus
    neutral_rotator = np.array([0, 0], dtype=int)
    required_rotator = -q_bilinear

    neutral_can_mix = np.array_equal(neutral_rotator + q_bilinear, np.zeros(2, dtype=int))
    charged_spurion_required = not neutral_can_mix

    print(f"S_PLUS_CHARGE_B_L={tuple(int(x) for x in q_plus)}")
    print(f"S_MINUS_CHARGE_B_L={tuple(int(x) for x in q_minus)}")
    print(f"SPLUS_DAGGER_SMINUS_CHARGE_B_L={tuple(int(x) for x in q_bilinear)}")
    print(f"REQUIRED_ROTATOR_CHARGE_B_L={tuple(int(x) for x in required_rotator)}")
    print(f"GAUGE_NEUTRAL_CONTINUOUS_ROTATOR_CAN_MIX_SPLUS_SMINUS={'YES' if neutral_can_mix else 'NO'}")
    print(f"ADDITIONAL_CHARGED_SPURION_REQUIRED={'YES' if charged_spurion_required else 'NO'}")

    minimal_abelian_structural_fail = abelian_phase_blind and charged_spurion_required
    print(
        "MINIMAL_ABELIAN_PHASE_ONLY_NEUTRAL_ROTATOR_CLASS="
        f"{'STRUCTURALLY_REJECTED' if minimal_abelian_structural_fail else 'NOT_REJECTED'}"
    )

    print("\n=== E — MINIMAL RENORMALIZABLE SU2 ISOSPECTRAL REPRESENTATION ===")
    rng = np.random.default_rng(20260831)
    pauli_identity_max = 0.0
    for _ in range(32):
        phi = rng.normal(size=3)
        Phi = su2_adjoint_matrix(phi)
        lhs = Phi @ Phi
        rhs = 0.25 * float(phi @ phi) * np.eye(2, dtype=complex)
        pauli_identity_max = max(
            pauli_identity_max,
            float(np.linalg.norm(lhs - rhs, ord=np.inf)),
        )

    g_x = 0.83
    u = 7.3
    v = 4.1
    su2_ref = np.linalg.eigvalsh(su2_vector_mass2(0.0, g_x, u, v))
    su2_max_eig_drift = 0.0
    for beta in np.linspace(-math.pi, math.pi, 73):
        eig = np.linalg.eigvalsh(su2_vector_mass2(beta, g_x, u, v))
        su2_max_eig_drift = max(
            su2_max_eig_drift,
            float(np.max(np.abs(eig - su2_ref) / np.maximum(np.abs(su2_ref), 1.0e-300))),
        )

    su2_rep_pass = (
        pauli_identity_max <= 1.0e-12
        and su2_max_eig_drift <= MAX_SPECTRAL_DRIFT
    )

    print(f"SU2_PHI_SQUARED_IDENTITY_MAX_ABS_ERROR={pauli_identity_max:.15e}")
    print("SU2_H_DAGGER_PHI_H=ODD_UNDER_PHI_TO_MINUS_PHI")
    print("SU2_H_DAGGER_PHI2_H=ORIENTATION_INDEPENDENT")
    print("SU2_EXACT_PHI_Z2_FORBIDS_ORIENTATION_CUBIC=YES")
    print(f"SU2_VECTOR_SPECTRUM_MAX_REL_DRIFT={su2_max_eig_drift:.15e}")
    print(f"SU2_RENORMALIZABLE_ISOSPECTRAL_REPRESENTATION={'PASS' if su2_rep_pass else 'FAIL'}")

    print("\n=== F — DIRECT SU2 PNGB / CURRENT TWO-SCALE BOUND ===")
    f_rel_min = EARTH_PHI / 0.5
    c_direct_su2_upper = 1.0 / f_rel_min**3
    direct_deficit = TARGET_C_PHI / c_direct_su2_upper
    direct_su2_fail = c_direct_su2_upper < TARGET_C_PHI

    print(f"EARTH_EXCURSION_F_REL_MIN_EV={f_rel_min:.15e}")
    print(f"DIRECT_SU2_C_PHI_ABSOLUTE_UPPER_EV_MINUS3={c_direct_su2_upper:.15e}")
    print(f"DIRECT_SU2_TARGET_DEFICIT_FACTOR={direct_deficit:.15e}")
    print(f"DIRECT_SU2_RELATIVE_ANGLE_AS_5KM_SCALAR={'REJECTED_BY_SCALING' if direct_su2_fail else 'NOT_REJECTED'}")
    print("BOUND_SCOPE=DIRECT_SU2_CURRENT_COUPLING_WITH_SAME_RELATIVE_ANGLE_AS_ULTRALIGHT_SCALAR")

    print("\n=== 020A1 DECISION ===")
    if not isospectral_pass or not su2_rep_pass:
        print("020A1_COLLECTIVE_ISOSPECTRAL_VECTOR_REPRESENTATION_GATE=RED")
        print("REASON=INTERNAL_RECONSTRUCTION_OR_REPRESENTATION_WITNESS_FAILED")
        print("NEXT=DEBUG_BEFORE_ANY_MODEL_ESCALATION")
    elif minimal_abelian_structural_fail and direct_su2_fail:
        print("020A1_COLLECTIVE_ISOSPECTRAL_VECTOR_REPRESENTATION_GATE=GREEN_NEGATIVE_RESULT")
        print("IDEAL_ISOSPECTRAL_CURRENT_KERNEL=SUPPORTED")
        print("MINIMAL_ABELIAN_PHASE_ONLY_TREE_SEED=STRUCTURALLY_REJECTED")
        print("CONVENTIONAL_EIGENVALUE_SPLIT=REJECTED_BY_ULTRALIGHT_NATURALNESS")
        print("MINIMAL_SU2_ISOSPECTRAL_VECTOR_REPRESENTATION=SUPPORTED")
        print("DIRECT_SU2_PNGB_CURRENT_PORTAL=REJECTED_BY_TWO_SCALE_SCALING")
        print("COMPLETE_MICROSCOPIC_VECTOR_WILSON_UV_WITNESS=NO")
        print("CURRENT_KNOWLEDGE_HEURISTIC=APPROXIMATELY_68_PERCENT_NOT_A_PROBABILITY")
        print("HEURISTIC_CHANGE=NONE")
        print("NEXT=020A2_EXTERNAL_WILSON_TO_SU2_ISOSPECTRAL_ROTATION_COLLECTIVE_TRANSFER_GATE")
    else:
        print("020A1_COLLECTIVE_ISOSPECTRAL_VECTOR_REPRESENTATION_GATE=INCONCLUSIVE")
        print("NEXT=REVIEW_STRUCTURAL_ASSUMPTIONS_BEFORE_ESCALATION")

    print("019A_WILSON_LINE_UV_PROTECTION_WITNESS=RETAINED")
    print("019B_ANOMALY_FREE_VECTOR_CURRENT_ENDPOINT=RETAINED")
    print("019C_RENORMALIZABLE_VECTOR_HIGGS_MEDIATOR_SECTOR=RETAINED")
    print("EXACT_2026_5KM_EXPERIMENTAL_BOUND=DEFER_UNTIL_COMPLETE_PORTAL_EXISTS")
    print("REAL_ANTIGRAVITY_MATERIAL=NO")
    print("PRACTICAL_ANTIGRAVITY_DEVICE=NO")
    print("NEW_PHYSICS_DISCOVERY=NO")
    print("CLAIM_CLASSIFICATION=PROJECT_DERIVED_020A1_COLLECTIVE_ISOSPECTRAL_VECTOR_REPRESENTATION_GATE")


if __name__ == "__main__":
    main()
