"""
031D2-B — dynamic reciprocal auxiliary-gate wall

D2A showed that a canonical gate has raw mass-shift capacity, but its
declared gate radius was imposed rather than generated by the field
equations and its energy ledger omitted the positive s^2 phi^2 overlap.

This run repairs that.

Model:

    V_s = lambda_s/4 (s^2-v_s^2)^2

    V_int = 1/2 g_s^2 s^2 phi^2

with

    z = s/v_s.

The reciprocal exterior equations are

    u'' + 2u'/x
      = [epsilon^2 + delta^2 z^2] u

    z'' + 2z'/x
      = [a_s^2(z^2-1) + b_s^2 u^2] z

where

    delta^2 = (g_s v_s/m_X)^2

    a_s^2 = lambda_s v_s^2/m_X^2

    b_s^2 = g_s^2 M_c^2/m_X^2.

The Q-ball/source region is not re-solved here.
Instead the gate wall is required to form far outside the source/payload,
and the exterior solution is matched onto the already-certified on-state
scalar tail.

Promotion means:
- dynamically generated wall outside payload;
- reciprocal u/z wall BVP converges;
- full positive gate wall + interaction energy is small;
- gate backreaction at the matching boundary is small;
- same-Q off-state tachyon is stabilized with margin;
- no obvious source-scale loop/naturalness catastrophe in the chosen
  corrected candidate.

Full y/u/z source coupling and switching remain subsequent gates.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import math
import sys
from pathlib import Path
from typing import Any

import numpy as np

from scipy.integrate import quad, solve_bvp
from scipy.optimize import brentq


ROOT = Path(__file__).resolve().parents[1]
SIM = ROOT / "simulations"
DATA = ROOT / "results" / "data"

QBALL_SOURCE = (
    SIM
    / "031b2a_global_qball_activated_scalar_control.py"
)

ROBUST_SUMMARY = (
    DATA
    / "031c96_operating_margin_robustness_summary.json"
)

LOW_SUMMARY = (
    DATA
    / "031d1r2_lowbranch_offstate_hessian_summary.json"
)

D1HR_SUMMARY = (
    DATA
    / "031d1hr_highbranch_certificate_summary.json"
)

D2A_SUMMARY = (
    DATA
    / "031d2a_auxiliary_gate_capacity_summary.json"
)

OUT_JSON = (
    DATA
    / "031d2b_dynamic_gate_wall_summary.json"
)

OUT_SCAN = (
    DATA
    / "031d2b_corrected_gate_scan.csv"
)

OUT_WALL = (
    DATA
    / "031d2b_gate_wall_convergence.csv"
)


HBARC_EV_M = 1.973269804e-7
J_PER_EV = 1.602176634e-19

X_MATCH = 80.0

STABILIZATION_MARGIN = 1.20

G_MAX = math.sqrt(
    4.0 * math.pi
)

G_VALUES = np.geomspace(
    1.0e-12,
    G_MAX,
    320,
)

WALL_CAPS_M = (
    0.10,
    0.25,
    0.50,
    1.00,
)

WALL_MASS_MARGIN = 1.05

ON_CURVATURE_MARGIN = 10.0

NATURALNESS_BACKGROUND_MARGIN = 3.0

SOURCE_LOOP_RATIO_MAX = 0.10

GATE_ENERGY_FRACTION_MAX = 0.01

PAYLOAD_WALL_CLEARANCE_M = 0.10

MATCH_HALF_WINDOWS_X = (
    250.0,
    300.0,
    350.0,
)

WALL_ENERGY_CONVERGENCE_REL = 0.03
WALL_RADIUS_CONVERGENCE_REL = 0.01
LEFT_DERIVATIVE_MISMATCH_MAX = 5.0e-3


def require(path: Path):
    if not path.is_file():
        raise RuntimeError(
            f"Missing required file: {path}"
        )


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(
        name,
        path,
    )

    if spec is None or spec.loader is None:
        raise RuntimeError(
            f"Cannot import {path}"
        )

    module = importlib.util.module_from_spec(
        spec
    )

    sys.modules[name] = module
    spec.loader.exec_module(module)

    return module


def builtin(value: Any):
    if isinstance(value, np.generic):
        return value.item()

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, dict):
        return {
            str(key): builtin(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            builtin(item)
            for item in value
        ]

    return value


def relerr(a: float, b: float):
    return abs(a - b) / max(
        abs(a),
        abs(b),
        1.0e-300,
    )


def main():
    print(
        "=== 031D2-B DYNAMIC RECIPROCAL GATE-WALL GATE ==="
    )

    print(
        "PRESCRIBED_GATE_RADIUS=NO"
    )

    print(
        "PRESCRIBED_SPATIAL_MPHI=NO"
    )

    print(
        "POSITIVE_S2_PHI2_INTERACTION_INCLUDED=YES"
    )

    print(
        "FULL_Y_U_Z_SOURCE_BVP=NO"
    )

    print(
        "SWITCHING_RESET_CLOSED=NO"
    )

    print(
        "PRACTICAL_DEVICE=NO"
    )

    for path in (
        QBALL_SOURCE,
        ROBUST_SUMMARY,
        LOW_SUMMARY,
        D1HR_SUMMARY,
        D2A_SUMMARY,
    ):
        require(path)

    robust = json.loads(
        ROBUST_SUMMARY.read_text()
    )

    low = json.loads(
        LOW_SUMMARY.read_text()
    )

    d1hr = json.loads(
        D1HR_SUMMARY.read_text()
    )

    d2a = json.loads(
        D2A_SUMMARY.read_text()
    )

    if not bool(
        robust.get(
            "family_operating_robustness_green",
            False,
        )
    ):
        raise RuntimeError(
            "031C96 robust operating family is not GREEN"
        )

    if not bool(
        d1hr.get(
            "gate_free_same_Q_offstate_route_closed",
            False,
        )
    ):
        raise RuntimeError(
            "031D1 gate-free off-state closure missing"
        )

    if not str(
        d2a.get(
            "classification",
            "",
        )
    ).startswith(
        "GREEN_D2A"
    ):
        raise RuntimeError(
            "031D2A capacity preflight is not GREEN"
        )

    candidate = robust[
        "candidate"
    ]

    operating = robust[
        "interior_20pct_margin_point"
    ]

    quadrature = robust[
        "quadrature"
    ][
        "high_order_result"
    ]

    nominal_geometry = next(
        row
        for row in robust[
            "geometry_scan"
        ]
        if row["label"] == "nominal"
    )

    omega = float(
        candidate["omega"]
    )

    epsilon = float(
        candidate["epsilon"]
    )

    chi = float(
        candidate["chi"]
    )

    m_x_gev = float(
        candidate[
            "m_x_gev_derived"
        ]
    )

    m_x_ev = (
        m_x_gev
        * 1.0e9
    )

    m_phi_ev = (
        epsilon
        * m_x_ev
    )

    F_gev = float(
        quadrature[
            "F_gev"
        ]
    )

    M_c_gev = (
        F_gev
        / chi
    )

    M_c_ev = (
        M_c_gev
        * 1.0e9
    )

    operating_energy_j = float(
        operating[
            "energy_J"
        ]
    )

    source_shift_m = float(
        operating[
            "shift_m"
        ]
    )

    payload_center_m = float(
        nominal_geometry[
            "payload_center_m"
        ]
    )

    payload_radius_m = float(
        nominal_geometry[
            "payload_radius_m"
        ]
    )

    payload_center_from_source_m = abs(
        payload_center_m
        - source_shift_m
    )

    payload_far_m = (
        payload_center_from_source_m
        + payload_radius_m
    )

    critical_hat = float(
        low[
            "critical_positive_delta_m2_hat"
        ]
    )

    required_hat = (
        STABILIZATION_MARGIN
        * critical_hat
    )

    required_delta_m_ev = (
        m_x_ev
        * math.sqrt(
            required_hat
        )
    )

    epsilon_off = math.sqrt(
        epsilon**2
        + required_hat
    )

    stabilized_lambda0 = (
        float(
            low[
                "finest_lambda0"
            ]
        )
        + required_hat
    )

    print(
        f"M_X_EV={m_x_ev:.15e}"
    )

    print(
        f"M_PHI_EV={m_phi_ev:.15e}"
    )

    print(
        f"M_C_GEV={M_c_gev:.15e}"
    )

    print(
        f"REQUIRED_DELTA_M2_HAT="
        f"{required_hat:.15e}"
    )

    print(
        f"REQUIRED_GV_EV="
        f"{required_delta_m_ev:.15e}"
    )

    print(
        f"OFF_EPSILON="
        f"{epsilon_off:.15e}"
    )

    print(
        f"OFF_HESSIAN_LAMBDA0_WITH_MARGIN="
        f"{stabilized_lambda0:+.15e}"
    )

    print(
        f"PAYLOAD_FAR_RADIUS_FROM_SOURCE_M="
        f"{payload_far_m:.12f}"
    )

    qmod = load_module(
        "qball031d2b",
        QBALL_SOURCE,
    )

    old_x_match = float(
        qmod.X_MATCH
    )

    qmod.X_MATCH = X_MATCH

    try:
        print(
            "\n=== STAGE A: RECONSTRUCT ON-STATE PROFILE ==="
        )

        seed = qmod.solve_uncoupled_qball(
            omega
        )

        if seed is None:
            raise RuntimeError(
                "Failed Q-ball seed"
            )

        solution = qmod.solve_coupled(
            seed,
            omega,
            epsilon,
            chi,
            previous=None,
        )

        if solution is None:
            raise RuntimeError(
                "Failed coupled Q-ball reconstruction"
            )

        u_center = abs(
            float(
                solution.sol(
                    1.0e-5
                )[2]
            )
        )

        u80 = float(
            solution.sol(
                X_MATCH
            )[2]
        )

        up80 = float(
            solution.sol(
                X_MATCH
            )[3]
        )

        x_length_m = (
            HBARC_EV_M
            / m_x_ev
        )

        payload_far_x = (
            payload_far_m
            / x_length_m
        )

        u_payload_far = abs(
            float(
                solution.sol(
                    payload_far_x
                )[2]
            )
        )

        phi_center_ev = (
            M_c_ev
            * u_center
        )

        phi_payload_far_ev = (
            M_c_ev
            * u_payload_far
        )

        print(
            f"U_CENTER={u_center:.15e}"
        )

        print(
            f"U_XMATCH={u80:.15e}"
        )

        print(
            f"UP_XMATCH={up80:.15e}"
        )

        print(
            f"PHI_CENTER_EV="
            f"{phi_center_ev:.15e}"
        )

        print(
            f"PHI_PAYLOAD_FAR_EV="
            f"{phi_payload_far_ev:.15e}"
        )

        def u_light(x):
            x = np.asarray(
                x,
                dtype=float,
            )

            return (
                u80
                * X_MATCH
                / x
                * np.exp(
                    -epsilon
                    * (
                        x
                        - X_MATCH
                    )
                )
            )

        def up_light(x):
            value = u_light(
                x
            )

            return (
                -epsilon
                -1.0 / x
            ) * value

        def phi_ev_at_x(x):
            if x <= X_MATCH:
                return (
                    M_c_ev
                    * abs(
                        float(
                            solution.sol(
                                max(
                                    x,
                                    1.0e-5,
                                )
                            )[2]
                        )
                    )
                )

            return (
                M_c_ev
                * abs(
                    float(
                        u_light(
                            x
                        )
                    )
                )
            )

        print(
            "\n=== STAGE B: CORRECTED GATE PARAMETER SCAN ==="
        )

        scan_rows = []

        for wall_cap_m in WALL_CAPS_M:
            m_s_ev = (
                WALL_MASS_MARGIN
                * HBARC_EV_M
                / wall_cap_m
            )

            for g_s in G_VALUES:
                v_s_ev = (
                    required_delta_m_ev
                    / g_s
                )

                lambda_s = (
                    m_s_ev**2
                    /
                    (
                        2.0
                        * v_s_ev**2
                    )
                )

                if (
                    lambda_s
                    <= 0.0
                    or
                    lambda_s
                    > 4.0 * math.pi
                ):
                    continue

                on_ratio_far = (
                    g_s**2
                    * phi_payload_far_ev**2
                    /
                    (
                        lambda_s
                        * v_s_ev**2
                    )
                )

                phi_transition_ev = (
                    m_s_ev
                    /
                    (
                        math.sqrt(2.0)
                        * g_s
                    )
                )

                if (
                    phi_transition_ev
                    >= phi_payload_far_ev
                ):
                    continue

                x_lo = max(
                    payload_far_x,
                    X_MATCH,
                )

                def transition_eq(x):
                    return (
                        phi_ev_at_x(x)
                        - phi_transition_ev
                    )

                x_hi = max(
                    2.0 * x_lo,
                    200.0,
                )

                while (
                    transition_eq(
                        x_hi
                    ) > 0.0
                    and
                    x_hi < 1.0e6
                ):
                    x_hi *= 1.5

                if transition_eq(
                    x_hi
                ) > 0.0:
                    continue

                x_transition = brentq(
                    transition_eq,
                    x_lo,
                    x_hi,
                    xtol=1.0e-9,
                    rtol=1.0e-10,
                )

                r_transition_m = (
                    x_transition
                    * x_length_m
                )

                geometry_pass = bool(
                    r_transition_m
                    >=
                    payload_far_m
                    + PAYLOAD_WALL_CLEARANCE_M
                )

                naive_nat_scale_ev = (
                    4.0
                    * math.pi
                    * m_s_ev
                    / g_s
                )

                on_gate_mass_center_ev = (
                    g_s
                    * phi_center_ev
                )

                background_nat_ratio = (
                    naive_nat_scale_ev
                    / max(
                        on_gate_mass_center_ev,
                        1.0e-300,
                    )
                )

                phi_loop_ratio_at_mx = (
                    g_s**2
                    /
                    (
                        16.0
                        * math.pi**2
                        * epsilon**2
                    )
                )

                gate_loop_ratio_at_mx = (
                    g_s**2
                    * m_x_ev**2
                    /
                    (
                        16.0
                        * math.pi**2
                        * m_s_ev**2
                    )
                )

                lambda_loop_est = (
                    g_s**4
                    /
                    (
                        16.0
                        * math.pi**2
                    )
                )

                naturalness_preflight_pass = bool(
                    background_nat_ratio
                    >=
                    NATURALNESS_BACKGROUND_MARGIN
                    and
                    phi_loop_ratio_at_mx
                    <= SOURCE_LOOP_RATIO_MAX
                    and
                    gate_loop_ratio_at_mx
                    <= SOURCE_LOOP_RATIO_MAX
                    and
                    lambda_loop_est
                    <= lambda_s
                )

                volume_nat = (
                    4.0
                    / 3.0
                    * math.pi
                    * (
                        r_transition_m
                        / HBARC_EV_M
                    )**3
                )

                wall_area_nat = (
                    4.0
                    * math.pi
                    * (
                        r_transition_m
                        / HBARC_EV_M
                    )**2
                )

                wall_width_nat = (
                    wall_cap_m
                    / HBARC_EV_M
                )

                bare_density_ev4 = (
                    lambda_s
                    * v_s_ev**4
                    / 4.0
                )

                volume_floor_j = (
                    bare_density_ev4
                    * volume_nat
                    * J_PER_EV
                )

                gradient_floor_j = (
                    wall_area_nat
                    * v_s_ev**2
                    /
                    (
                        2.0
                        * wall_width_nat
                    )
                    * J_PER_EV
                )

                estimated_floor_j = (
                    volume_floor_j
                    + gradient_floor_j
                )

                energy_fraction = (
                    estimated_floor_j
                    / operating_energy_j
                )

                energy_pass = bool(
                    energy_fraction
                    <=
                    GATE_ENERGY_FRACTION_MAX
                )

                candidate_pass = bool(
                    geometry_pass
                    and
                    on_ratio_far
                    >= ON_CURVATURE_MARGIN
                    and
                    naturalness_preflight_pass
                    and
                    energy_pass
                )

                scan_rows.append(
                    {
                        "g_s":
                            float(g_s),

                        "v_s_eV":
                            v_s_ev,

                        "lambda_s":
                            lambda_s,

                        "m_s_eV":
                            m_s_ev,

                        "wall_cap_m":
                            wall_cap_m,

                        "phi_transition_eV":
                            phi_transition_ev,

                        "x_transition":
                            x_transition,

                        "r_transition_m":
                            r_transition_m,

                        "on_curvature_ratio_far_payload":
                            on_ratio_far,

                        "naive_naturalness_scale_eV":
                            naive_nat_scale_ev,

                        "on_gate_mass_center_eV":
                            on_gate_mass_center_ev,

                        "background_naturalness_ratio":
                            background_nat_ratio,

                        "phi_loop_ratio_at_mX":
                            phi_loop_ratio_at_mx,

                        "gate_loop_ratio_at_mX":
                            gate_loop_ratio_at_mx,

                        "lambda_loop_est":
                            lambda_loop_est,

                        "volume_floor_J":
                            volume_floor_j,

                        "gradient_floor_J":
                            gradient_floor_j,

                        "estimated_gate_floor_J":
                            estimated_floor_j,

                        "estimated_energy_fraction":
                            energy_fraction,

                        "candidate_pass":
                            candidate_pass,
                    }
                )

        passing = [
            row
            for row in scan_rows
            if bool(
                row[
                    "candidate_pass"
                ]
            )
        ]

        print(
            f"CORRECTED_SCAN_CASES="
            f"{len(scan_rows)}"
        )

        print(
            f"STRICT_PASSING_CASES="
            f"{len(passing)}"
        )

        if not passing:
            classification = (
                "RED_D2B_NO_CORRECTED_CANONICAL_GATE_WINDOW"
            )

            print(
                f"031D2B_CLASSIFICATION="
                f"{classification}"
            )

            print(
                "NEXT=031D3_ALTERNATE_ACTIVATION_FIELD"
            )

            summary = {
                "classification":
                    classification,
                "passing_count":
                    0,
            }

            OUT_JSON.write_text(
                json.dumps(
                    summary,
                    indent=2,
                )
                + "\n"
            )

            fields = sorted(
                {
                    key
                    for row in scan_rows
                    for key in row
                }
            )

            with OUT_SCAN.open(
                "w",
                newline="",
            ) as handle:
                writer = csv.DictWriter(
                    handle,
                    fieldnames=fields,
                )
                writer.writeheader()
                writer.writerows(
                    scan_rows
                )

            return

        best = min(
            passing,
            key=lambda row:
                float(
                    row[
                        "estimated_gate_floor_J"
                    ]
                ),
        )

        print(
            "\n=== STAGE C: CORRECTED BEST CANDIDATE ==="
        )

        for key in (
            "g_s",
            "v_s_eV",
            "lambda_s",
            "m_s_eV",
            "wall_cap_m",
            "phi_transition_eV",
            "r_transition_m",
            "on_curvature_ratio_far_payload",
            "naive_naturalness_scale_eV",
            "on_gate_mass_center_eV",
            "background_naturalness_ratio",
            "phi_loop_ratio_at_mX",
            "gate_loop_ratio_at_mX",
            "estimated_gate_floor_J",
        ):
            print(
                f"BEST_{key.upper()}="
                f"{best[key]:.15e}"
            )

        g_s = float(
            best["g_s"]
        )

        v_s_ev = float(
            best["v_s_eV"]
        )

        lambda_s = float(
            best["lambda_s"]
        )

        m_s_ev = float(
            best["m_s_eV"]
        )

        x_transition = float(
            best["x_transition"]
        )

        a2 = (
            lambda_s
            * v_s_ev**2
            / m_x_ev**2
        )

        b2 = (
            g_s**2
            * M_c_ev**2
            / m_x_ev**2
        )

        delta2 = (
            g_s
            * v_s_ev
            / m_x_ev
        )**2

        print(
            f"A2_GATE={a2:.15e}"
        )

        print(
            f"B2_GATE={b2:.15e}"
        )

        print(
            f"DELTA2_GATE={delta2:.15e}"
        )

        print(
            "\n=== STAGE D: RECIPROCAL U/Z WALL BVP ==="
        )

        wall_rows = []

        def solve_wall(
            half_window_x: float,
        ):
            x_left = max(
                X_MATCH,
                x_transition
                - half_window_x,
            )

            x_right = (
                x_transition
                + half_window_x
            )

            grid = np.linspace(
                x_left,
                x_right,
                2200,
            )

            u_guess = u_light(
                grid
            )

            wall_scale_x = max(
                m_s_ev
                / m_x_ev,
                1.0e-8,
            )

            width_x = (
                1.0
                / wall_scale_x
            )

            logistic_arg = np.clip(
                (
                    grid
                    - x_transition
                )
                / max(
                    width_x,
                    1.0e-6,
                ),
                -60.0,
                60.0,
            )

            z_guess = (
                1.0
                /
                (
                    1.0
                    + np.exp(
                        -logistic_arg
                    )
                )
            )

            zp_guess = (
                z_guess
                * (
                    1.0
                    - z_guess
                )
                / max(
                    width_x,
                    1.0e-6,
                )
            )

            up_guess = (
                -epsilon
                -1.0 / grid
            ) * u_guess

            guess = np.vstack(
                (
                    u_guess,
                    up_guess,
                    z_guess,
                    zp_guess,
                )
            )

            u_left = float(
                u_light(
                    x_left
                )
            )

            def equations(
                x,
                state,
            ):
                u = state[0]
                z = state[2]

                return np.vstack(
                    (
                        state[1],

                        (
                            epsilon**2
                            + delta2
                            * z**2
                        )
                        * u
                        - 2.0
                        * state[1]
                        / x,

                        state[3],

                        (
                            a2
                            * (
                                z**2
                                - 1.0
                            )
                            + b2
                            * u**2
                        )
                        * z
                        - 2.0
                        * state[3]
                        / x,
                    )
                )

            def boundary(
                left,
                right,
            ):
                return np.array(
                    (
                        left[0]
                        - u_left,

                        left[2],

                        right[1]
                        + (
                            epsilon_off
                            + 1.0
                            / x_right
                        )
                        * right[0],

                        right[2]
                        - 1.0,
                    ),
                    dtype=float,
                )

            result = solve_bvp(
                equations,
                boundary,
                grid,
                guess,
                tol=1.0e-6,
                max_nodes=100_000,
                verbose=0,
            )

            if not result.success:
                raise RuntimeError(
                    "Wall BVP failed for "
                    f"half_window={half_window_x}: "
                    f"{result.message}"
                )

            sample = np.linspace(
                x_left,
                x_right,
                30_000,
            )

            state = result.sol(
                sample
            )

            u = np.asarray(
                state[0],
                dtype=float,
            )

            up = np.asarray(
                state[1],
                dtype=float,
            )

            z = np.asarray(
                state[2],
                dtype=float,
            )

            zp = np.asarray(
                state[3],
                dtype=float,
            )

            if np.any(
                np.diff(z) < -1.0e-4
            ):
                raise RuntimeError(
                    "Gate wall is materially nonmonotone"
                )

            z_clipped = np.maximum.accumulate(
                np.clip(
                    z,
                    0.0,
                    1.0,
                )
            )

            x10 = float(
                np.interp(
                    0.10,
                    z_clipped,
                    sample,
                )
            )

            x50 = float(
                np.interp(
                    0.50,
                    z_clipped,
                    sample,
                )
            )

            x90 = float(
                np.interp(
                    0.90,
                    z_clipped,
                    sample,
                )
            )

            gate_prefactor_j = (
                4.0
                * math.pi
                * v_s_ev**2
                / m_x_ev
                * J_PER_EV
            )

            grad_density = (
                0.5
                * zp**2
            )

            potential_density = (
                a2
                / 4.0
                * (
                    z**2
                    - 1.0
                )**2
            )

            interaction_density = (
                0.5
                * b2
                * z**2
                * u**2
            )

            def integrate_gate(
                density,
            ):
                return (
                    gate_prefactor_j
                    * np.trapezoid(
                        sample**2
                        * density,
                        sample,
                    )
                )

            interior_false_j = (
                gate_prefactor_j
                * a2
                / 4.0
                * x_left**3
                / 3.0
            )

            gradient_j = integrate_gate(
                grad_density
            )

            wall_potential_j = integrate_gate(
                potential_density
            )

            interaction_local_j = integrate_gate(
                interaction_density
            )

            u_right = float(
                result.sol(
                    x_right
                )[0]
            )

            interaction_outer_integral = (
                0.5
                * b2
                * u_right**2
                * x_right**2
                / (
                    2.0
                    * epsilon_off
                )
            )

            interaction_outer_j = (
                gate_prefactor_j
                * interaction_outer_integral
            )

            gate_total_j = (
                interior_false_j
                + gradient_j
                + wall_potential_j
                + interaction_local_j
                + interaction_outer_j
            )

            scalar_prefactor_j = (
                4.0
                * math.pi
                * M_c_ev**2
                / m_x_ev
                * J_PER_EV
            )

            scalar_new_local_j = (
                scalar_prefactor_j
                * np.trapezoid(
                    sample**2
                    * (
                        0.5
                        * up**2
                        + 0.5
                        * epsilon**2
                        * u**2
                    ),
                    sample,
                )
            )

            up_right_factor = (
                epsilon_off
            )

            def scalar_outer_integrand(
                x,
            ):
                uo = (
                    u_right
                    * x_right
                    / x
                    * math.exp(
                        -epsilon_off
                        * (
                            x
                            - x_right
                        )
                    )
                )

                upo = (
                    -epsilon_off
                    -1.0 / x
                ) * uo

                return (
                    x**2
                    * (
                        0.5
                        * upo**2
                        + 0.5
                        * epsilon**2
                        * uo**2
                    )
                )

            scalar_new_outer_j = (
                scalar_prefactor_j
                * quad(
                    scalar_outer_integrand,
                    x_right,
                    np.inf,
                    epsabs=1.0e-12,
                    epsrel=1.0e-8,
                    limit=300,
                )[0]
            )

            def scalar_old_integrand(
                x,
            ):
                uo = float(
                    u_light(
                        x
                    )
                )

                upo = (
                    -epsilon
                    -1.0 / x
                ) * uo

                return (
                    x**2
                    * (
                        0.5
                        * upo**2
                        + 0.5
                        * epsilon**2
                        * uo**2
                    )
                )

            scalar_old_tail_j = (
                scalar_prefactor_j
                * quad(
                    scalar_old_integrand,
                    x_left,
                    np.inf,
                    epsabs=1.0e-12,
                    epsrel=1.0e-8,
                    limit=300,
                )[0]
            )

            scalar_new_tail_j = (
                scalar_new_local_j
                + scalar_new_outer_j
            )

            scalar_tail_delta_j = (
                scalar_new_tail_j
                - scalar_old_tail_j
            )

            new_up_left = float(
                result.sol(
                    x_left
                )[1]
            )

            old_up_left = float(
                up_light(
                    x_left
                )
            )

            derivative_mismatch = relerr(
                new_up_left,
                old_up_left,
            )

            return {
                "half_window_x":
                    half_window_x,

                "x_left":
                    x_left,

                "x_right":
                    x_right,

                "x10":
                    x10,

                "x50":
                    x50,

                "x90":
                    x90,

                "r10_m":
                    x10
                    * x_length_m,

                "r50_m":
                    x50
                    * x_length_m,

                "r90_m":
                    x90
                    * x_length_m,

                "wall_10_90_width_m":
                    (
                        x90
                        - x10
                    )
                    * x_length_m,

                "left_derivative_mismatch":
                    derivative_mismatch,

                "left_z_prime":
                    float(
                        result.sol(
                            x_left
                        )[3]
                    ),

                "right_z_prime":
                    float(
                        result.sol(
                            x_right
                        )[3]
                    ),

                "interior_false_vacuum_J":
                    interior_false_j,

                "gradient_J":
                    gradient_j,

                "wall_potential_J":
                    wall_potential_j,

                "interaction_local_J":
                    interaction_local_j,

                "interaction_outer_J":
                    interaction_outer_j,

                "gate_total_positive_J":
                    gate_total_j,

                "scalar_old_tail_J":
                    scalar_old_tail_j,

                "scalar_new_tail_J":
                    scalar_new_tail_j,

                "scalar_tail_delta_J":
                    scalar_tail_delta_j,

                "conservative_total_energy_J":
                    operating_energy_j
                    + gate_total_j,

                "matched_total_energy_J":
                    operating_energy_j
                    + gate_total_j
                    + scalar_tail_delta_j,
            }

        for half_window in (
            MATCH_HALF_WINDOWS_X
        ):
            row = solve_wall(
                half_window
            )

            wall_rows.append(
                row
            )

            print(
                f"WALL "
                f"HALF_X={half_window:.3f} "
                f"R50_M={row['r50_m']:.9f} "
                f"WIDTH10_90_M="
                f"{row['wall_10_90_width_m']:.9f} "
                f"GATE_J="
                f"{row['gate_total_positive_J']:.9e} "
                f"INTERACTION_J="
                f"{row['interaction_local_J'] + row['interaction_outer_J']:.9e} "
                f"DERIV_MISMATCH="
                f"{row['left_derivative_mismatch']:.6e}"
            )

        gate_energies = np.array(
            [
                row[
                    "gate_total_positive_J"
                ]
                for row in wall_rows
            ],
            dtype=float,
        )

        wall_radii = np.array(
            [
                row["r50_m"]
                for row in wall_rows
            ],
            dtype=float,
        )

        derivative_mismatches = np.array(
            [
                row[
                    "left_derivative_mismatch"
                ]
                for row in wall_rows
            ],
            dtype=float,
        )

        gate_energy_spread = (
            np.max(
                gate_energies
            )
            - np.min(
                gate_energies
            )
        ) / max(
            np.mean(
                gate_energies
            ),
            1.0e-300,
        )

        wall_radius_spread = (
            np.max(
                wall_radii
            )
            - np.min(
                wall_radii
            )
        ) / max(
            np.mean(
                wall_radii
            ),
            1.0e-300,
        )

        max_derivative_mismatch = float(
            np.max(
                derivative_mismatches
            )
        )

        reference = wall_rows[
            len(
                wall_rows
            ) // 2
        ]

        gate_fraction = (
            reference[
                "gate_total_positive_J"
            ]
            / operating_energy_j
        )

        wall_outside_payload = bool(
            reference[
                "r10_m"
            ]
            >
            payload_far_m
            + PAYLOAD_WALL_CLEARANCE_M
        )

        bvp_converged = bool(
            gate_energy_spread
            <= WALL_ENERGY_CONVERGENCE_REL
            and
            wall_radius_spread
            <= WALL_RADIUS_CONVERGENCE_REL
            and
            max_derivative_mismatch
            <= LEFT_DERIVATIVE_MISMATCH_MAX
        )

        off_stability_pass = bool(
            stabilized_lambda0
            > 0.0
        )

        gate_energy_pass = bool(
            gate_fraction
            <= GATE_ENERGY_FRACTION_MAX
        )

        print(
            "\n=== STAGE E: DECISION ==="
        )

        print(
            f"WALL_RADIUS_REL_SPREAD="
            f"{wall_radius_spread:.15e}"
        )

        print(
            f"GATE_ENERGY_REL_SPREAD="
            f"{gate_energy_spread:.15e}"
        )

        print(
            f"MAX_LEFT_DERIVATIVE_MISMATCH="
            f"{max_derivative_mismatch:.15e}"
        )

        print(
            f"DYNAMIC_WALL_OUTSIDE_PAYLOAD="
            f"{wall_outside_payload}"
        )

        print(
            f"EXTERIOR_RECIPROCAL_BVP_CONVERGED="
            f"{bvp_converged}"
        )

        print(
            f"OFF_STATE_LINEAR_STABILIZATION_PASS="
            f"{off_stability_pass}"
        )

        print(
            f"REFERENCE_GATE_TOTAL_POSITIVE_J="
            f"{reference['gate_total_positive_J']:.15e}"
        )

        print(
            f"REFERENCE_GATE_ENERGY_FRACTION="
            f"{gate_fraction:.15e}"
        )

        print(
            f"REFERENCE_INTERACTION_ENERGY_J="
            f"{reference['interaction_local_J'] + reference['interaction_outer_J']:.15e}"
        )

        print(
            f"REFERENCE_SCALAR_TAIL_DELTA_J="
            f"{reference['scalar_tail_delta_J']:+.15e}"
        )

        print(
            f"CONSERVATIVE_TOTAL_WITH_GATE_GJ="
            f"{reference['conservative_total_energy_J'] / 1.0e9:.12f}"
        )

        if (
            bvp_converged
            and
            wall_outside_payload
            and
            off_stability_pass
            and
            gate_energy_pass
        ):
            classification = (
                "GREEN_D2B_DYNAMIC_RECIPROCAL_GATE_WALL_EXISTS_"
                "WITH_SMALL_POSITIVE_ENERGY_AT_EXTERNAL_FIELD_LEVEL"
            )

            next_action = (
                "031D2C_FULL_FIXED_Q_COUPLED_Y_U_Z_ON_OFF_"
                "SOURCE_BVP_PLUS_SWITCHING_BARRIER"
            )

        else:
            classification = (
                "YELLOW_D2B_DYNAMIC_GATE_WALL_NOT_YET_CLOSED"
            )

            next_action = (
                "REFINE_ONLY_FAILED_D2B_SUBGATE"
            )

        print(
            f"031D2B_CLASSIFICATION="
            f"{classification}"
        )

        print(
            f"NEXT={next_action}"
        )

        print(
            "FULL_Y_U_Z_SOURCE_BVP_CLOSED=NO"
        )

        print(
            "SWITCHING_BARRIER_CLOSED=NO"
        )

        print(
            "FORMATION_RESET_ENERGY_CLOSED=NO"
        )

        print(
            "FULL_METRIC_BACKREACTION_CLOSED=NO"
        )

        print(
            "RADIATIVE_NATURALNESS_CLOSED=NO"
        )

        print(
            "PRACTICAL_DEVICE=NO"
        )

        summary = {
            "classification":
                classification,

            "next":
                next_action,

            "corrected_scan_count":
                len(scan_rows),

            "strict_passing_count":
                len(passing),

            "best_corrected_candidate":
                best,

            "off_state": {
                "required_delta_m2_hat":
                    required_hat,

                "stabilized_lambda0":
                    stabilized_lambda0,

                "pass":
                    off_stability_pass,
            },

            "wall_convergence": {
                "rows":
                    wall_rows,

                "wall_radius_rel_spread":
                    wall_radius_spread,

                "gate_energy_rel_spread":
                    gate_energy_spread,

                "max_left_derivative_mismatch":
                    max_derivative_mismatch,

                "bvp_converged":
                    bvp_converged,
            },

            "reference_wall":
                reference,

            "claim_limits": [
                (
                    "This solves the reciprocal exterior phi/s wall, "
                    "not the complete y/u/z microscopic source."
                ),
                (
                    "The wall radius emerges dynamically rather than "
                    "being prescribed."
                ),
                (
                    "Positive s^2 phi^2 interaction energy is included."
                ),
                (
                    "No credit from reduced scalar-tail energy is "
                    "required for the conservative total."
                ),
                (
                    "The naturalness tests here are source-scale "
                    "preflight diagnostics only."
                ),
                (
                    "Switching/nucleation, reset and radiation remain "
                    "open."
                ),
                (
                    "Full metric backreaction and empirical closure "
                    "remain open."
                ),
                (
                    "No practical device is established."
                ),
            ],
        }

        OUT_JSON.write_text(
            json.dumps(
                builtin(summary),
                indent=2,
                sort_keys=True,
            )
            + "\n"
        )

        scan_fields = sorted(
            {
                key
                for row in scan_rows
                for key in row
            }
        )

        with OUT_SCAN.open(
            "w",
            newline="",
        ) as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=scan_fields,
            )

            writer.writeheader()
            writer.writerows(
                scan_rows
            )

        wall_fields = sorted(
            {
                key
                for row in wall_rows
                for key in row
            }
        )

        with OUT_WALL.open(
            "w",
            newline="",
        ) as handle:
            writer = csv.DictWriter(
                handle,
                fieldnames=wall_fields,
            )

            writer.writeheader()
            writer.writerows(
                wall_rows
            )

        print(
            f"SUMMARY_JSON={OUT_JSON}"
        )

        print(
            f"SCAN_CSV={OUT_SCAN}"
        )

        print(
            f"WALL_CSV={OUT_WALL}"
        )

    finally:
        qmod.X_MATCH = old_x_match


if __name__ == "__main__":
    main()
