#!/usr/bin/env python3
"""
031E — full physical-metric / Einstein-backreaction survival gate.

Purpose
-------
031D3D2-R closed the activation/control stage at the driven adiabatic
multiscale level.

031E asks whether the microscopic ON field still produces outward finite-
payload motion after including its ordinary attractive Einstein metric and
using the one physical Jordan metric directly.

The ON endpoint contains:

    X source
    phi scalar
    Y activation

At the endpoint:

    R = 0
    S = 0

so reservoir and mixer endpoint stress-energy vanish.

The soliton is self-supported. No mechanical support is inserted into the
primary isolated-source solution.

Energy bookkeeping
------------------
The actual Einstein source is the EXACT Hamiltonian stress tensor.

The approximately 127.8-GJ conservative inventory remains the project's
engineering upper ledger, but is NOT substituted for T_munu. Doing that would
double count the interaction/binding term already present in the exact
Hamiltonian.

Physical metric
---------------
Ordinary neutral matter follows

    gtilde_mn = A_m^2 g_mn

with

    A_m = exp[ f(a) phi^2 / (2 M_m^2) ]

and

    phi = M_c u.

For the spherical Einstein-frame metric

    ds^2 =
        -exp(2 nu) c^2 dt^2
        + dr^2/(1-C)
        + r^2 dOmega^2,

    C(r)=2 G m(r)/(r c^2),

the physical Jordan metric is

    d_stilde^2 = A_m^2 ds^2.

The local radial acceleration of a neutral particle released from rest is
computed directly from the Jordan lapse:

    Ntilde = A_m exp(nu),

    a_hat_r =
        -c^2 sqrt(1-C)/A_m
        * d_r [ nu + ln A_m ].

No external fifth-force term is added by hand.

Einstein equations
------------------
Using the complete exact endpoint stress tensor,

    dm/dr
      = 4 pi r^2 rho_E / c^2,

    dnu/dr
      =
      G [ m + 4 pi r^3 p_r/c^2 ]
      /
      [ r^2 c^2 (1-C) ].

Because the expected compactness is far below double precision relative to
the O(1) matter fields, 031E does NOT pretend to resolve a 1e-32 change in
y,u,a directly.

Instead:

1. reconstruct full T_munu independently;
2. solve the Einstein metric from that T_munu without subtracting unity;
3. measure the physical metric perturbation;
4. compare it with the already certified R5 physical spectral gap;
5. quantify the covariant-conservation source term generated by curvature;
6. evaluate the Jordan geodesic exactly on that metric.

A GREEN result is therefore a WEAK-CURVATURE PERTURBATIVE BACKREACTION
CERTIFICATE.

It is not a claim that float64 directly resolved the fully curved matter
profiles at relative order 1e-32.

Still open after GREEN
----------------------
- carrier-resolved nonlinear switching dynamics;
- nonlinear fragmentation;
- higher-harmonic / multiparticle radiation;
- EFT / radiative naturalness;
- empirical fifth-force / EP / PPN closure;
- laboratory support hardware;
- practical device.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import math
from pathlib import Path
import sys
from typing import Any

import numpy as np

from numpy.polynomial.legendre import leggauss

from scipy.integrate import (
    cumulative_trapezoid,
)

from scipy.interpolate import PchipInterpolator


ROOT = Path(__file__).resolve().parents[1]
SIM = ROOT / "simulations"
DATA = ROOT / "results" / "data"

DATA.mkdir(
    parents=True,
    exist_ok=True,
)

D3D2R_SUMMARY = (
    DATA
    / "031d3d2r_dual_ledger_fixed_theory_summary.json"
)

R5_SUMMARY = (
    DATA
    / "031d3cr5_saturation_safe_schur_summary.json"
)

D3AR2_SUMMARY = (
    DATA
    / "031d3ar2_physical_metric_summary.json"
)

D3D0_SUMMARY = (
    DATA
    / "031d3d0_exact_conserved_charge_reservoir_summary.json"
)

C96_SUMMARY = (
    DATA
    / "031c96_operating_margin_robustness_summary.json"
)

R4_SOURCE = (
    SIM
    / "031d3cr4_relative_translation_ward_closeout.py"
)

OUT_JSON = (
    DATA
    / "031e_full_physical_metric_einstein_backreaction_summary.json"
)

OUT_PROFILE = (
    DATA
    / "031e_einstein_jordan_metric_profile.csv"
)

OUT_PAYLOAD = (
    DATA
    / "031e_finite_payload_metric_scan.csv"
)


G = 6.67430e-11
C_LIGHT = 299_792_458.0

HBARC_EV_M = 1.973269804e-7

PAYLOAD_MASS_KG = 1.0

METRIC_XMAX = 1200.0

FAR_FIELD_MAX_M = 300.0

PAYLOAD_RADIAL_ORDER = 56
PAYLOAD_ANGULAR_ORDER = 72

MAX_ENERGY_RELERR = 2.0e-5

MAX_NUMERICAL_CONSERVATION_RELERR = 3.0e-3

MAX_DEC_EXCESS = 3.0e-5

MAX_CM_REFERENCE_RELERR = 5.0e-3

MAX_SURFACE_REFERENCE_RELERR = 1.5e-2

MAX_SELF_METRIC_OVER_GAP = 1.0e-7

MAX_PAYLOAD_METRIC_OVER_GAP = 1.0e-4

MAX_PAYLOAD_SCALAR_REACTION = 1.0e-10

MAX_GR_FRACTION_OF_OUTWARD = 1.0e-10

MAX_COMPACTNESS = 1.0e-12

MAX_SOURCE_OVERLAP = 1.0e-20


def require(
    path: Path,
) -> None:

    if not path.is_file():

        raise RuntimeError(
            f"Missing required artifact: {path}"
        )


def load_json(
    path: Path,
) -> dict[str, Any]:

    return json.loads(
        path.read_text()
    )


def load_module(
    name: str,
    path: Path,
):

    spec = (
        importlib.util.spec_from_file_location(
            name,
            path,
        )
    )

    if (
        spec is None
        or spec.loader is None
    ):

        raise RuntimeError(
            f"Cannot import {path}"
        )

    module = (
        importlib.util.module_from_spec(
            spec
        )
    )

    sys.modules[
        name
    ] = module

    try:

        spec.loader.exec_module(
            module
        )

    except Exception:

        sys.modules.pop(
            name,
            None,
        )

        raise

    return module


def relerr(
    a: float,
    b: float,
    floor: float = 1.0e-300,
) -> float:

    return (
        abs(
            a - b
        )
        / max(
            abs(
                a
            ),
            abs(
                b
            ),
            floor,
        )
    )


def builtin(
    value: Any,
) -> Any:

    if isinstance(
        value,
        dict,
    ):

        return {
            str(
                key
            ):
            builtin(
                child
            )
            for key, child
            in value.items()
        }

    if isinstance(
        value,
        (
            list,
            tuple,
        ),
    ):

        return [
            builtin(
                child
            )
            for child
            in value
        ]

    if isinstance(
        value,
        np.ndarray,
    ):

        return value.tolist()

    if isinstance(
        value,
        (
            np.floating,
            np.integer,
            np.bool_,
        ),
    ):

        return value.item()

    return value


def W(
    z,
):

    z = np.asarray(
        z,
        dtype=float,
    )

    return (
        0.5
        * np.log1p(
            z
            * z
        )
    )


def activation_fraction(
    a,
):

    a = np.asarray(
        a,
        dtype=float,
    )

    return -np.expm1(
        -0.5
        * a
        * a
    )


def activation_fraction_prime(
    a,
):

    a = np.asarray(
        a,
        dtype=float,
    )

    return (
        a
        * np.exp(
            -0.5
            * a
            * a
        )
    )


def make_metric_grid() -> np.ndarray:

    return np.unique(
        np.concatenate(
            (
                np.linspace(
                    1.0e-5,
                    20.0,
                    8000,
                ),

                np.linspace(
                    20.0,
                    120.0,
                    8000,
                ),

                np.linspace(
                    120.0,
                    500.0,
                    8000,
                ),

                np.linspace(
                    500.0,
                    METRIC_XMAX,
                    8000,
                ),
            )
        )
    )


def weighted_l2(
    x,
    value,
) -> float:

    x = np.asarray(
        x,
        dtype=float,
    )

    value = np.asarray(
        value,
        dtype=float,
    )

    return float(
        math.sqrt(
            max(
                np.trapezoid(
                    x
                    * x
                    * value
                    * value,
                    x,
                ),
                0.0,
            )
        )
    )


def main() -> None:

    print(
        "=== 031E FULL PHYSICAL-METRIC / EINSTEIN-BACKREACTION GATE ==="
    )

    print(
        "CLAIM_CLASS="
        "WEAK_CURVATURE_EINSTEIN_JORDAN_GEODESIC_BACKREACTION_CERTIFICATE"
    )

    print(
        "D3D2R_DRIVEN_ADIABATIC_CLOSEOUT_REQUIRED=YES"
    )

    print(
        "EXACT_HAMILTONIAN_SOURCES_EINSTEIN_METRIC=YES"
    )

    print(
        "CONSERVATIVE_INVENTORY_USED_AS_T_MUNU=NO"
    )

    print(
        "DIRECT_JORDAN_GEODESIC_USED=YES"
    )

    print(
        "EXTERNAL_FIFTH_FORCE_ADDED_BY_HAND=NO"
    )

    print(
        "MECHANICAL_SUPPORT_USED_IN_PRIMARY_ISOLATED_SOURCE=NO"
    )

    print(
        "PRACTICAL_DEVICE=NO"
    )

    for path in (
        D3D2R_SUMMARY,
        R5_SUMMARY,
        D3AR2_SUMMARY,
        D3D0_SUMMARY,
        C96_SUMMARY,
        R4_SOURCE,
    ):

        require(
            path
        )

    d2r = load_json(
        D3D2R_SUMMARY
    )

    r5 = load_json(
        R5_SUMMARY
    )

    d3ar2 = load_json(
        D3AR2_SUMMARY
    )

    d0 = load_json(
        D3D0_SUMMARY
    )

    c96 = load_json(
        C96_SUMMARY
    )

    d3d_green = bool(
        str(
            d2r.get(
                "classification",
                "",
            )
        ).startswith(
            "GREEN_D3D2R"
        )

        and

        d2r[
            "decision"
        ][
            "full_D3D_driven_adiabatic_closeout"
        ]
    )

    if not d3d_green:

        raise RuntimeError(
            "031E unauthorized: D3D2-R is not GREEN"
        )

    metric_green = bool(
        str(
            d3ar2.get(
                "classification",
                "",
            )
        ).startswith(
            "GREEN_D3AR2"
        )
    )

    if not metric_green:

        raise RuntimeError(
            "031E unauthorized: physical-metric normalization is not GREEN"
        )

    nominal_geometry = next(
        row
        for row
        in c96[
            "geometry_scan"
        ]
        if row[
            "label"
        ]
        == "nominal"
    )

    payload_center_global_m = float(
        nominal_geometry[
            "payload_center_m"
        ]
    )

    payload_radius_m = float(
        nominal_geometry[
            "payload_radius_m"
        ]
    )

    source_shift_m = float(
        nominal_geometry[
            "shift_m"
        ]
    )

    payload_center_from_source_m = abs(
        payload_center_global_m
        - source_shift_m
    )

    reference_cm = float(
        nominal_geometry[
            "a_cm_mps2"
        ]
    )

    reference_surface_min = float(
        nominal_geometry[
            "surface_min_mps2"
        ]
    )

    inherited_overlap = float(
        nominal_geometry[
            "conservative_overlap"
        ]
    )

    exact_source_on_J = float(
        d2r[
            "dual_ledger"
        ][
            "exact_source_ON_J"
        ]
    )

    exact_on_J = float(
        d2r[
            "dual_ledger"
        ][
            "exact_ON_J"
        ]
    )

    conservative_on_J = float(
        d2r[
            "dual_ledger"
        ][
            "conservative_ON_J"
        ]
    )

    activation_energy_J = float(
        d0[
            "reservoir_qball"
        ][
            "rest_energy_J"
        ]
    )

    m_x_eV = float(
        d0[
            "model"
        ][
            "m_x_eV"
        ]
    )

    M_c_GeV = float(
        d3ar2[
            "reconstructed"
        ][
            "M_c_GeV"
        ]
    )

    M_m_GeV = float(
        d3ar2[
            "reconstructed"
        ][
            "M_m_GeV"
        ]
    )

    matter_ratio_sq = (
        M_c_GeV
        / M_m_GeV
    ) ** 2

    payload_scalar_reaction = float(
        d3ar2[
            "payload"
        ][
            "correct_reaction_ratio"
        ]
    )

    model = r5[
        "model"
    ]

    omega_x = float(
        model[
            "omega_x"
        ]
    )

    omega_y = float(
        model[
            "omega_y"
        ]
    )

    epsilon = float(
        model[
            "epsilon"
        ]
    )

    chi = float(
        model[
            "chi"
        ]
    )

    mu = float(
        model[
            "mu"
        ]
    )

    rho_y = float(
        model[
            "rho_y"
        ]
    )

    target_qx = float(
        model[
            "target_I_QX"
        ]
    )

    target_qy = float(
        model[
            "target_I_QY"
        ]
    )

    physical_gap = float(
        r5[
            "schur"
        ][
            "relaxed_relative_lower_bound"
        ]
    )

    x_length_m = (
        HBARC_EV_M
        / m_x_eV
    )

    print(
        "\n=== STAGE A: PROVENANCE / GEOMETRY ==="
    )

    print(
        f"D3D2R_CLASSIFICATION={d2r['classification']}"
    )

    print(
        f"EXACT_SOURCE_ON_J={exact_source_on_J:.15e}"
    )

    print(
        f"EXACT_ON_TOTAL_J={exact_on_J:.15e}"
    )

    print(
        f"CONSERVATIVE_ON_INVENTORY_J={conservative_on_J:.15e}"
    )

    print(
        f"M_X_EV={m_x_eV:.15e}"
    )

    print(
        f"X_LENGTH_M={x_length_m:.15e}"
    )

    print(
        f"M_C_GEV={M_c_GeV:.15e}"
    )

    print(
        f"M_M_GEV={M_m_GeV:.15e}"
    )

    print(
        f"MC_OVER_MM_SQUARED={matter_ratio_sq:.15e}"
    )

    print(
        f"PAYLOAD_CENTER_GLOBAL_M={payload_center_global_m:.15e}"
    )

    print(
        f"SOURCE_SHIFT_M={source_shift_m:.15e}"
    )

    print(
        "PAYLOAD_CENTER_FROM_SOURCE_M="
        f"{payload_center_from_source_m:.15e}"
    )

    print(
        f"PAYLOAD_RADIUS_M={payload_radius_m:.15e}"
    )

    print(
        f"REFERENCE_FLAT_CM_MPS2={reference_cm:.15e}"
    )

    print(
        "REFERENCE_FLAT_SURFACE_MIN_MPS2="
        f"{reference_surface_min:.15e}"
    )

    print(
        f"INHERITED_X_OVERLAP={inherited_overlap:.15e}"
    )

    print(
        "\n=== STAGE B: FULL D3B ENDPOINT RECONSTRUCTION ===",
        flush=True,
    )

    r4 = load_module(
        "r4_for_031e",
        R4_SOURCE,
    )

    d3b = load_module(
        "d3b_for_031e",
        r4.D3B_SOURCE,
    )

    qmod = load_module(
        "qball_for_031e",
        r4.QBALL_SOURCE,
    )

    d3a = load_module(
        "d3a_for_031e",
        r4.D3A_SOURCE,
    )

    (
        product80,
        source80,
        activation80,
    ) = (
        r4.build_product_background(
            qmod,
            d3a,
            omega_x,
            omega_y,
            epsilon,
            chi,
            mu,
            r4.X_SOURCE_MATCH,
        )
    )

    (
        _coarse,
        _fine,
        tight,
        _homotopy,
        _diag_c,
        _diag_f,
        diag_t,
    ) = (
        r4.reconstruct_full_background(
            d3b,
            qmod,
            d3a,
            product80,
            source80,
            activation80,
            omega_x_seed=omega_x,
            omega_y_seed=omega_y,
            epsilon=epsilon,
            chi=chi,
            mu=mu,
            rho_y=rho_y,
            target_qx=target_qx,
            target_qy=target_qy,
        )
    )

    del (
        product80,
        source80,
        activation80,
    )

    background_pass = bool(
        diag_t[
            "qx_relerr"
        ]
        <= r4.MAX_BVP_CHARGE_RELERR

        and

        diag_t[
            "qy_relerr"
        ]
        <= r4.MAX_BVP_CHARGE_RELERR

        and

        diag_t[
            "max_rms_residual"
        ]
        <= r4.MAX_BVP_RMS
    )

    evaluator = (
        r4.full_solution_evaluator(
            tight,
            epsilon,
            mu,
        )
    )

    omega_x = float(
        tight.p[
            0
        ]
    )

    omega_y = float(
        tight.p[
            1
        ]
    )

    print(
        f"OMEGA_X={omega_x:.15e}"
    )

    print(
        f"OMEGA_Y={omega_y:.15e}"
    )

    print(
        f"BVP_QX_RELERR={diag_t['qx_relerr']:.15e}"
    )

    print(
        f"BVP_QY_RELERR={diag_t['qy_relerr']:.15e}"
    )

    print(
        f"BVP_RMS={diag_t['max_rms_residual']:.15e}"
    )

    print(
        f"FULL_D3B_RECONSTRUCTION_PASS={background_pass}"
    )

    print(
        "\n=== STAGE C: COMPLETE EXACT T_MUNU ===",
        flush=True,
    )

    x = make_metric_grid()

    (
        y,
        yp,
        u,
        up,
        a,
        ap,
    ) = evaluator(
        x
    )

    f = activation_fraction(
        a
    )

    fp = activation_fraction_prime(
        a
    )

    A_x = np.exp(
        -0.5
        * f
        * u
        * u
    )

    W_y = W(
        y
    )

    W_a = W(
        a
    )

    rho_X = (
        0.5
        * yp
        * yp

        + 0.5
        * omega_x
        * omega_x
        * y
        * y

        + A_x
        * W_y
    )

    pr_X = (
        0.5
        * yp
        * yp

        + 0.5
        * omega_x
        * omega_x
        * y
        * y

        - A_x
        * W_y
    )

    pt_X = (
        -0.5
        * yp
        * yp

        + 0.5
        * omega_x
        * omega_x
        * y
        * y

        - A_x
        * W_y
    )

    rho_phi = (
        0.5
        * (
            up
            * up
            + epsilon
            * epsilon
            * u
            * u
        )
        / (
            chi
            * chi
        )
    )

    pr_phi = (
        0.5
        * (
            up
            * up
            - epsilon
            * epsilon
            * u
            * u
        )
        / (
            chi
            * chi
        )
    )

    pt_phi = (
        -0.5
        * (
            up
            * up
            + epsilon
            * epsilon
            * u
            * u
        )
        / (
            chi
            * chi
        )
    )

    rho_Y = (
        rho_y
        * (
            0.5
            * ap
            * ap

            + 0.5
            * mu
            * mu
            * omega_y
            * omega_y
            * a
            * a

            + mu
            * mu
            * W_a
        )
    )

    pr_Y = (
        rho_y
        * (
            0.5
            * ap
            * ap

            + 0.5
            * mu
            * mu
            * omega_y
            * omega_y
            * a
            * a

            - mu
            * mu
            * W_a
        )
    )

    pt_Y = (
        rho_y
        * (
            -0.5
            * ap
            * ap

            + 0.5
            * mu
            * mu
            * omega_y
            * omega_y
            * a
            * a

            - mu
            * mu
            * W_a
        )
    )

    rho = (
        rho_X
        + rho_phi
        + rho_Y
    )

    pr = (
        pr_X
        + pr_phi
        + pr_Y
    )

    pt = (
        pt_X
        + pt_phi
        + pt_Y
    )

    I_source = float(
        4.0
        * math.pi
        * np.trapezoid(
            x
            * x
            * (
                rho_X
                + rho_phi
            ),
            x,
        )
    )

    I_Y = float(
        4.0
        * math.pi
        * np.trapezoid(
            x
            * x
            * rho_Y,
            x,
        )
    )

    I_total = (
        I_source
        + I_Y
    )

    energy_scale_J = (
        activation_energy_J
        / I_Y
    )

    source_rebuilt_J = (
        energy_scale_J
        * I_source
    )

    total_rebuilt_J = (
        energy_scale_J
        * I_total
    )

    source_energy_relerr = relerr(
        source_rebuilt_J,
        exact_source_on_J,
    )

    total_energy_relerr = relerr(
        total_rebuilt_J,
        exact_on_J,
    )

    energy_pass = bool(
        source_energy_relerr
        <= MAX_ENERGY_RELERR

        and

        total_energy_relerr
        <= MAX_ENERGY_RELERR
    )

    gradient_anisotropy = (
        yp
        * yp

        + up
        * up
        / (
            chi
            * chi
        )

        + rho_y
        * ap
        * ap
    )

    anisotropy_identity = (
        pr
        - pt
        - gradient_anisotropy
    )

    anisotropy_relerr = (
        weighted_l2(
            x,
            anisotropy_identity,
        )
        / max(
            weighted_l2(
                x,
                gradient_anisotropy,
            ),
            1.0e-300,
        )
    )

    flat_dpr_analytic = (
        -2.0
        * gradient_anisotropy
        / x
    )

    flat_conservation_analytic = (
        flat_dpr_analytic
        + 2.0
        * (
            pr
            - pt
        )
        / x
    )

    flat_conservation_analytic_relerr = (
        weighted_l2(
            x,
            flat_conservation_analytic,
        )
        / max(
            weighted_l2(
                x,
                flat_dpr_analytic,
            ),
            1.0e-300,
        )
    )

    dpr_numeric = np.gradient(
        pr,
        x,
        edge_order=2,
    )

    flat_conservation_numeric = (
        dpr_numeric
        + 2.0
        * (
            pr
            - pt
        )
        / x
    )

    significant = (
        rho
        >
        np.max(
            rho
        )
        * 1.0e-13
    )

    numeric_num = weighted_l2(
        x[
            significant
        ],
        flat_conservation_numeric[
            significant
        ],
    )

    numeric_den = max(
        weighted_l2(
            x[
                significant
            ],
            dpr_numeric[
                significant
            ],
        )
        +
        weighted_l2(
            x[
                significant
            ],
            (
                2.0
                * (
                    pr
                    - pt
                )
                / x
            )[
                significant
            ],
        ),
        1.0e-300,
    )

    flat_conservation_numeric_relerr = (
        numeric_num
        / numeric_den
    )

    with np.errstate(
        divide="ignore",
        invalid="ignore",
    ):

        dec_ratio = (
            np.maximum(
                np.abs(
                    pr
                ),
                np.abs(
                    pt
                ),
            )
            / np.maximum(
                rho,
                1.0e-300,
            )
        )

    dec_ratio = dec_ratio[
        significant
    ]

    dec_max = float(
        np.max(
            dec_ratio
        )
    )

    dec_pass = bool(
        dec_max
        <=
        1.0
        + MAX_DEC_EXCESS

        and

        float(
            np.min(
                rho
            )
        )
        >=
        -1.0e-12
    )

    stress_pass = bool(
        anisotropy_relerr
        <= 2.0e-8

        and

        flat_conservation_analytic_relerr
        <= 2.0e-8

        and

        flat_conservation_numeric_relerr
        <= MAX_NUMERICAL_CONSERVATION_RELERR

        and

        dec_pass
    )

    print(
        f"I_SOURCE_EXACT={I_source:.15e}"
    )

    print(
        f"I_Y_EXACT={I_Y:.15e}"
    )

    print(
        f"ENERGY_SCALE_J={energy_scale_J:.15e}"
    )

    print(
        f"SOURCE_REBUILT_J={source_rebuilt_J:.15e}"
    )

    print(
        f"SOURCE_CERTIFIED_EXACT_J={exact_source_on_J:.15e}"
    )

    print(
        f"SOURCE_ENERGY_RELERR={source_energy_relerr:.15e}"
    )

    print(
        f"TOTAL_REBUILT_J={total_rebuilt_J:.15e}"
    )

    print(
        f"TOTAL_CERTIFIED_EXACT_J={exact_on_J:.15e}"
    )

    print(
        f"TOTAL_ENERGY_RELERR={total_energy_relerr:.15e}"
    )

    print(
        f"EXACT_T_MUNU_ENERGY_PASS={energy_pass}"
    )

    print(
        f"ANISOTROPY_IDENTITY_RELERR={anisotropy_relerr:.15e}"
    )

    print(
        "FLAT_CONSERVATION_ANALYTIC_RELERR="
        f"{flat_conservation_analytic_relerr:.15e}"
    )

    print(
        "FLAT_CONSERVATION_NUMERICAL_RELERR="
        f"{flat_conservation_numeric_relerr:.15e}"
    )

    print(
        f"DEC_MAX_RATIO={dec_max:.15e}"
    )

    print(
        f"COMPLETE_EXACT_STRESS_PASS={stress_pass}"
    )

    print(
        "ON_ENDPOINT_R_RESERVOIR_FIELD=ZERO"
    )

    print(
        "ON_ENDPOINT_S_CONTROL_FIELD=ZERO"
    )

    print(
        "INTRINSIC_MECHANICAL_SUPPORT_REQUIRED=NO_SELF_SUPPORTED_SOLITON"
    )

    print(
        "\n=== STAGE D: SPHERICAL EINSTEIN METRIC ==="
    )

    r = (
        x_length_m
        * x
    )

    energy_density_scale = (
        energy_scale_J
        / (
            x_length_m
            ** 3
        )
    )

    energy_density_phys = (
        energy_density_scale
        * rho
    )

    pr_phys = (
        energy_density_scale
        * pr
    )

    mass_integrand = (
        4.0
        * math.pi
        * energy_scale_J
        / (
            C_LIGHT
            * C_LIGHT
        )
        * x
        * x
        * rho
    )

    enclosed_mass = cumulative_trapezoid(
        mass_integrand,
        x,
        initial=0.0,
    )

    compactness = (
        2.0
        * G
        * enclosed_mass
        / (
            r
            * C_LIGHT
            * C_LIGHT
        )
    )

    max_compactness = float(
        np.max(
            compactness
        )
    )

    pressure_mass = (
        4.0
        * math.pi
        * r
        * r
        * r
        * pr_phys
        / (
            C_LIGHT
            * C_LIGHT
        )
    )

    nu_x = (
        G
        * (
            enclosed_mass
            + pressure_mass
        )
        / (
            x_length_m
            * x
            * x
            * C_LIGHT
            * C_LIGHT
            * (
                1.0
                - compactness
            )
        )
    )

    nu_outer = (
        0.5
        * np.log1p(
            -compactness[
                -1
            ]
        )
    )

    reverse_integral = cumulative_trapezoid(
        nu_x[
            ::-1
        ],
        x[
            ::-1
        ],
        initial=0.0,
    )

    nu = (
        nu_outer
        + reverse_integral
    )[
        ::-1
    ]

    lambda_metric = (
        -0.5
        * np.log1p(
            -compactness
        )
    )

    adm_mass_kg = float(
        enclosed_mass[
            -1
        ]
    )

    adm_energy_J = (
        adm_mass_kg
        * C_LIGHT
        * C_LIGHT
    )

    adm_relerr = relerr(
        adm_energy_J,
        total_rebuilt_J,
    )

    no_horizon = bool(
        max_compactness
        <
        1.0
        and
        np.all(
            np.isfinite(
                nu
            )
        )
    )

    positive_adm = bool(
        adm_mass_kg
        > 0.0
    )

    source_metric_amplitude = max(
        max_compactness,
        float(
            np.max(
                np.abs(
                    nu
                )
            )
        ),
        float(
            np.max(
                np.abs(
                    lambda_metric
                )
            )
        ),
    )

    self_metric_over_gap = (
        source_metric_amplitude
        / physical_gap
    )

    curved_conservation_source = (
        (
            rho
            + pr
        )
        * nu_x
    )

    curved_conservation_source_rel = (
        weighted_l2(
            x,
            curved_conservation_source,
        )
        / max(
            weighted_l2(
                x,
                flat_dpr_analytic,
            ),
            1.0e-300,
        )
    )

    einstein_pass = bool(
        adm_relerr
        <= 5.0e-8

        and

        positive_adm

        and

        no_horizon

        and

        max_compactness
        <= MAX_COMPACTNESS
    )

    perturbative_backreaction_pass = bool(
        self_metric_over_gap
        <= MAX_SELF_METRIC_OVER_GAP
    )

    print(
        f"ADM_MASS_KG={adm_mass_kg:.15e}"
    )

    print(
        f"ADM_ENERGY_J={adm_energy_J:.15e}"
    )

    print(
        f"ADM_ENERGY_RELERR={adm_relerr:.15e}"
    )

    print(
        f"MAX_COMPACTNESS_2GM_RC2={max_compactness:.15e}"
    )

    print(
        f"MAX_ABS_NU={float(np.max(np.abs(nu))):.15e}"
    )

    print(
        "MAX_ABS_EINSTEIN_RADIAL_LOG_FACTOR="
        f"{float(np.max(np.abs(lambda_metric))):.15e}"
    )

    print(
        f"POSITIVE_ADM_MASS={positive_adm}"
    )

    print(
        f"NO_HORIZON_OR_METRIC_SINGULARITY={no_horizon}"
    )

    print(
        "CURVED_CONSERVATION_SOURCE_RELATIVE_SCALE="
        f"{curved_conservation_source_rel:.15e}"
    )

    print(
        f"R5_PHYSICAL_GAP={physical_gap:.15e}"
    )

    print(
        "SELF_METRIC_PERTURBATION_OVER_R5_GAP="
        f"{self_metric_over_gap:.15e}"
    )

    print(
        f"SPHERICAL_EINSTEIN_METRIC_PASS={einstein_pass}"
    )

    print(
        "PERTURBATIVE_MATTER_BACKREACTION_PASS="
        f"{perturbative_backreaction_pass}"
    )

    print(
        "FLOAT64_FULL_CURVED_MATTER_SHIFT_DIRECTLY_RESOLVABLE="
        "NO_EXPECTED_BELOW_MACHINE_RELATIVE_PRECISION"
    )

    print(
        "FULL_NONPERTURBATIVE_CURVED_MATTER_BVP_SOLVED=NO"
    )

    print(
        "BACKREACTION_METHOD="
        "EXACT_EINSTEIN_METRIC_PLUS_CERTIFIED_SMALL_PERTURBATION_OVER_SPECTRAL_GAP"
    )

    mass_interp = PchipInterpolator(
        r,
        enclosed_mass,
        extrapolate=False,
    )

    pr_interp = PchipInterpolator(
        r,
        pr_phys,
        extrapolate=False,
    )

    metric_rmax = float(
        r[
            -1
        ]
    )

    def radial_acceleration(
        radius_m,
    ):

        radius = np.asarray(
            radius_m,
            dtype=float,
        )

        xx = (
            radius
            / x_length_m
        )

        (
            _yy,
            _yyp,
            uu,
            uup,
            aa,
            aap,
        ) = evaluator(
            xx
        )

        ff = activation_fraction(
            aa
        )

        ffa = activation_fraction_prime(
            aa
        )

        log_A_m = (
            0.5
            * matter_ratio_sq
            * ff
            * uu
            * uu
        )

        dlog_A_dx = (
            matter_ratio_sq
            * (
                ff
                * uu
                * uup

                + 0.5
                * ffa
                * aap
                * uu
                * uu
            )
        )

        dlog_A_dr = (
            dlog_A_dx
            / x_length_m
        )

        inside = (
            radius
            <= metric_rmax
        )

        m_local = np.empty_like(
            radius
        )

        p_local = np.empty_like(
            radius
        )

        if np.any(
            inside
        ):

            m_local[
                inside
            ] = mass_interp(
                radius[
                    inside
                ]
            )

            p_local[
                inside
            ] = pr_interp(
                radius[
                    inside
                ]
            )

        if np.any(
            ~inside
        ):

            m_local[
                ~inside
            ] = adm_mass_kg

            p_local[
                ~inside
            ] = 0.0

        C_local = (
            2.0
            * G
            * m_local
            / (
                radius
                * C_LIGHT
                * C_LIGHT
            )
        )

        nu_r = (
            G
            * (
                m_local

                + 4.0
                * math.pi
                * radius
                * radius
                * radius
                * p_local
                / (
                    C_LIGHT
                    * C_LIGHT
                )
            )
            / (
                radius
                * radius
                * C_LIGHT
                * C_LIGHT
                * (
                    1.0
                    - C_local
                )
            )
        )

        prefactor = (
            np.sqrt(
                np.maximum(
                    1.0
                    - C_local,
                    0.0,
                )
            )
            * np.exp(
                -log_A_m
            )
        )

        a_scalar = (
            -C_LIGHT
            * C_LIGHT
            * dlog_A_dr
        )

        a_einstein = (
            -C_LIGHT
            * C_LIGHT
            * nu_r
        )

        a_jordan = (
            -C_LIGHT
            * C_LIGHT
            * prefactor
            * (
                nu_r
                + dlog_A_dr
            )
        )

        return {
            "jordan":
                a_jordan,

            "scalar_flat":
                a_scalar,

            "einstein":
                a_einstein,

            "log_A_m":
                log_A_m,

            "dlog_A_dr":
                dlog_A_dr,

            "compactness":
                C_local,
        }

    print(
        "\n=== STAGE E: DIRECT JORDAN-METRIC FINITE PAYLOAD ==="
    )

    center_eval = radial_acceleration(
        np.array(
            [
                payload_center_from_source_m
            ]
        )
    )

    center_jordan = float(
        center_eval[
            "jordan"
        ][
            0
        ]
    )

    center_scalar = float(
        center_eval[
            "scalar_flat"
        ][
            0
        ]
    )

    center_gr = float(
        center_eval[
            "einstein"
        ][
            0
        ]
    )

    s_nodes, s_weights = leggauss(
        PAYLOAD_RADIAL_ORDER
    )

    mu_nodes, mu_weights = leggauss(
        PAYLOAD_ANGULAR_ORDER
    )

    s = (
        0.5
        * payload_radius_m
        * (
            s_nodes
            + 1.0
        )
    )

    ws = (
        0.5
        * payload_radius_m
        * s_weights
    )

    S, MU = np.meshgrid(
        s,
        mu_nodes,
        indexing="ij",
    )

    rr = np.sqrt(
        payload_center_from_source_m
        * payload_center_from_source_m

        + S
        * S

        + 2.0
        * payload_center_from_source_m
        * S
        * MU
    )

    projection = (
        payload_center_from_source_m
        + S
        * MU
    ) / rr

    volume_eval = radial_acceleration(
        rr.ravel()
    )

    jordan_grid = (
        volume_eval[
            "jordan"
        ].reshape(
            rr.shape
        )
    )

    scalar_grid = (
        volume_eval[
            "scalar_flat"
        ].reshape(
            rr.shape
        )
    )

    gr_grid = (
        volume_eval[
            "einstein"
        ].reshape(
            rr.shape
        )
    )

    weight = (
        2.0
        * math.pi
        * (
            ws
            * s
            * s
        )[
            :,
            None,
        ]
        * mu_weights[
            None,
            :,
        ]
    )

    payload_volume = (
        4.0
        * math.pi
        * payload_radius_m
        ** 3
        / 3.0
    )

    a_cm_jordan = float(
        np.sum(
            weight
            * jordan_grid
            * projection
        )
        / payload_volume
    )

    a_cm_scalar = float(
        np.sum(
            weight
            * scalar_grid
            * projection
        )
        / payload_volume
    )

    a_cm_gr = float(
        np.sum(
            weight
            * gr_grid
            * projection
        )
        / payload_volume
    )

    surface_mu = np.linspace(
        -1.0,
        1.0,
        4001,
    )

    surface_r = np.sqrt(
        payload_center_from_source_m
        * payload_center_from_source_m

        + payload_radius_m
        * payload_radius_m

        + 2.0
        * payload_center_from_source_m
        * payload_radius_m
        * surface_mu
    )

    surface_projection = (
        payload_center_from_source_m
        + payload_radius_m
        * surface_mu
    ) / surface_r

    surface_eval = radial_acceleration(
        surface_r
    )

    surface_projected = (
        surface_eval[
            "jordan"
        ]
        * surface_projection
    )

    surface_min = float(
        np.min(
            surface_projected
        )
    )

    surface_max = float(
        np.max(
            surface_projected
        )
    )

    cm_reference_relerr = relerr(
        a_cm_jordan,
        reference_cm,
    )

    surface_reference_relerr = relerr(
        surface_min,
        reference_surface_min,
    )

    gr_fraction = (
        abs(
            a_cm_gr
        )
        / max(
            abs(
                a_cm_jordan
            ),
            1.0e-300,
        )
    )

    conservative_mass_kg = (
        conservative_on_J
        / (
            C_LIGHT
            * C_LIGHT
        )
    )

    conservative_gr_surface_bound = (
        G
        * conservative_mass_kg
        / (
            (
                payload_center_from_source_m
                - payload_radius_m
            )
            ** 2
        )
    )

    finite_payload_pass = bool(
        a_cm_jordan
        > 0.0

        and

        surface_min
        > 0.0

        and

        cm_reference_relerr
        <= MAX_CM_REFERENCE_RELERR

        and

        surface_reference_relerr
        <= MAX_SURFACE_REFERENCE_RELERR

        and

        gr_fraction
        <= MAX_GR_FRACTION_OF_OUTWARD

        and

        inherited_overlap
        <= MAX_SOURCE_OVERLAP
    )

    print(
        f"CENTER_JORDAN_ACCEL_MPS2={center_jordan:+.15e}"
    )

    print(
        f"CENTER_FLAT_SCALAR_ACCEL_MPS2={center_scalar:+.15e}"
    )

    print(
        f"CENTER_EINSTEIN_ACCEL_MPS2={center_gr:+.15e}"
    )

    print(
        f"PAYLOAD_CM_JORDAN_ACCEL_MPS2={a_cm_jordan:+.15e}"
    )

    print(
        f"PAYLOAD_CM_FLAT_SCALAR_ACCEL_MPS2={a_cm_scalar:+.15e}"
    )

    print(
        f"PAYLOAD_CM_EINSTEIN_ACCEL_MPS2={a_cm_gr:+.15e}"
    )

    print(
        f"PAYLOAD_SURFACE_MIN_MPS2={surface_min:+.15e}"
    )

    print(
        f"PAYLOAD_SURFACE_MAX_MPS2={surface_max:+.15e}"
    )

    print(
        f"CM_REFERENCE_RELERR={cm_reference_relerr:.15e}"
    )

    print(
        "SURFACE_MIN_REFERENCE_RELERR="
        f"{surface_reference_relerr:.15e}"
    )

    print(
        f"GR_FRACTION_OF_TOTAL_CM={gr_fraction:.15e}"
    )

    print(
        "CONSERVATIVE_LEDGER_GR_SURFACE_BOUND_MPS2="
        f"{conservative_gr_surface_bound:.15e}"
    )

    print(
        f"FINITE_PAYLOAD_JORDAN_REPULSION_PASS={finite_payload_pass}"
    )

    print(
        "\n=== STAGE F: FAR FIELD / PAYLOAD BACKREACTION / RECOIL ==="
    )

    far_r = np.geomspace(
        max(
            payload_center_from_source_m
            + payload_radius_m,
            0.2,
        ),
        FAR_FIELD_MAX_M,
        5000,
    )

    far_eval = radial_acceleration(
        far_r
    )

    far_a = far_eval[
        "jordan"
    ]

    zero_radius = math.nan

    for index in range(
        1,
        far_r.size,
    ):

        if (
            far_a[
                index
            ]
            <= 0.0

            and

            far_a[
                index
                - 1
            ]
            > 0.0
        ):

            r0 = far_r[
                index
                - 1
            ]

            r1 = far_r[
                index
            ]

            a0 = far_a[
                index
                - 1
            ]

            a1 = far_a[
                index
            ]

            zero_radius = float(
                r0
                + (
                    0.0
                    - a0
                )
                * (
                    r1
                    - r0
                )
                / (
                    a1
                    - a0
                )
            )

            break

    far_scan_attractive = bool(
        far_a[
            -1
        ]
        < 0.0
    )

    local_repulsive = bool(
        a_cm_jordan
        > 0.0
    )

    positive_adm_farfield = bool(
        adm_mass_kg
        > 0.0
    )

    farfield_pass = bool(
        local_repulsive

        and

        far_scan_attractive

        and

        positive_adm_farfield
    )

    payload_metric_driver = (
        G
        * PAYLOAD_MASS_KG
        / (
            payload_center_from_source_m
            * C_LIGHT
            * C_LIGHT
        )
    )

    payload_metric_over_gap = (
        payload_metric_driver
        / physical_gap
    )

    payload_backreaction_pass = bool(
        payload_metric_over_gap
        <= MAX_PAYLOAD_METRIC_OVER_GAP

        and

        payload_scalar_reaction
        <= MAX_PAYLOAD_SCALAR_REACTION
    )

    interaction_force_N = (
        PAYLOAD_MASS_KG
        * a_cm_jordan
    )

    exact_source_mass_equiv_kg = (
        exact_on_J
        / (
            C_LIGHT
            * C_LIGHT
        )
    )

    free_source_recoil_mps2 = (
        interaction_force_N
        / exact_source_mass_equiv_kg
    )

    print(
        "JORDAN_ACCEL_AT_FAR_SCAN_END_MPS2="
        f"{float(far_a[-1]):+.15e}"
    )

    print(
        f"REPULSIVE_TO_ATTRACTIVE_ZERO_M={zero_radius}"
    )

    print(
        "ASYMPTOTIC_POSITIVE_ADM_ATTRACTION="
        f"{positive_adm_farfield}"
    )

    print(
        f"LOCAL_REPULSIVE_BASIN_PRESENT={local_repulsive}"
    )

    print(
        f"FAR_FIELD_SIGN_PASS={farfield_pass}"
    )

    print(
        f"PAYLOAD_SCALAR_REACTION_RATIO={payload_scalar_reaction:.15e}"
    )

    print(
        f"PAYLOAD_METRIC_DRIVER={payload_metric_driver:.15e}"
    )

    print(
        "PAYLOAD_METRIC_DRIVER_OVER_R5_GAP="
        f"{payload_metric_over_gap:.15e}"
    )

    print(
        f"PAYLOAD_BACKREACTION_PASS={payload_backreaction_pass}"
    )

    print(
        f"ONE_KG_INTERACTION_FORCE_N={interaction_force_N:.15e}"
    )

    print(
        "FREE_SOURCE_RECOIL_DIAGNOSTIC_MPS2="
        f"{free_source_recoil_mps2:.15e}"
    )

    print(
        "SOURCE_RECOIL_INTERPRETATION="
        "CENTER_OF_MASS_TRANSLATION_NOT_INTERNAL_INSTABILITY"
    )

    print(
        "LAB_FIXED_ONE_KG_SUPPORT_FORCE_N="
        f"{interaction_force_N:.15e}"
    )

    print(
        "LAB_FIXED_SUPPORT_APPARATUS_REALIZED=NO"
    )

    print(
        "PRIMARY_031E_CLAIM="
        "ISOLATED_SOURCE_PLUS_FINITE_TEST_PAYLOAD_RELEASED_FROM_REST"
    )

    print(
        "\n=== STAGE G: DECISION ==="
    )

    prerequisites = bool(
        background_pass

        and

        energy_pass

        and

        stress_pass

        and

        einstein_pass

        and

        perturbative_backreaction_pass

        and

        finite_payload_pass

        and

        farfield_pass

        and

        payload_backreaction_pass
    )

    print(
        f"BACKGROUND_PASS={background_pass}"
    )

    print(
        f"EXACT_T_MUNU_PASS={energy_pass and stress_pass}"
    )

    print(
        f"EINSTEIN_METRIC_PASS={einstein_pass}"
    )

    print(
        "MATTER_BACKREACTION_PERTURBATIVE_CERTIFICATE_PASS="
        f"{perturbative_backreaction_pass}"
    )

    print(
        f"JORDAN_FINITE_PAYLOAD_PASS={finite_payload_pass}"
    )

    print(
        f"FAR_FIELD_PASS={farfield_pass}"
    )

    print(
        f"PAYLOAD_REACTION_BACKREACTION_PASS={payload_backreaction_pass}"
    )

    if prerequisites:

        classification = (
            "GREEN_031E_WEAK_CURVATURE_EINSTEIN_"
            "JORDAN_GEODESIC_BACKREACTION_CERTIFICATE"
        )

        next_action = (
            "031F_NONLINEAR_RADIATION_EFT_NATURALNESS_"
            "EMPIRICAL_FINAL_CLOSEOUT"
        )

        promotion = True

    else:

        classification = (
            "YELLOW_OR_RED_031E_PHYSICAL_METRIC_"
            "BACKREACTION_GATE_FAILED"
        )

        next_action = (
            "DIAGNOSE_ONLY_FAILED_031E_TMNUNU_EINSTEIN_"
            "JORDAN_PAYLOAD_OR_BACKREACTION_SUBGATE"
        )

        promotion = False

    print(
        f"031E_CLASSIFICATION={classification}"
    )

    print(
        f"031E_PROMOTION_AUTHORIZED={promotion}"
    )

    print(
        "FULL_EXACT_FLOAT64_CURVED_MATTER_BVP="
        "NO"
    )

    print(
        "FULL_CURVED_COVARIANT_CONSERVATION_CLAIM="
        "NO_PERTURBATIVE_SMALL_CURVATURE_CERTIFICATE_ONLY"
    )

    print(
        "NONLINEAR_FRAGMENTATION_CLOSED=NO"
    )

    print(
        "CARRIER_RESOLVED_SWITCHING_CLOSED=NO"
    )

    print(
        "HIGHER_HARMONIC_MULTIPARTICLE_RADIATION_CLOSED=NO"
    )

    print(
        "EFT_NATURALNESS_EMPIRICAL_CLOSURE=NO"
    )

    print(
        "LAB_FIXED_SUPPORT_HARDWARE_CLOSED=NO"
    )

    print(
        "PRACTICAL_DEVICE=NO"
    )

    print(
        f"NEXT={next_action}"
    )

    profile_stride = max(
        1,
        x.size
        // 2500,
    )

    profile_rows = []

    for index in range(
        0,
        x.size,
        profile_stride,
    ):

        profile_rows.append(
            {
                "x":
                    float(
                        x[
                            index
                        ]
                    ),

                "r_m":
                    float(
                        r[
                            index
                        ]
                    ),

                "rho_dimless":
                    float(
                        rho[
                            index
                        ]
                    ),

                "pr_dimless":
                    float(
                        pr[
                            index
                        ]
                    ),

                "pt_dimless":
                    float(
                        pt[
                            index
                        ]
                    ),

                "enclosed_mass_kg":
                    float(
                        enclosed_mass[
                            index
                        ]
                    ),

                "compactness":
                    float(
                        compactness[
                            index
                        ]
                    ),

                "nu":
                    float(
                        nu[
                            index
                        ]
                    ),

                "lambda_metric":
                    float(
                        lambda_metric[
                            index
                        ]
                    ),
            }
        )

    payload_rows = []

    for mu_surface, radius_surface, accel_surface in zip(
        surface_mu,
        surface_r,
        surface_projected,
        strict=True,
    ):

        payload_rows.append(
            {
                "surface_mu":
                    float(
                        mu_surface
                    ),

                "source_radius_m":
                    float(
                        radius_surface
                    ),

                "projected_jordan_accel_mps2":
                    float(
                        accel_surface
                    ),
            }
        )

    summary = {
        "classification":
            classification,

        "next":
            next_action,

        "claim_class":
            (
                "WEAK_CURVATURE_EINSTEIN_JORDAN_"
                "GEODESIC_BACKREACTION_CERTIFICATE"
            ),

        "provenance": {
            "d3d2r":
                d2r[
                    "classification"
                ],

            "r5":
                r5[
                    "classification"
                ],

            "d3ar2":
                d3ar2[
                    "classification"
                ],
        },

        "geometry": {
            "payload_center_global_m":
                payload_center_global_m,

            "source_shift_m":
                source_shift_m,

            "payload_center_from_source_m":
                payload_center_from_source_m,

            "payload_radius_m":
                payload_radius_m,

            "reference_flat_cm_mps2":
                reference_cm,

            "reference_surface_min_mps2":
                reference_surface_min,

            "inherited_X_overlap":
                inherited_overlap,
        },

        "stress_energy": {
            "energy_scale_J":
                energy_scale_J,

            "source_rebuilt_J":
                source_rebuilt_J,

            "source_certified_exact_J":
                exact_source_on_J,

            "source_relerr":
                source_energy_relerr,

            "total_rebuilt_J":
                total_rebuilt_J,

            "total_certified_exact_J":
                exact_on_J,

            "total_relerr":
                total_energy_relerr,

            "conservative_inventory_J":
                conservative_on_J,

            "anisotropy_identity_relerr":
                anisotropy_relerr,

            "flat_conservation_analytic_relerr":
                flat_conservation_analytic_relerr,

            "flat_conservation_numeric_relerr":
                flat_conservation_numeric_relerr,

            "DEC_max_ratio":
                dec_max,

            "pass":
                bool(
                    energy_pass
                    and
                    stress_pass
                ),
        },

        "einstein": {
            "ADM_mass_kg":
                adm_mass_kg,

            "ADM_energy_J":
                adm_energy_J,

            "ADM_relerr":
                adm_relerr,

            "max_compactness":
                max_compactness,

            "max_abs_nu":
                float(
                    np.max(
                        np.abs(
                            nu
                        )
                    )
                ),

            "positive_ADM":
                positive_adm,

            "no_horizon":
                no_horizon,

            "curved_conservation_source_relative":
                curved_conservation_source_rel,

            "R5_gap":
                physical_gap,

            "self_metric_over_gap":
                self_metric_over_gap,

            "metric_pass":
                einstein_pass,

            "perturbative_backreaction_pass":
                perturbative_backreaction_pass,
        },

        "physical_metric": {
            "M_c_GeV":
                M_c_GeV,

            "M_m_GeV":
                M_m_GeV,

            "Mc_over_Mm_squared":
                matter_ratio_sq,

            "center_jordan_mps2":
                center_jordan,

            "center_scalar_flat_mps2":
                center_scalar,

            "center_einstein_mps2":
                center_gr,

            "payload_cm_jordan_mps2":
                a_cm_jordan,

            "payload_cm_scalar_flat_mps2":
                a_cm_scalar,

            "payload_cm_einstein_mps2":
                a_cm_gr,

            "surface_min_mps2":
                surface_min,

            "surface_max_mps2":
                surface_max,

            "cm_reference_relerr":
                cm_reference_relerr,

            "surface_reference_relerr":
                surface_reference_relerr,

            "GR_fraction":
                gr_fraction,

            "pass":
                finite_payload_pass,
        },

        "far_field": {
            "scan_end_m":
                FAR_FIELD_MAX_M,

            "scan_end_accel_mps2":
                float(
                    far_a[
                        -1
                    ]
                ),

            "repulsive_to_attractive_zero_m":
                zero_radius,

            "positive_ADM_asymptotic_attraction":
                positive_adm_farfield,

            "pass":
                farfield_pass,
        },

        "payload_backreaction": {
            "payload_mass_kg":
                PAYLOAD_MASS_KG,

            "scalar_reaction_ratio":
                payload_scalar_reaction,

            "metric_driver":
                payload_metric_driver,

            "metric_driver_over_R5_gap":
                payload_metric_over_gap,

            "interaction_force_N":
                interaction_force_N,

            "free_source_recoil_diagnostic_mps2":
                free_source_recoil_mps2,

            "lab_fixed_support_realized":
                False,

            "pass":
                payload_backreaction_pass,
        },

        "decision": {
            "prerequisites":
                prerequisites,

            "promotion_authorized":
                promotion,
        },

        "claim_limits": [
            (
                "GREEN is a weak-curvature perturbative "
                "Einstein-backreaction certificate, not a direct "
                "float64 resolution of 1e-32 matter-field shifts."
            ),
            (
                "The exact Hamiltonian sources the Einstein metric. "
                "The approximately 127.8-GJ conservative inventory "
                "remains the engineering upper ledger."
            ),
            (
                "Ordinary matter follows the Jordan metric directly; "
                "no fifth-force acceleration is added by hand."
            ),
            (
                "The primary payload result is an isolated finite "
                "test payload released from rest relative to the "
                "self-supported soliton."
            ),
            (
                "A free microscopic source recoils strongly against "
                "a 1-kg payload because its inertial mass-equivalent "
                "is only of order a microgram."
            ),
            (
                "A laboratory-fixed support apparatus is not realized "
                "and no support stress-energy is hidden in the ledger."
            ),
            (
                "Carrier-resolved nonlinear switching, fragmentation "
                "and higher-harmonic/multiparticle radiation remain open."
            ),
            (
                "EFT/naturalness and empirical fifth-force/EP/PPN "
                "closure remain open."
            ),
            (
                "No practical antigravity device is established."
            ),
        ],
    }

    OUT_JSON.write_text(
        json.dumps(
            builtin(
                summary
            ),
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )

    with OUT_PROFILE.open(
        "w",
        newline="",
    ) as handle:

        writer = csv.DictWriter(
            handle,
            fieldnames=list(
                profile_rows[
                    0
                ].keys()
            ),
        )

        writer.writeheader()

        writer.writerows(
            profile_rows
        )

    with OUT_PAYLOAD.open(
        "w",
        newline="",
    ) as handle:

        writer = csv.DictWriter(
            handle,
            fieldnames=list(
                payload_rows[
                    0
                ].keys()
            ),
        )

        writer.writeheader()

        writer.writerows(
            payload_rows
        )

    print(
        f"SUMMARY_JSON={OUT_JSON}"
    )

    print(
        f"PROFILE_CSV={OUT_PROFILE}"
    )

    print(
        f"PAYLOAD_CSV={OUT_PAYLOAD}"
    )


if __name__ == "__main__":
    main()
